### ISSUE TITLE
关于etcd证书问题

### ISSUE THREAD

**Issue by zhashuyu** [gjmzj/kubeasz#1]
关于大侠写的etcd生成证书那块，有个疑问，我发现脚本里etcd证书是在etcd节点上生成的，那么如果有三个etcd节点，就会生成三套证书，这样子的话，三个节点之间是怎么认证的，kube-apiserver和calico用的是哪套证书，怎么实现正常通信的？

**Comment by gjmzj** [comment]
如果有三个etcd节点，确实生成三套证书，但是因为是同一个CA签发的，所以三个节点用各自证书能够彼此认证，关于kube-apiserver是用同一个CA签发的kubernetes证书，使用这个证书与 etcd集群之间认证交互的，关于calico 当时为了方便是直接用etcd1生成的证书与etcd集群之间交互。
