### ISSUE TITLE
如何将运行的image的端口外对映射出来?

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#10]
@gjmzj 大神,请教一下,

我按您的教程顺利安装布置成功了.但现在有个问题,我在运行pod的时候,境像里的端口对外如何映射出来呢? 
我尝试几个方法均不成功,不知道能不能得到您的指点? 谢谢了!!

Create nginx pod:
kubectl run nginx --image=nginx --port=80

Expose nginx as a service:
kubectl expose deployment nginx --target-port=80 --type=NodePort

root@k8-d-1:~# kubectl get po
NAME                     READY     STATUS    RESTARTS   AGE
nginx-7cbc4b4d9c-vkwpg   1/1       Running   0          6m

root@k8-d-2:~# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
8ff15f173594        nginx                                    "nginx -g 'daemon ..."   6 minutes ago       Up 6 minutes                            k8s_nginx_nginx-7cbc4b4d9c-vkwpg_default_5aaf73d1-db22-11e7-8d3c-000c292c98d7_0
7e18250b1b6b        mirrorgooglecontainers/pause-amd64:3.0   "/pause"                 6 minutes ago       Up 6 minutes                            k8s_POD_nginx-7cbc4b4d9c-vkwpg_default_5aaf73d1-db22-11e7-8d3c-000c292c98d7_0
0473991c21e5        calico/node:v2.6.2                       "start_runit"            2 hours ago         Up 2 hours                              calico-node
root@k8-d-2:~# docker logs 8ff15f173594

**Comment by gjmzj** [comment]
你看一下 `kubectl get svc` 会看到类似
``` bash
kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)       AGE
kubernetes   ClusterIP   10.68.0.1       <none>        443/TCP       4h
nginx        NodePort    10.68.117.172   <none>        80:7215/TCP   8s
``` 
浏览器访问 $NodeIP:7215即可

**Comment by evenye** [comment]
@gjmzj 谢谢您,果然成功了,非常感谢您提供这么好的工具!!!! 

我能再请教一下吗? 我在kubectl run的时候,它自动分配到某一台node上去了,如果我重启这个node节点后,能让它自动漂移到另外一台机器上去吗? 
假如漂移到另外一台机器上,我能用VIP的地址直接映射这个端口吗? 这样就可以实现无论它漂移到哪里,联接方式都一样. 
谢谢您! 再次感谢万分!!!

**Comment by gjmzj** [comment]
你说的功能其实是最基本的功能，随着你的学习，这些功能都可以一个个去实践，
第一个问题，你可以用 kubectl cordon /drain 命令去实现，可以参考[这里](http://blog.csdn.net/xingwangc2014/article/details/51204224)
第二个问题，只要service不删除，一直可以用这个映射端口，而且 $NodeIp 可以是任意一个node节点的地址，不管这个pod运行在哪个node

**Comment by evenye** [comment]
@gjmzj 谢谢您的耐心指点. 理解像您这样的高手还这么耐心指点新手! 万分感谢!
按您的指导,我google也学习中.  您说的功能我都实现了 谢谢!
