### ISSUE TITLE
07.kube-node.yml 报错

### ISSUE THREAD

**Issue by guoxiaopeng** [gjmzj/kubeasz#102]
安装多主集群第七步后报错如下：这是什么原因呢？
TASK [kube-node : 运行calico-kube-controllers] ****************************************************************************
skipping: [192.168.27.113]
skipping: [192.168.27.114]
fatal: [192.168.27.112]: FAILED! => {"changed": true, "cmd": "sleep 15 && /root/local/bin/kubectl create -f /root/local/kube-system/calico/rbac.yaml && /root/local/bin/kubectl create -f /root/local/kube-system/calico/calico-kube-controllers.yaml", "delta": "0:00:15.275831", "end": "2018-02-02 13:00:47.592648", "msg": "non-zero return code", "rc": 1, "start": "2018-02-02 13:00:32.316817", "stderr": "error: You must be logged in to the server (the server has asked for the client to provide credentials)", "stderr_lines": ["error: You must be logged in to the server (the server has asked for the client to provide credentials)"], "stdout": "", "stdout_lines": []}
...ignoring

![Uploading image.png…]()

**Comment by guoxiaopeng** [comment]
安装完成后，执行kubectl get nodes命令提示如下：
error: You must be logged in to the server (Unauthorized

**Comment by gjmzj** [comment]
前面几步都成功了吗？看错误提示说连不上api-server，是否第三步 03.kubectl.yml 执行有问题？

**Comment by guoxiaopeng** [comment]
重新安装后问题解决，谢谢！

**Comment by guoxiaopeng** [comment]
你这种方式安装完成以后，如下执行get nodes 只显示node不会显示master的信息么？
[root@node7 ~]# kubectl get nodes
NAME             STATUS    ROLES     AGE       VERSION
192.168.27.112   Ready     <none>    26m       v1.9.1
192.168.27.113   Ready     <none>    26m       v1.9.1
192.168.27.114   Ready     <none>    26m       v1.9.1
 还有k8s外访问master的ip和端口不能访问，使用node+端口的方式可以访问。如何使用master+端口 的方式访问呢？

**Comment by gjmzj** [comment]
如何使用master+端口 的方式访问呢？
其实只要在master节点安装kube-proxy就行了，但是master节点最好还是功能单一点，不要去运行太多服务

**Comment by guoxiaopeng** [comment]
十分感谢，我是想咨询安装完成后kubectl get nodes 只显示角色是node的机器（如上图ip为112,113,114），master机器不显示(ip为115则不显示)。怎么把master也显示出来？

**Comment by gjmzj** [comment]
`kubectl get nodes`据我所知只会显示nodes节点啊，除非master节点同时也是node节点；而对于多节点集群，master节点还是独立规划吧
