### ISSUE TITLE
dashboard无法登录

### ISSUE THREAD

**Issue by henghasaint** [gjmzj/kubeasz#103]
各主机配置如下：
[hosts.txt](https://github.com/gjmzj/kubeasz/files/1694241/hosts.txt)
安装后master节点和node节点验证正常，使用的calico.
安装dashboard1.8.2后，报错如下：
kubectl get pod --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   calico-kube-controllers-5c6b98d9df-xdqzv   1/1       Running   0          1h        192.168.0.222    192.168.0.222
kube-system   calico-node-4kvxb                          2/2       Running   0          1h        192.168.0.221    192.168.0.221
kube-system   calico-node-5vqwb                          2/2       Running   0          1h        192.168.0.222    192.168.0.222
kube-system   calico-node-kl2gl                          2/2       Running   0          1h        192.168.0.223    192.168.0.223
kube-system   heapster-7b76dbf757-zlx8x                  1/1       Running   0          24m       172.20.250.195   192.168.0.223
kube-system   kubernetes-dashboard-7c74685c48-rj77j      1/1       Running   0          1h        172.20.248.1     192.168.0.221
kube-system   monitoring-grafana-64747d765f-phknd        1/1       Running   0          24m       172.20.250.193   192.168.0.223
kube-system   monitoring-influxdb-7dd6654659-6z985       1/1       Running   0          24m       172.20.250.194   192.168.0.223

[root@deploy-c7 down]# kubectl get pod -n kube-system | grep dashboard

kubernetes-dashboard-7c74685c48-rj77j      1/1       Running   0          1h

[root@deploy-c7 down]# kubectl cluster-info|grep dashboard
kubernetes-dashboard is running at https://192.168.0.204:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboar:/proxy
[root@deploy-c7 down]#  kubectl logs kubernetes-dashboard-7c74685c48-rj77j -n kube-system
2018/02/05 06:16:33 Using in-cluster config to connect to apiserver
2018/02/05 06:16:33 Starting overwatch
2018/02/05 06:16:33 Using service account token for csrf signing
2018/02/05 06:16:33 No request provided. Skipping authorization
2018/02/05 06:16:33 Successful initial request to the apiserver, version: v1.9.1
2018/02/05 06:16:33 Generating JWE encryption key
2018/02/05 06:16:33 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/02/05 06:16:33 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/02/05 06:16:35 Storing encryption key in a secret
2018/02/05 06:16:35 Creating in-cluster Heapster client
2018/02/05 06:16:35 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2018/02/05 06:16:35 Auto-generating certificates
2018/02/05 06:16:36 Successfuly created and stored certificates
2018/02/05 06:16:36 Serving securely on HTTPS port: 8443
2018/02/05 07:09:08 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2018/02/05 07:09:38 Metric client health check failed: an error on the server ("unknown") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
2018/02/05 07:10:08 Metric client health check failed: an error on the server ("unknown") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
2018/02/05 07:23:15 Metric client health check failed: an error on the server ("Error: 'dial tcp 172.20.250.195:8082: getsockopt: connection timed out'\nTrying to reach: 'http://172.20.250.195:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
2018/02/05 07:25:52 Metric client health check failed: an error on the server ("Error: 'dial tcp 172.20.250.195:8082: getsockopt: connection timed out'\nTrying to reach: 'http://172.20.250.195:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.

**Comment by gjmzj** [comment]
你这个报错好像是因为没有安装kubedns

**Comment by henghasaint** [comment]
清理集群，删除证书文件，重新安装了一次.kubedns正常运行。
访问： https://192.168.0.204:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
页面提示：

  |  
-- | --
kind | "Status"
apiVersion | "v1"
metadata | {}
status | "Failure"
message | "services \"https:kubernetes-dashboard:\" is forbidden: User \"admin\" cannot get services/proxy in the namespace \"kube-system\""
reason | "Forbidden"
details |  
name | "https:kubernetes-dashboard:"
kind | "services"
code | 403
##################################
[root@deploy-c7 ssl]# kubectl get pod --all-namespaces 
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5c6b98d9df-tfcc6   1/1       Running   0          33m
kube-system   calico-node-94v86                          2/2       Running   0          33m
kube-system   calico-node-r26zc                          2/2       Running   0          33m
kube-system   calico-node-xlsg5                          2/2       Running   0          33m
kube-system   heapster-7b76dbf757-cllzq                  1/1       Running   0          31m
kube-system   kube-dns-566c7c77d8-gdrbz                  3/3       Running   0          31m
kube-system   kubernetes-dashboard-7c74685c48-7sndq      1/1       Running   0          30m
kube-system   monitoring-grafana-64747d765f-mcc2v        1/1       Running   0          31m
kube-system   monitoring-influxdb-7dd6654659-r657h       1/1       Running   0          31m
[root@deploy-c7 ssl]# kubectl logs kubernetes-dashboard-7c74685c48-7sndq   -n kube-system
2018/02/06 01:32:43 Starting overwatch
2018/02/06 01:32:43 Using in-cluster config to connect to apiserver
2018/02/06 01:32:43 Using service account token for csrf signing
2018/02/06 01:32:43 No request provided. Skipping authorization
2018/02/06 01:32:43 Successful initial request to the apiserver, version: v1.9.1
2018/02/06 01:32:43 Generating JWE encryption key
2018/02/06 01:32:43 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/02/06 01:32:43 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/02/06 01:32:43 Storing encryption key in a secret
2018/02/06 01:32:43 Creating in-cluster Heapster client
2018/02/06 01:32:43 Auto-generating certificates
2018/02/06 01:32:43 Successfuly created and stored certificates
2018/02/06 01:32:43 Serving securely on HTTPS port: 8443
2018/02/06 01:53:12 Metric client health check failed: an error on the server ("Error: 'dial tcp 172.20.248.1:8082: getsockopt: connection timed out'\nTrying to reach: 'http://172.20.248.1:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
[root@deploy-c7 ssl]# date
Tue Feb  6 09:56:58 CST 2018

**Comment by henghasaint** [comment]
![image](https://user-images.githubusercontent.com/6634464/35846694-a4e5f240-0b52-11e8-83e5-d65bc60237c0.png)

k8s_heapster_heapster容器有这个报错

**Comment by gjmzj** [comment]
关于admin没权限登陆的话，是否忘记rbac配置
``` bash
$ kubectl create -f /etc/ansible/manifests/dashboard/ui-admin-rbac.yaml
$ kubectl create -f /etc/ansible/manifests/dashboard/ui-read-rbac.yaml
```
关于网络不通，是不是在公有云虚机安装的集群，如果是的话，请尽量使用flannel网络插件，还要特别注意集群各个nodes主机的安全组设置

**Comment by henghasaint** [comment]
除了一台node节点是物理机，其他的主机全是KVM虚机，我试一下flannel

**Comment by henghasaint** [comment]
[deploy]
192.168.0.233

[etcd]
192.168.0.183
192.168.0.184
192.168.0.185

[kube-master]
192.168.0.187
192.168.0.188

[lb]
192.168.0.191
192.168.0.192

[kube-node]
192.168.0.221
192.168.0.222
192.168.0.223

[harbor]
192.168.0.144
以上集群节点
############
换成flannel后，k8s_heapster_heapster容器的报错消失了
dashboard报错如下：
![image](https://user-images.githubusercontent.com/6634464/35902545-97b97398-0c16-11e8-8436-950bd79c3751.png)

docker logs k8s_influxdb_monitoring-influxdb-7dd6654659-xl5km_kube-system_0a1088e2-0bce-11e8-a310-c6ec9a902651_0 如下提示：
![image](https://user-images.githubusercontent.com/6634464/35902877-cb27c7d8-0c17-11e8-8fb4-e8dc004eeb83.png)

在node3上：
![image](https://user-images.githubusercontent.com/6634464/35903077-9bffc716-0c18-11e8-94bc-5922c11a5c8a.png)

**Comment by henghasaint** [comment]
用chrome浏览器打开后提示输入用户名和密码
而后提示如下：
![image](https://user-images.githubusercontent.com/6634464/35903825-be547458-0c1b-11e8-835f-774b6470aea0.png)
dns已经安装了

**Comment by gjmzj** [comment]
dashboard是按照本项目安装的1.8.2吗？
关于admin没权限登陆的话，是否忘记rbac配置
``` bash
$ kubectl create -f /etc/ansible/manifests/dashboard/ui-admin-rbac.yaml
$ kubectl create -f /etc/ansible/manifests/dashboard/ui-read-rbac.yaml
```
