### ISSUE TITLE
Deployment下Pod 的images版本更新问题

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#105]
@gjmzj 
请教一下, 用的是1.8.6搭建的cluster, 测试在线更新pod的images时,有二台总是成功,另外二台总是失败,提示如下错误:
root@kuber-3:~# kubectl get pod -o wide
NAME                               READY     STATUS             RESTARTS   AGE       IP               NODE
deployment-demo-5db6b6bdc4-9rtmn   1/1       Running            0          6m        172.20.127.214   10.10.10.233
deployment-demo-5db6b6bdc4-q5c9n   1/1       Running            0          6m        172.20.153.91    10.10.10.232
deployment-demo-5db6b6bdc4-rzdd5   1/1       Running            0          6m        172.20.153.92    10.10.10.232
deployment-demo-696f75b879-fws4h   0/1       InvalidImageName   0          1m        172.20.179.213   10.10.10.118
deployment-demo-696f75b879-gh2ss   0/1       InvalidImageName   0          1m        172.20.127.217   10.10.10.233
jenkins-c7bb86cb8-8nbjb            1/1       Running            0          7d        172.20.153.76    10.10.10.232
事实上,我每台node节点都是手动将新版本的images下载回来了,并且单独测试正常的. 请问有什么办法查看原因吗? 

kubectl set image deployment/deployment-demo deployment-demo=image=nginx:1.11.9
deployment "deployment-demo" image updated

root@kuber-2:~/upgrade-test# kubectl rollout status deployment/deployment-demo
Waiting for rollout to finish: 2 out of 4 new replicas have been updated...
error: watch closed before Until timeout
kubectl set image deployment/deployment-demo deployment-demo=image=nginx:1.11.9

**Comment by gjmzj** [comment]
1.去错误的节点上查看kubelet日志 `journalctl -u kubelet `
2.直接查错误pod的详细信息，例如`kubectl describe pod deployment-demo-696f75b879-fws4h`
寻找线索再往下排查吧

**Comment by evenye** [comment]
@gjmzj  真心感谢! 原来是这样. 
好奇怪,我用你的方法测试一切正常.但用我这个有问题的命令deployment-demo=image=nginx:1.11.9有二个节点升级是成功的,有二个节点就是失败的.
真心搞不懂啊. 但用您的命令下来就完全升级成功.
