### ISSUE TITLE
ingress访问问题

### ISSUE THREAD

**Issue by guoxiaopeng** [gjmzj/kubeasz#107]
ingress安装配置都没问题，ui界面里面也显示了对应的规则。但是通过外部访问node ip:23456缺不能访问。配置的域名也已经写在了nosts里面了，什么问题，该怎么排查。内部访问：[root@localhost ingress]# curl -H Host:tomcat.test.com 10.68.187.31 也没反应。

**Comment by gjmzj** [comment]
ingress问题你按照项目[ingress文档](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/ingress.md)实验下应该没啥问题；
你把ingress规则文件贴一贴看？

**Comment by guoxiaopeng** [comment]
ingress 中tomcat.yaml文件：
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat
spec:
  rules:
  - host: tomcat.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tomcat
          servicePort: 8080

[root@localhost ingress]# kubectl get svc |grep tomcat
tomcat       LoadBalancer   10.68.187.31   <pending>     8080:27966/TCP   22h
