### ISSUE TITLE
欢迎使用 anjia0532/gcr.io_mirror

### ISSUE THREAD

**Issue by anjia0532** [gjmzj/kubeasz#109]
为了方便国内用户安装k8s，我在去年11月做了一个gcr.io/google-containers的全镜像，基于Travis CI每日作业，执行bash脚本全量比对，增量更新。欢迎交流。
项目地址 https://github.com/anjia0532/gcr.io_mirror

**Comment by gjmzj** [comment]
感谢提供资源，后续可以做为项目使用的镜像源之一

**Comment by anjia0532** [comment]
恩恩，好的。具体同步代码 https://github.com/anjia0532/gcr.io_mirror/blob/sync/deploy.sh 。好处在于，不用维护img list,自动同步新增image或者新增tag,除非 docker hub停用或者Travis CI,github关闭，否则会一直同步更新（不用担心不及时或者不维护导致的不可用）。
k8s的安装太痛苦了，非常感谢您开源的这个项目，太方便了。哈哈。
