### ISSUE TITLE
Kubernetes master VIP 地址打开后提示错误

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#11]
我的集群建好后,我直接打开LB的VIP地址, https://10.10.2.17:8443/,它弹出对话框让我输用户名和密码.
我输入用户名和密码后,只能看到以下网页文字:
提示如下错误:
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {
},
"status": "Failure",
"message": "forbidden: User "admin" cannot get path "/"",
"reason": "Forbidden",
"details": {

},
"code": 403
}

10.10.2.17 这个是Kubernetes master 的虚拟IP, 可以ping通. 
整个安装环节我也反复重装过了,没有任何错误提示. 证明安装还是挺顺利的. 
能请大家指点一下吗? 谢谢啦!!

root@k8-d-2:~# kubectl cluster-info
Kubernetes master is running at https://10.10.2.17:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

**Comment by gjmzj** [comment]
这个是地址集群的apiserver地址，不是给用户浏览器去访问的，你如果想访问 dashboard的话可以在安装dashboard后 `kubectl get svc -n kube-system` 查看 dashboard服务的NodePort 方式去访问，如下用浏览器 $NodeIp:5529 去访问
``` bash
root@k8s402:/etc/ansible# kubectl get svc -n kube-system
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                       AGE
heapster               ClusterIP   10.68.40.85    <none>        80/TCP                        52s
kube-dns               ClusterIP   10.68.0.2      <none>        53/UDP,53/TCP                 1d
kubernetes-dashboard   NodePort    10.68.188.74   <none>        80:5529/TCP                   11s
```
如果你要用apiserver方式去访问dashboard，你要用admin登陆的话，并要去做RBAC绑定，后续我 `使用指南` 里面更新这个文档吧

**Comment by evenye** [comment]
谢谢您的指导! 期待您后继的指南,谢谢!!
