### ISSUE TITLE
flannel 网络如何发布主机路由

### ISSUE THREAD

**Issue by guojunmin1984** [gjmzj/kubeasz#110]
你好：
           我想问一下，用flannel组网的话，pod的ip，如何发布到机房网络中（可以和机房网络内其他主机ip互访），需要交换机做物理vlan和虚拟vlan的绑定吗？

**Comment by gjmzj** [comment]
flannel设计是为了k8s集群内部网络通讯的，当然pod可以访问外部主机ip，但是外部主机是不能主动访问pod网络的(使用ingress等暴露服务)；
如果你在寻找pod与外部主机互访的方案，可以去了解下cni的macvlan插件

**Comment by guojunmin1984** [comment]
如果我的pod网络所使用的ip段是和宿主机ip一样的真实ip段呢，这样的话，pod_ip 是否可以正常的和集群之外的ip互访呢

**Comment by guojunmin1984** [comment]
如果我的pod网络所使用的ip段是和宿主机ip一样的真实ip段呢，这样的话，pod_ip 是否可以正常的和集群之外的ip互访呢

**Comment by gjmzj** [comment]
@guojunmin1984 不可以，这样会有路由问题，除非你用的是macvlan等插件，我还没有尝试过

**Comment by guojunmin1984** [comment]
如果我使用您安装包里的Calico 的话，宿主机是否需要单独加一个网线，bgp协议是否从单独的一个网口发出，因为我的服务器现在默认只有一根网线

**Comment by gjmzj** [comment]
calico不需要单独网卡
