### ISSUE TITLE
Host docker or docker in tar ?

### ISSUE THREAD

**Issue by mingfengwuye** [gjmzj/kubeasz#113]
If I have already install docker in my ubuntu host, the docker bins in the tar file is needed or not ?
Will the two conflicts with each other ? Should i remove the host docker ?

**Comment by gjmzj** [comment]
you can keep your docker installation, and install k8s step by step, just skips the ` 04.docker.yml`.
but it's recommended to use this project's docker installation, it's all about configration and some useful tools.
