### ISSUE TITLE
k8s时区与服务器时区相差8小时问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#114]
k8s内部服务都是UTC时区，而我的服务器本身是CST时区，这个有影响吗？我allinone模式没有问题，多主多node就不可以，主要问题出现在calico或者flannel上，请问和这个时区有关系吗？

**Comment by gjmzj** [comment]
我使用的服务器也是CST时区，暂时没有出现问题，需要进一步实验。

**Comment by sunchangming** [comment]
安装的是最新的1.9.3版本，dashboard安装是执行kubectl create -f /etc/ansible/manifests/dashboard,然后执行kubectl get pod --all-namespaces查看所有的服务都是Running状态，利用kube-proxy访问dashboard页面，长时间没有反应，过一会之后，dashboard呈现CrashLoopBackOff状态，页面返回503，查看日志没有报错，然后在执行kubectl scale deploy kubernetes-dashboard --replicas=0 -n kube-system，删除之后执行kubectl scale deploy kubernetes-dashboard --replicas=1 -n kube-system，查看日志报错如下
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.68.0.1:443/version: dial tcp 10.68.0.1:443: getsockopt: no route to host
求大神指点

**Comment by sunchangming** [comment]
还有一点，时区不一样的话，那我创建的所有容器的时区都是UTC的，那如果用来跑业务也不合适吧？这个有办法更改一下镜像的时区吗？

**Comment by gjmzj** [comment]
@sunchangming 最新版1.9.3版本，貌似已经不支持旧版dashboard，请使用dashboard1.8.2，项目文档中有[dashboard1.8.2安装说明](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/dashboard-1.8.2.md)

**Comment by sunchangming** [comment]
@gjmzj  谢谢大神，我的集群已经成功了，后期会考虑时区的设置问题，弄好了之后会回来感谢大神。
