### ISSUE TITLE
分支v1.9即将删除通知

### ISSUE THREAD

**Issue by gjmzj** [gjmzj/kubeasz#115]
为了减少维护工作，分支v1.9即将删除；
目前分支v1.8和分支v1.9都是基于二进制方式安装的，包括网络插件部分，也就是这两个分支安装方式完全一致，所以选择保留一个；
master分支支持k8s v1.9，主要组件基于二进制安装，网络部分基于`daemonset Pod`方式安装，并且提供`flannel`和`calico`可选;

**Comment by peterpijing** [comment]
请问网络部分用daemonset Pod的部署方式比较好，还是分支v1.9的方式比较好了？

**Comment by gjmzj** [comment]
我觉得`daemonset Pod`就是方便一点，分支v1.9、分支v1.8使用`systemd service`方式需要自己的配置多点，但是排查问题也方便点
