### ISSUE TITLE
无法复制文件认证文件

### ISSUE THREAD

**Issue by daiab** [gjmzj/kubeasz#117]
ansible无法复制认证文件，但是src目录是有这些文件的， 比如这个文件是存在的/etc/kubernetes/ssl/ca.pem，但是报错AnsibleFileNotFound

TASK [deploy : 准备分发 CA证书] ************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFileNotFound: Could not find or access '/etc/kubernetes/ssl/ca.pem'
failed: [172.16.199.128] (item=ca.pem) => {"changed": false, "item": "ca.pem", "msg": "Could not find or access '/etc/kubernetes/ssl/ca.pem'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFileNotFound: Could not find or access '/etc/kubernetes/ssl/ca-key.pem'
failed: [172.16.199.128] (item=ca-key.pem) => {"changed": false, "item": "ca-key.pem", "msg": "Could not find or access '/etc/kubernetes/ssl/ca-key.pem'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFileNotFound: Could not find or access '/etc/kubernetes/ssl/ca.csr'
failed: [172.16.199.128] (item=ca.csr) => {"changed": false, "item": "ca.csr", "msg": "Could not find or access '/etc/kubernetes/ssl/ca.csr'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFileNotFound: Could not find or access '/etc/kubernetes/ssl/ca-config.json'
failed: [172.16.199.128] (item=ca-config.json) => {"changed": false, "item": "ca-config.json", "msg": "Could not find or access '/etc/kubernetes/ssl/ca-config.json'"}

**Comment by gjmzj** [comment]
你的ansible是使用root用户登陆的吗？
还有看下这些文件的权限 `ls -l /etc/kubernetes/ssl/`

**Comment by gjmzj** [comment]
别人遇到跟你一样的问题，是因为deploy节点搞错了，ansible脚本需要在deploy节点运行，参考#119
