### ISSUE TITLE
 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/kubernetes/ssl/ca.pem'

### ISSUE THREAD

**Issue by dotnet123** [gjmzj/kubeasz#119]
执行第一步的时候报这个错误.麻烦看下
![3](https://user-images.githubusercontent.com/21954452/37024138-056a7764-2163-11e8-87ec-5c788e26eb39.jpg)

**Comment by gjmzj** [comment]
这个问题是不是CA证书生成没有成功？你手动去该目录下查看下，如果文件在，确认下文件权限问题
昨天好像也有个提到这个问题，不知道怎么解决的，麻烦提供下你的环境：
centos7.x具体版本还是ubuntu1604，是allinone安装还是其他，还有其他可能有帮助的信息也提供下

**Comment by dotnet123** [comment]
CA证书都生成了
![4](https://user-images.githubusercontent.com/21954452/37030579-64aa3fbc-2176-11e8-88e4-f3c1c54c4d0f.jpg)
所有系统都是这个
![5](https://user-images.githubusercontent.com/21954452/37030581-64dbed78-2176-11e8-87f0-4146a462cab9.jpg)

**Comment by dotnet123** [comment]
[root@localhost ansible]# ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[root@localhost ansible]#

**Comment by dotnet123** [comment]
我找到原因了, 是我这边的问题,
[deploy]
10.1.4.224

但我实际操作的时候没在10.1.4.224 这个机器上,不够细心呀.

**Comment by gjmzj** [comment]
感谢提供反馈
