### ISSUE TITLE
ALLinONE模式安装

### ISSUE THREAD

**Issue by kitepad** [gjmzj/kubeasz#12]
我采用allinone的模式，按照你的教程步骤执行。我装的是virtualbox的虚拟机，两个网卡：一个NAT，一个HostOnly， 地址是192.168.56.100， 所以我把hosts中所有节点的地址都改为这个地址，ssh-copy-id时就会报错，需要root@192.168.56.100的密码，ubuntu缺省是没有的，我自己建了一个，可是一直不对，“Permission Deneid”。如果不管的话，后面执行安装，无法ssh 192.168.56.100这台机器。请问，可以不用root用户吗？

**Comment by gjmzj** [comment]
ubuntu 1缺省是没有root密码，2缺省不允许root密码登陆
所以你还需要修改ssh的配置 vi /etc/ssh/sshd_config
找到 PermitRootLogin 这一行，修改为PermitRootLogin yes
然后重启ssh服务 systemctl restart sshd

**Comment by kitepad** [comment]
谢谢！安装很快就完成了。也成功了三个组件，并且dashboard也可以访问。有一个小问题，因为都是root下安装，即使重启，也是无法访问kubectl等命令，因为都安装到了/root目录下，其它用户没有权限，只有给了执行权限后才可以访问。所以，可能安装到opt或usr下会更好。

再一次感谢！

**Comment by kitepad** [comment]
我如果想自己修改安装目录，是不是修改hosts文件中的bin_dir即可？另外，安装后的docker执行有问题，如
vagrant@vagrant:/var/run$ docker images
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/images/json: dial unix /var/run/docker.sock: connect: permission denied

vagrant@vagrant:~$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/version: dial unix /var/run/docker.sock: connect: permission denied

**Comment by kitepad** [comment]
需要把docker加到组里，是否可以把这几个命令加在prepare里呢？
