### ISSUE TITLE
能否使用openssl生成证书？

### ISSUE THREAD

**Issue by Matrix0xCC** [gjmzj/kubeasz#120]
cfssl需要下载3个工具，openssl基本上每个环境都有。

**Comment by gjmzj** [comment]
抱歉没有实践过，如果你有好的资料或者实践分享下

**Comment by gjmzj** [comment]
可以参考这个网址 https://rocdu.io/2017/12/%E7%94%9F%E6%88%90k8s%E8%AF%81%E4%B9%A6%E7%9A%84%E4%B8%89%E7%A7%8D%E6%96%B9%E5%BC%8F/
