### ISSUE TITLE
如何最简单实现pods网络隔离

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#122]
请教一下1.8x版本搭建的集群,calico为默认.

系统运行了10个pods,请问如何让其中二个pod能互相访问,但是跟其它8个pod 隔离开来? 

有什么简点的实例能够共享一下看看呢? 谢谢!!

@gjmzj @TracyBin @DiamondYuan

**Comment by gjmzj** [comment]
1.可以考虑把需要隔离的pod放在独立的namespace，那么可以按照项目文档中的使用场景1隔离
2.如果都在同一个namespace中，可以考虑使用pod的标签来进行隔离，可以阅读下项目文档中的`示例策略解读`

**Comment by evenye** [comment]
请问您说的第一点,是为他们建议独立的mamespace然后把pod放进去就可以实现隔离了吗? 文档中我并没有找到实列,只有一张图示.
您说的第二点,我通过使用pod的标签实现在隔离,但我必须先创建deny all 的networkpolicy,然后再创建第二个policy允许指定标签的pod 可以互相访问,不知道这样做是否正确?

谢谢!

**Comment by evenye** [comment]
谢谢您!
