### ISSUE TITLE
jenkins对接k8s API接口所需要的信息

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#123]
请问一下,我尝试用jenkins的k8s插件,它提示我需要以下信息:
Kubernetes server certificate key
Credentials
Kubernetes URL

请问二述二个信息我从哪里能查询到呢? 感谢!!

Error connecting: Failure executing: GET at: https://172.10.10.2:5888/api/v1/namespaces/default/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked..

**Comment by gjmzj** [comment]
jenkins需要的k8s的认证信息，我印象中可以使用kubeconfig，即使用/root/.kube/config中的信息
具体我没深入用过，这个信息应该容易搜索到

**Comment by evenye** [comment]
请教一下,我一直无法让jenkins插件正常访问k8s,提示错误如下;
Error connecting: Failure executing: GET at: https://10.231.215.223:5888/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
给请您给些建议么?

**Comment by evenye** [comment]
还是一样报相同的错误,苦恼中....

**Comment by peterpijing** [comment]
@evenye 和jenkins的结合认证搞定了吗？

**Comment by evenye** [comment]
还没有呢.一直在测试中.

**Comment by evenye** [comment]
已经解决.用以下方法.
 创建个ServiceAccount，绑定个有权限的role，然后把这个sa给你的jenkins用
示例:
-------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: build
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
--------------------------------

**Comment by songfuxing** [comment]
@evenye 你好，我也遇到这个问题，请问ca是怎么得到的，如何给jenkins用？

**Comment by evenye** [comment]
@songfuxing 
你好. 解决方法我特地贴上来了. 
就是你在起jenkins的.yaml文件中,增加ServiceAccount，绑定个有权限的role，然后把这个sa给你的jenkins用.
这里已经不需要用CA了,直接这样就可以联通jenkins和k8s. 当然你要注意在jenkins的configure - kubernetes里面,把URL填上即可.
