### ISSUE TITLE
动态添加master问题？

### ISSUE THREAD

**Issue by dotnet123** [gjmzj/kubeasz#124]
如果3台master的其中一台硬盘坏了，有好的解决方案吗？比如想再添加一台新的master,多谢指导。

**Comment by dotnet123** [comment]
感谢大神

**Comment by gjmzj** [comment]
请查看项目文档 https://github.com/gjmzj/kubeasz/blob/master/docs/guide/op/AddMaster.md

**Comment by dotnet123** [comment]
感谢

**Comment by dotnet123** [comment]
麻烦大神，我在问下，硬盘坏的那个master,直接在hosts文件的
[kube-master]节点下剔除这个ip就行了，是吧？etcd里面要删这个ip吗？

**Comment by dotnet123** [comment]
之前这个ip参加过竞选，怕etcd里有垃圾数据。

**Comment by gjmzj** [comment]
下线节点最好先清理相应的服务，然后在hosts里面删除掉，以免启动时意外开启之前的kube服务；
etcd里面的数据会更新的，不用担心
