### ISSUE TITLE
验证ansible安装的时候报错。

### ISSUE THREAD

**Issue by shanShanKate** [gjmzj/kubeasz#127]
一步步安装， 到了验证ansible安装的时候
ansible all -m ping   

提示 ERROR! Unexpected Exception, this is probably a bug: (cryptography 1.2.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=1.5'), set(['paramiko']))
the full traceback was:

请问是哪里的配置问题？

**Comment by gjmzj** [comment]
确认pip已按文档升级到最新，然后重新安装下ansible，再次执行验证，如果还有问题把错误代码完整贴出来，尝试baidu，google搜索

**Comment by shanShanKate** [comment]
好的 我再去重新装一遍， 谢谢。
