### ISSUE TITLE
 error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by dotnet123** [gjmzj/kubeasz#128]
昨天用20.addnodeyaml新加一个node都正常，今天新加一个node后，执行完也没有报错，可是在新node上执行kubectl get pod 就报如题的错误，重新执行了几遍就是不行。

**Comment by gjmzj** [comment]
新node上首先查看下kubeconfig是否与别的一致，`vi $HOME/.kube/config` 看看
另外，新node上可以执行服务验证：
`systemctl status kubelet`
`systemctl status kube-proxy`

**Comment by dotnet123** [comment]
与正常的.kube/config对比,只有client-certificate-data不一致.
`
[root@localhost ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-03-13 02:23:41 EDT; 6min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 6439 ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP (code=exited, status=0/SUCCESS)
  Process: 6434 ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 6432 ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 6430 ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
 Main PID: 6429 (kubelet)
    Tasks: 13
   Memory: 33.2M
   CGroup: /system.slice/kubelet.service
           └─6429 /root/local/bin/kubelet --address=10.1.4.221 --hostname-override=10.1.4.221 --pod-infra-container-image=mirrorgooglecontainers/pause-amd64:3.0 --experimental-bootstrap-kubeconfig=/e...

Mar 13 02:29:03 localhost.localdomain kubelet[6429]: I0313 02:29:03.360239    6429 kuberuntime_manager.go:758] checking backoff for container "kube-flannel" in pod "kube-flannel-ds-fzllw_...0c29044852)"
Mar 13 02:29:03 localhost.localdomain kubelet[6429]: I0313 02:29:03.360541    6429 kuberuntime_manager.go:768] Back-off 1m20s restarting failed container=kube-flannel pod=kube-flannel-ds-...00c29044852)
Mar 13 02:29:03 localhost.localdomain kubelet[6429]: E0313 02:29:03.360600    6429 pod_workers.go:186] Error syncing pod 96a4b2e9-2665-11e8-b766-000c29044852 ("kube-flannel-ds-fzllw_kube-system(96a4b...
Mar 13 02:29:17 localhost.localdomain kubelet[6429]: I0313 02:29:17.360187    6429 kuberuntime_manager.go:514] Container {Name:kube-flannel Image:jmgao1983/flannel:v0.10.0-amd64 Command:[...ObjectFieldS
Mar 13 02:29:17 localhost.localdomain kubelet[6429]: I0313 02:29:17.360243    6429 kuberuntime_manager.go:758] checking backoff for container "kube-flannel" in pod "kube-flannel-ds-fzllw_...0c29044852)"
Mar 13 02:29:17 localhost.localdomain kubelet[6429]: I0313 02:29:17.360356    6429 kuberuntime_manager.go:768] Back-off 1m20s restarting failed container=kube-flannel pod=kube-flannel-ds-...00c29044852)
Mar 13 02:29:17 localhost.localdomain kubelet[6429]: E0313 02:29:17.360376    6429 pod_workers.go:186] Error syncing pod 96a4b2e9-2665-11e8-b766-000c29044852 ("kube-flannel-ds-fzllw_kube-system(96a4b...
Mar 13 02:29:31 localhost.localdomain kubelet[6429]: I0313 02:29:31.359914    6429 kuberuntime_manager.go:514] Container {Name:kube-flannel Image:jmgao1983/flannel:v0.10.0-amd64 Command:[...ObjectFieldS
Mar 13 02:29:31 localhost.localdomain kubelet[6429]: I0313 02:29:31.359961    6429 kuberuntime_manager.go:758] checking backoff for container "kube-flannel" in pod "kube-flannel-ds-fzllw_...0c29044852)"
Mar 13 02:29:32 localhost.localdomain kubelet[6429]: I0313 02:29:32.542833    6429 kubelet.go:1880] SyncLoop (PLEG): "kube-flannel-ds-fzllw_kube-system(96a4b2e9-2665-11e8-b766-000c29044852)", event: ...
Hint: Some lines were ellipsized, use -l to show in full.
`
`
[root@localhost ~]# systemctl status kube-proxy
● kube-proxy.service - Kubernetes Kube-Proxy Server
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-03-13 02:23:36 EDT; 10min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 5951 (kube-proxy)
    Tasks: 0
   Memory: 4.6M
   CGroup: /system.slice/kube-proxy.service
           ‣ 5951 /root/local/bin/kube-proxy --bind-address=10.1.4.221 --hostname-override=10.1.4.221 --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig --logtostderr=true --v=2

Mar 13 02:34:15 localhost.localdomain kube-proxy[5951]: E0313 02:34:15.772509    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:15 localhost.localdomain kube-proxy[5951]: E0313 02:34:15.773165    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:16 localhost.localdomain kube-proxy[5951]: E0313 02:34:16.775639    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:16 localhost.localdomain kube-proxy[5951]: E0313 02:34:16.776086    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:17 localhost.localdomain kube-proxy[5951]: E0313 02:34:17.778876    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:17 localhost.localdomain kube-proxy[5951]: E0313 02:34:17.779547    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:18 localhost.localdomain kube-proxy[5951]: E0313 02:34:18.781751    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:18 localhost.localdomain kube-proxy[5951]: E0313 02:34:18.782805    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:19 localhost.localdomain kube-proxy[5951]: E0313 02:34:19.786015    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Mar 13 02:34:19 localhost.localdomain kube-proxy[5951]: E0313 02:34:19.786905    5951 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory....Unauthorized
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost ~]#
`

**Comment by dotnet123** [comment]
![1](https://user-images.githubusercontent.com/21954452/37319481-3190bda2-26aa-11e8-96d5-ad2bc2799bf5.jpg)

**Comment by dotnet123** [comment]
目前只有这台机器有问题, 我今天又新加了一台, 都正常的.

**Comment by gjmzj** [comment]
你直接把正常节点的kubeconfig复制到这台问题机器就行了
