### ISSUE TITLE
kubenetes master 网页无法打开

### ISSUE THREAD

**Issue by samlyhuang** [gjmzj/kubeasz#13]
操作系统：CentOS Linux release 7.2.1511 (Core) 

发现无法打开kubernetes master网页，具体操作如下：

1、获取cluster info
```
kubectl cluster-info              
Kubernetes master is running at https://192.168.31.100:8443
```

2、wget获取网页内容
```
wget https://192.168.31.100:8443
--2017-12-09 13:44:35--  https://192.168.31.100:8443/
正在连接 192.168.31.100:8443... 已连接。
错误: 无法验证 192.168.31.100 的由 “/C=CN/ST=HangZhou/L=XS/O=k8s/OU=System/CN=kubernetes” 颁发的证书:
  无法本地校验颁发者的权限。
要以不安全的方式连接至 192.168.31.100，使用“--no-check-certificate”。
```

3、
```
wget https://192.168.31.100:8443 --no-check-certificate
--2017-12-09 13:44:45--  https://192.168.31.100:8443/
正在连接 192.168.31.100:8443... 已连接。
警告: 无法验证 192.168.31.100 的由 “/C=CN/ST=HangZhou/L=XS/O=k8s/OU=System/CN=kubernetes” 颁发的证书:
  无法本地校验颁发者的权限。
已发出 HTTP 请求，正在等待回应... 401 Unauthorized
验证失败。
```

然后我本地查看master与node信息，发现集群状态正常：
```
 kubectl get nodes
NAME             STATUS    ROLES     AGE       VERSION
192.168.31.151   Ready     <none>    9m        v1.8.4
192.168.31.152   Ready     <none>    9m        v1.8.4
```

```
kubectl get componentstatus 
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-2               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}

```

这个是什么原因？

**Comment by nfmomo** [comment]
我也是这样，同问

**Comment by gjmzj** [comment]
因为apiserver对外只允许通过https访问，需要认证，你如果只想访问dashboard的话，在安装dashboard插件后用NodePort方式访问即可， `kubectl get svc -n kube-system|grep dashboard` 查看下端口

**Comment by coollei** [comment]
我是在ubunut16.04上使用allinone方式安装的，也遇到了这个问题。发现https://ip:6443/ui访问时，输入账号密码admin/test1234，不能弹出页面。但发现这台机器上的8080端口在127.0.0.1上也进行监听。并且在服务器上wget http://127.0.0.1:8080是正常，所以我在服务器上安装了桌面环境，然后在服务器的桌面环境中通过火狐访问http://127.0.0.1:8080/ui可以直接访问页面，连密码都不需要。解决方案就变成了以下两种
第一：如果8080端口也能在普通的服务器ip地址上监听，我们可以使用http://ip:8080/ui来使用。那么如何配置？
第二：如何解决使用admin/test1234 登陆https://ip:6443/ui 报错问题，报错返回json格式的错误，错误码为403

**Comment by gjmzj** [comment]
@coollei 
AllinOne部署的话，修改 /etc/systemd/system/kube-apiserver.service 找到 `--insecure-bind-address=127.0.0.1 \`把 127.0.0.1 修改为服务器的IP，保存退出，`systemctl daemon-reload && systemctl restart kube-apiserver`重启apiserver即可
第二，admin/test1234登陆访问不行，因为没有做RBAC配置，后续更新dashboard安装文档时再补充

**Comment by gjmzj** [comment]
@samlyhuang @nfmomo @coollei 关于dashboard的访问可以参考我更新的dashboard.md文档
