### ISSUE TITLE
连接dashboard超时？

### ISSUE THREAD

**Issue by panhongyin** [gjmzj/kubeasz#130]
部署1.9.3多masterHA模式环境时，部署过程都正常，pod启动也正常，
但登陆dashboard一直报如下的问题：

Error: 'dial tcp 172.20.0.4:8443: getsockopt: connection timed out'
Trying to reach: 'https://172.20.0.4:8443/'

请协助一下，谢谢。

部署1.8版本的就正常

**Comment by gjmzj** [comment]
这个问题已经在修改中了，原因是因为master节点没有安装kube-proxy，这两天更新解决

**Comment by gjmzj** [comment]
临时处理：
在hosts配置中把master节点IP都加入[new-node]组，
然后运行`ansible-playbook 20.addnode.yml`，
执行成功后即可。
当然现在所有master节点同时也成为了node节点，如果不想master节点运行业务pod，则需要使用`kubectl cordon` 命令手动禁止pod调度到master节点

**Comment by gjmzj** [comment]
release v194-r1 已解决该问题
