### ISSUE TITLE
连接dashbord问题

### ISSUE THREAD

**Issue by xiaozhiqi2000** [gjmzj/kubeasz#132]
1.9.3 多Master部署正常,dashbord pod启动正常，apiserver启用basic帐号密码认证出现问题

https://192.168.3.50:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

弹窗需要输入帐号密码，一直认证不了，就是重复的输入帐号密码，请大神协助！

**Comment by xiaozhiqi2000** [comment]
# cat /lib/systemd/system/kube-apiserver.service 
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target
[Service]
ExecStart=/usr/local/bin/kube-apiserver \
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction \
--advertise-address=192.168.3.48 \
--bind-address=192.168.3.48 \
--insecure-bind-address=127.0.0.1 \
--kubelet-https=true \
--anonymous-auth=false \
--basic-auth-file=/etc/kubernetes/ssl/basic-auth.csv \
--runtime-config=rbac.authorization.k8s.io/v1 \
--authorization-mode=RBAC,Node \
--enable-bootstrap-token-auth \
--token-auth-file=/etc/kubernetes/ssl/token.csv \
--service-cluster-ip-range=172.21.0.0/16 \
--service-node-port-range=20000-40000 \
--tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem \
--tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
--client-ca-file=/etc/kubernetes/ssl/ca.pem \
--service-account-key-file=/etc/kubernetes/ssl/ca-key.pem \
--etcd-cafile=/etc/kubernetes/ssl/ca.pem \
--etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem \
--etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem \
--etcd-servers=https://192.168.3.51:2379,https://192.168.3.52:2379,https://192.168.3.53:2379 \
--enable-swagger-ui=true \
--allow-privileged=true \
--apiserver-count=3 \
--audit-log-maxage=30 \
--audit-log-maxbackup=3 \
--audit-log-maxsize=100 \
--audit-log-path=/var/lib/audit.log \
--event-ttl=1h \
--v=2
Restart=on-failure
RestartSec=5
Type=notify
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target


-----------------------------------------------------------------------------------
# cat /etc/kubernetes/ssl/basic-auth.csv 
admin,test1234,1
readonly,readonly,2

-----------------------------------------------------------------------------------
# kubectl cluster-info|grep dashboard
kubernetes-dashboard is running at https://192.168.3.50:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

# kubectl get svc -n kube-system|grep dashboard
kubernetes-dashboard   NodePort    172.21.178.179   <none>        443:36058/TCP   47m

**Comment by gjmzj** [comment]
输入默认的 admin:test1234 不能登陆吗？

**Comment by xiaozhiqi2000** [comment]
不能登录，有需要提供的我可以提供信息

**Comment by gjmzj** [comment]
是不是同这个问题 https://github.com/gjmzj/kubeasz/issues/130

**Comment by xiaozhiqi2000** [comment]
是我这边的问题，在做baisc认证的时候的顺序搞错了，密码,用户名,序号)的格式，正确的格式，我实则是用户名，密码，序号，解决之后正常登录dashboard
