### ISSUE TITLE
清理集群时提示Device or resource busy，无法清理干净

### ISSUE THREAD

**Issue by luyx30** [gjmzj/kubeasz#136]
rmtree failed: [Errno 16] Device or resource busy: '/var/lib/docker/overlay/6eac69ad04c99475f240d49a6b0e97f94bc24c961a6afca292aa066358ca0322/merged

**Comment by gjmzj** [comment]
能否提供更多点信息

**Comment by luyx30** [comment]
参考这篇文章解决了。非安装脚本的问题。参考链接：https://blog.frognew.com/2018/02/k8s-unable-delete-pod-docker-device-busy.html
