### ISSUE TITLE
部署1个master多个node节点是第4部报错

### ISSUE THREAD

**Issue by buxiaomo** [gjmzj/kubeasz#137]
Hello：

部署1个master多个node节点时在第4步有下面这个报错，是不是二进制文件缺失。

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/bridge'
failed: [10.211.55.11] (item=bridge) => {"changed": false, "item": "bridge", "msg": "Could not find or access '/etc/ansible/bin/bridge'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/host-local'
failed: [10.211.55.11] (item=host-local) => {"changed": false, "item": "host-local", "msg": "Could not find or access '/etc/ansible/bin/host-local'"}`

二进制文件是在百度云下载的。

**Comment by gjmzj** [comment]
百度云的下载包是和项目release对应的，一般不能用最新的代码配套之前的下载包

**Comment by buxiaomo** [comment]
我切换的事1.8的分支，下载的是k8s.188.tar.gz这个文件

**Comment by buxiaomo** [comment]
可能是我切换分支没有切换过去，这个问题没有出现了，完美安装，谢谢
