### ISSUE TITLE
calico网络插件问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#138]
大神，用1.9.3版本的k8s，安装完成之后，node节点上有calico，但是master上没有，不是下载镜像慢的问题，这是怎么回事呢？现在导致dashboard访问不了，报错信息如下：
Could not enable metric client: Health check failed: an error on the server ("Error: 'dial tcp 172.42.46.65:8082: getsockopt: connection timed out'\nTrying to reach: 'http://172.42.46.65:8082/healthz'") has prevented the request from succeeding (get services heapster). Continuing.

**Comment by gjmzj** [comment]
同 ISSUE #130

**Comment by sunchangming** [comment]
谢谢大神，已经解决
