### ISSUE TITLE
controller-manager和scheduler与apiserver是通过8080端口通信，那么kubelet、kube-proxy呢？

### ISSUE THREAD

**Issue by liusl12** [gjmzj/kubeasz#139]
controller-manager和scheduler与apiserver是通过8080端口通信，那么kubelet、kube-proxy呢？如果是通过6443端口通信，haproxy配置的时候8443转发到6443的时候不需要配置证书认证吗？
老铁，能加个微信吗？我最近在研究多master HA架构，想请教您。
我的微信是LoveSoyeonForever

**Comment by gjmzj** [comment]
haproxy 使用4层模式，不需要证书

**Comment by luokeychen** [comment]
我昨天在公司机器也同样试了一下。
我没有用你提供的HAPROXY而是用了公司内部的LB的IP直接指定然后设置URL（原理差不多）。
配置成功但是在，Master Node上用kubectl get pods 提示我没有X509证书不能认证。
这个时候是不是需要把证书导入LB？
另外我想问一下，看代码好像LB死了整体也就是死了。是这样子吗？
谢谢

**Comment by gjmzj** [comment]
keepalive+haproxy有主备，不是单点，kubectl 使用的 ~/.kube/config 看看有没有问题
还有要确认你用公司的LB，是4层，还是7层，4层的话肯定没问题
