### ISSUE TITLE
kubedns-无法解析外网

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#14]
@gjmzj 请教一下,我看到您做了kubedns的新教程,按您的教程执行kubectl create -f /etc/ansible/manifests/kubedns/kubedns.yaml,系统提示均运行正常. 
最后我用kubectl run busybox --rm -it --image=busybox /bin/sh来做nslook解析时,前面您的那些例子我都可以正常解析,但是最后解析外网却不成功. 换成任何物理机的外网地址都不行,请问这是我哪里配置有错吗?  

谢谢!!
root@k8-d-1:~# kubectl run busybox --rm -it --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # nslookup www.baidu.com
Server:    10.68.0.
Address 1: 10.68.0.2 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'www.baidu.com'
/ # Session ended, resume using 'kubectl attach busybox-6bf46598ff-8lnkw -c busybox -i -t' command when the pod is running

**Comment by gjmzj** [comment]
默认pod是集成node的dns解析，是不是你的node也就是宿主机上本身就不能解析www.baidu.com?

**Comment by evenye** [comment]
我的四台宿主机都是可以直接联互联网的,ping也没有问题, 按您的教程搭建好后,我现在接着开始研究kubedns, 

root@k8-d-1:~# nslookup www.baidu.com
Server:         127.0.1.1
Address:        127.0.1.1#53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com.
Name:   www.a.shifen.com
Address: 115.239.211.112
Name:   www.a.shifen.com
Address: 115.239.210.27
root@k8-d-1:~# 


root@k8-d-1:~# kubectl get svc|grep nginx                          
nginx        ClusterIP   10.68.195.188   <none>        80/TCP    1h
root@k8-d-1:~# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.68.0.1       <none>        443/TCP   2d
nginx        ClusterIP   10.68.195.188   <none>        80/TCP    1h
root@k8-d-1:~# 
root@k8-d-1:~# kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-7cbc4b4d9c-62mbb   1/1       Running   0          1h
root@k8-d-1:~# 

我还有哪里地方忽略了吗? 我是按这里的教程来创建的:https://github.com/gjmzj/kubeasz/blob/master/docs/guide/kubedns.md
在另外一个地方我看到有这么个提示:运行 ansible-playbook 01.prepare.yml后会重新生成该目录下的kubedns.yaml 文件 -- 这里我需要重新运行一次吗? 

谢谢您的回复!

**Comment by evenye** [comment]
我重新运行kubectl create -f /etc/ansible/manifests/kubedns/kubedns.yaml报错. 
请问如何删除原来的服务再重建呢? 
root@k8-d-1:~# kubectl create -f /etc/ansible/manifests/kubedns/kubedns.yaml
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/kubedns/kubedns.yaml": configmaps "kube-dns" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/kubedns/kubedns.yaml": serviceaccounts "kube-dns" already exists
Error from server (Invalid): error when creating "/etc/ansible/manifests/kubedns/kubedns.yaml": Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.68.0.2": provided IP is already allocated
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/kubedns/kubedns.yaml": deployments.extensions "kube-dns" already exists

**Comment by gjmzj** [comment]
先如下删除，再重建
`kubectl delete deploy kube-dns -n kube-system`
`kubectl delete svc kube-dns -n kube-system`
`kubectl delete cm kube-dns -n kube-system`
`kubectl delete sa kube-dns -n kube-system`

**Comment by gjmzj** [comment]
其实就是提示什么重复，就删除什么就行了:)

**Comment by evenye** [comment]
@gjmzj  根据您的提示,我找到原因了. 
我的四台集群节点都是VM ubuntu 16.04自动获取IP地址的,安装完系统后它的/etc/resolv.conf 内容默认为:
nameserver 127.0.0.1
如果在这时执行kubectl create -f /etc/ansible/manifests/kubedns/kubedns.yaml,就会出现所述现象. 即使后来我手动将/etc/resolv.conf的内容修改也不行. 
我解决方法如下:
1. 按您的方法先删除原来建好的kubedns.
2. 手动修改/etc/resolv.conf的内容.
3. 再执行kubectl create -f /etc/ansible/manifests/kubedns/kubedns.yaml重建.
这样就完美解决了. 

感谢您!!!
@gjmzj   非常期待您接下来dashboard和ingress的安装配置!  谢谢!

**Comment by evenye** [comment]
resolved
