### ISSUE TITLE
HPA获取不到CPU使用率

### ISSUE THREAD

**Issue by xiaozhiqi2000** [gjmzj/kubeasz#143]
**k8s版本： 1.9.3**

[root@docker-k8s-01 ~]# kubectl get hpa php-apache
NAME                      REFERENCE               TARGETS                      MINPODS   MAXPODS   REPLICAS   AGE
php-apache   Deployment/php-apache   **unknown** / 50%      1                 10                 1               17m

**kube-controller-manager 是已经添加--horizontal-pod-autoscaler-use-rest-clients=false**
[root@docker-k8s-01 ~]# cat /lib/systemd/system/kube-controller-manager.service 
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
[Service]
ExecStart=/usr/local/bin/kube-controller-manager \
--address=127.0.0.1 \
--master=http://127.0.0.1:8080 \
--allocate-node-cidrs=true \
--service-cluster-ip-range=172.21.0.0/16 \
--cluster-cidr=172.20.0.0/16 \
--cluster-name=kubernetes \
--cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem \
--cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem \
--service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem \
--root-ca-file=/etc/kubernetes/ssl/ca.pem \
--horizontal-pod-autoscaler-use-rest-clients=false \
--leader-elect=true \
--v=2
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target

**报错信息**
Mar 22 17:39:45 docker-k8s-01 kube-controller-manager: E0322 17:39:45.626301    5935 horizontal.go:189] failed to compute desired number of replicas based on listed metrics for Deployment/default/php-apache: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster

请大神协助！

**Comment by gjmzj** [comment]
是否你没有安装kubedns 和 heapster

**Comment by xiaozhiqi2000** [comment]
kubedns和heapster是正常的

[root@docker-k8s-01 hpa]# kubectl get pods --all-namespaces -o wide | grep php-apache
default       php-apache-7564cc6b9f-dvlfx             0/1       Error     3          1m        172.20.36.7   docker-k8s-04
[root@docker-k8s-01 hpa]# kubectl logs php-apache-7564cc6b9f-dvlfx
AH00534: apache2: Configuration error: No MPM loaded.

看容器日志好像是镜像有问题

**Comment by gjmzj** [comment]
你是用项目里面的hpa实验吗？我刚测试过是没问题的。
如果heapster是好的，`kubectl top pod` 应该可以获取到pod的资源使用情况

**Comment by xiaozhiqi2000** [comment]
**是的，是项目中的实验，kubectl top pod可以获取资源使用情况**
[root@docker-k8s-01 efk]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
default       php-apache-5ddf9674b5-qdwcl             0/1       CrashLoopBackOff   2          1m        172.20.12.3   docker-k8s-05
kube-system   heapster-84b4d9f99c-v8kc4               1/1       Running            4          4d        172.20.36.6   docker-k8s-04
kube-system   kube-dns-5885479f8f-qnshr               3/3       Running            36         7d        172.20.11.4   docker-k8s-03
kube-system   kubernetes-dashboard-5bd6f767c7-gvgd6   1/1       Running            4          5d        172.20.12.4   docker-k8s-05
kube-system   monitoring-grafana-58bcf7d49b-dtl7b     1/1       Running            4          4d        172.20.36.2   docker-k8s-04
kube-system   monitoring-influxdb-6c4b84d695-dgbbr    1/1       Running            4          4d        172.20.12.2   docker-k8s-05

[root@docker-k8s-01 efk]# kubectl top pod heapster-84b4d9f99c-v8kc4 -n kube-system
NAME                        CPU(cores)   MEMORY(bytes)   
heapster-84b4d9f99c-v8kc4   1m           34Mi   

[root@docker-k8s-01 efk]# kubectl logs php-apache-5ddf9674b5-qdwcl
AH00534: apache2: Configuration error: No MPM loaded.

**Comment by xiaozhiqi2000** [comment]
**但是我使用nginx的镜像做测试是有效果的**

[root@docker-k8s-01 ~]# kubectl run nginx --image=nginx:1.7.9 --requests=cpu=0.06m --expose --port=80
[root@docker-k8s-01 ~]# kubectl autoscale deploy nginx --cpu-percent=50 --min=1 --max=10
[root@docker-k8s-01 ~]# kubectl get hpa nginx
NAME      REFERENCE          TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
nginx     Deployment/nginx   0% / 50%   1         10        1          10m


[root@docker-k8s-01 ~]# kubectl run --rm -it load-generator --image=busybox /bin/sh
Hit enter for command prompt
$ while true; do wget -q -O- http://nginx; done;

**另外一台主上查看nginx副本是有扩展的**
[root@docker-k8s-02 ~]# kubectl get hpa nginx
NAME      REFERENCE          TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
nginx     Deployment/nginx   3300% / 50%   1         10        **1**          14m
[root@docker-k8s-02 ~]# kubectl get hpa nginx
NAME      REFERENCE          TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
nginx     Deployment/nginx   3300% / 50%   1         10        **4**          14m

**Comment by gjmzj** [comment]
那应该是测试镜像的问题，使用nginx可以，说明hpa特性是起效的。

**Comment by xiaozhiqi2000** [comment]
后续再测试下，先close
