### ISSUE TITLE
大神，创建efk问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#145]
第一次创建efk没有问题，后来我把efk的pod删除了，然后在执行create的时候，报错如下，不知道是什么问题，请大神指教，谢谢
statefulset "elasticsearch-logging" created
daemonset "fluentd-es-v2.0.2" created
deployment "kibana-logging" created
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/es-service.yaml": services "elasticsearch-logging" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/es-statefulset.yaml": serviceaccounts "elasticsearch-logging" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/es-statefulset.yaml": clusterroles.rbac.authorization.k8s.io "elasticsearch-logging" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/es-statefulset.yaml": clusterrolebindings.rbac.authorization.k8s.io "elasticsearch-logging" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/fluentd-es-configmap.yaml": configmaps "fluentd-es-config-v0.1.1" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/fluentd-es-ds.yaml": serviceaccounts "fluentd-es" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/fluentd-es-ds.yaml": clusterroles.rbac.authorization.k8s.io "fluentd-es" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/fluentd-es-ds.yaml": clusterrolebindings.rbac.authorization.k8s.io "fluentd-es" already exists
Error from server (AlreadyExists): error when creating "/etc/ansible/manifests/efk/kibana-service.yaml": services "kibana-logging" already exists

**Comment by evanchn97** [comment]
你这里显示一些资源已经存在，是之前的删除并没有删除干净，请在仔细检查下

**Comment by evanchn97** [comment]
是这样，efk所使用的资源并不只包含POD，还有别的资源比如ConfigMap，serviceaccounts 等

**Comment by sunchangming** [comment]
@evanchn97  这些资源应该怎么彻底删除呢？

**Comment by evanchn97** [comment]
kubectl delete -f file1 -f file2 
或者:
kubectl delete -f dir/

**Comment by sunchangming** [comment]
@evanchn97  OK，非常感谢
