### ISSUE TITLE
nodeport 访问问题

### ISSUE THREAD

**Issue by guoxiaopeng** [gjmzj/kubeasz#146]
测试部署了两个项目nginx及一个我们自己的项目，访问模式改成nodeport模式，nginx 三个节点使用ip+port访问都没问题。自己的项目则只有一个节点可以访问
集群信息：
[root@master ~]# kubectl get no
NAME           STATUS    ROLES     AGE       VERSION
192.168.0.76   Ready     <none>    11d       v1.9.1
192.168.0.77   Ready     <none>    11d       v1.9.1
192.168.0.78   Ready     <none>    11d       v1.9.1
项目信息：
[root@master ~]# kubectl get pod,svc -n hspro
NAME                                READY     STATUS    RESTARTS   AGE
po/nginx-6d4b4788df-s6kqf           1/1       Running   0          25m
po/resource-saas-5944f86fcd-4fjsq   1/1       Running   0          1m

NAME                TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
svc/nginx           NodePort   10.68.64.226   <none>        80:36988/TCP     25m
svc/resource-saas   NodePort   10.68.31.247   <none>        8380:25477/TCP   1m

访问nginx：[root@master ~]# curl 192.168.0.76:36988 curl 192.168.0.77:36988 curl 192.168.0.78:36988  均没问题。
访问我们自己的项目： curl 192.168.0.76:25477(无法访问) curl 192.168.0.77:25477（(无法访问)） curl 192.168.0.78:25477（可以访问，实际pod运行在该节点）

**Comment by guoxiaopeng** [comment]
为了测试我又部署了一个tomcat服务，同样只有一个Node 节点ip+端口可以访问。

**Comment by gjmzj** [comment]
说不通，暂时没思路...

**Comment by gjmzj** [comment]
使用命令`iptables-save |grep 服务名` 查看每个节点是否一致，比如：
``` bash
$iptables-save |grep nginx
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx:" -m tcp --dport 25485 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx:" -m tcp --dport 25485 -j KUBE-SVC-4N57TFCL4MD7ZTDA
-A KUBE-SEP-S3MNNWJXT4KQNCZC -s 172.20.1.15/32 -m comment --comment "default/nginx:" -j KUBE-MARK-MASQ
-A KUBE-SEP-S3MNNWJXT4KQNCZC -p tcp -m comment --comment "default/nginx:" -m tcp -j DNAT --to-destination 172.20.1.15:80
-A KUBE-SERVICES -d 10.68.191.58/32 -p tcp -m comment --comment "default/nginx: cluster IP" -m tcp --dport 80 -j KUBE-SVC-4N57TFCL4MD
-A KUBE-SVC-4N57TFCL4MD7ZTDA -m comment --comment "default/nginx:" -j KUBE-SEP-S3MNNWJXT4KQNCZC
```

**Comment by guoxiaopeng** [comment]
使用命令iptables-save |grep 服务名三个节点看到的信息一致

**Comment by guoxiaopeng** [comment]
我觉得nginx之所以三个节点都能访问可能是nginx pod 实际运行的那台node (192.168.0.76)即是master也是node 会不会和这个有关系？其他服务的Pod 运行在了node 节点。按照这个思路该怎么排查下？

**Comment by guoxiaopeng** [comment]
可能是安装问题，重新部署k8s 1.96问题解决！谢谢
