### ISSUE TITLE
kubernetes-dashboard访问问题

### ISSUE THREAD

**Issue by huangclyz** [gjmzj/kubeasz#147]
calico网络使用daemonset部署之后，如果master主机不加入node集群中，master上是不会运行calico-node的，没有运行calico那么master就没有到node中pod的路由，那么dashboard通过master的ip是无法访问kube-dashboard的，需要单独在master上起一个calico进程，保证master和node之间的路由和通信，有什么好的方法解决

**Comment by gjmzj** [comment]
上周就解决了，请看更新说明

**Comment by gjmzj** [comment]
同 ISSUE #130
