### ISSUE TITLE
多master多node集群无法通过master ip+nodeport来访问应用

### ISSUE THREAD

**Issue by yuzhiquan** [gjmzj/kubeasz#15]
你好，我使用example中的多master部署的方式部署了一套集群，各项都正常，但是部署的应用以nodeport方式暴露端口后，发现只能通过应用所在的node ip+端口来访问，而不是可以通过master ip+port方式开访问，并且master集群三台机器通过netstat查看均无对应的nodeport，这个和我之前部署的好像不大一样，应该是通过master ip+nodeport方式可以直接访问service的，是否有哪里配置的不对，请指教？
多谢

**Comment by gjmzj** [comment]
@yuzhiquan 你的配置没错，按照项目预置生成的集群在master节点是不能通过master ip+port方式开访问，因为master节点没有安装kube-proxy，如果你有需求可以修改安装

**Comment by yuzhiquan** [comment]
只需要安装kube-proxy即可？需要做什么配置吗？
node节点是否需要按照？

**Comment by yuzhiquan** [comment]
我在各个node上安装了kube-proxy，也设置了damonset，但是看起来还是不行，master端需要做些什么吗？求助

**Comment by gjmzj** [comment]
node节点本来就已经安装kube-proxy，所有node节点使用nodeip+nodeport都可以访问应用，master节点建议不要安装kube-proxy. 你说的“在各个node上安装了kube-proxy，也设置了damonset”，估计冲突了，本来kube-proxy已经二进制方式安装好了，`systemctl status kube-proxy`可以查看，不能再用pod方式安装了

**Comment by yuzhiquan** [comment]
确实所有的kube-proxy因为端口被占在报error
这种情况下的话，我怎么实现master ip+nodeport访问啊，通过node+nodeport方式访问，一旦重新建立，应用就会去到其他node上
现在的情况是并不能通过集群中随意一个node ip来访问，而是必须要用应用pod所在的那个node的ip加端口来访问，这样好像不是正常的吧？

**Comment by gjmzj** [comment]
"现在的情况是并不能通过集群中随意一个node ip来访问，而是必须要用应用pod所在的那个node的ip加端口来访问" ，这个是不是你哪里配置有问题，如果你可以的话，建议清理后重新安装下集群`ansible-playbook 99.clean.yml`

**Comment by yuzhiquan** [comment]
另外，我这个是在阿里云网络环境配置calico，会出现什么问题吗？

**Comment by gjmzj** [comment]
阿里云上配置的话，保险起见修改 `roles/calico/templates/calico-node.service.j2` 找到 `-e CALICO_IPV4POOL_IPIP=off \`这一行，把off 改成 always，保存后再安装集群

**Comment by yuzhiquan** [comment]
阿里云貌似并不支持calico，所以我换成了flannel，虽然各个node上flannel.1虚拟网卡的地址都可以ping通，但是奇怪的是重启机器后，default命名空间里的kubernetes服务无法连接上了，导致kube-dns、kube-dashboard等等都无法启动了，这种情况遇到过吗？
具体来说就是集群内无法连接10.68.0.1:443了

**Comment by gjmzj** [comment]
@yuzhiquan 按照这个步骤：修改 roles/calico/templates/calico-node.service.j2 找到 -e CALICO_IPV4POOL_IPIP=off \这一行，把off 改成 always，保存后再安装集群，不管什么云都会支持calico的
你换成flannel，不知道你是怎么安装的，记得flannel也要用tls证书与 etcd集群通信

**Comment by yuzhiquan** [comment]
👍，确实改为ipip模式后，就可以了，看来bgp这个支持的太少了

**Comment by evenye** [comment]
@gjmzj 大神啊.感谢您的一直指点. 
关于您说的这句话: 按照项目预置生成的集群在master节点是不能通过master ip+port方式开访问，因为master节点没有安装kube-proxy，如果你有需求可以修改安装

我现在是想让某些服务以master ip + port的方式来访问,请问我具体可以修改哪里安装呢? 谢谢了!!!
