### ISSUE TITLE
efk对接ceph问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#151]
大神，请教一个问题，需求是把es的日志存放在存储里，现在用的是ceph，但是创建es的时候，挂载不上，报错如下：
Unable to mount volumes for pod "elasticsearch-logging-0_kube-system(09a7f917-3af5-11e8-b0c0-525453c0ef0a)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"elasticsearch-logging-0". list of unattached/unmounted volumes=[elasticsearch-logging]

**Comment by gjmzj** [comment]
ceph有rbd-provisioner和cephfs_provisioner，github上就有很好的文档，跟我的nfs-client-provisioner类似，https://github.com/kubernetes-incubator/external-storage/tree/master/ceph
