### ISSUE TITLE
flanneld网络无法启动成功

### ISSUE THREAD

**Issue by weilinqwe** [gjmzj/kubeasz#153]
环境： 6台centOS7.3 虚拟机，双master节点部署，1.9.4版本
[deploy]
192.168.11.91
[etcd]
192.168.11.91 NODE_NAME=etcd1 NODE_IP="192.168.11.91"
192.168.11.92 NODE_NAME=etcd2 NODE_IP="192.168.11.92"
192.168.11.93 NODE_NAME=etcd3 NODE_IP="192.168.11.93"
[kube-master]
192.168.11.92 NODE_IP="192.168.11.92"
192.168.11.93 NODE_IP="192.168.11.93"
[lb]
192.168.11.92 LB_IF="ens33" LB_ROLE=backup
192.168.11.93 LB_IF="ens33" LB_ROLE=master
[lb:vars]
master1="192.168.11.92:6443"
master2="192.168.11.93:6443"
ROUTER_ID=57
MASTER_PORT="8443"
[kube-node]
192.168.11.94 NODE_IP="192.168.11.94"
192.168.11.95 NODE_IP="192.168.11.95"
192.168.11.96 NODE_IP="192.168.11.96"

ansible-playbook 06.network.yml后两台master节点启动成功，三台node节点无法启动
[root@cloudhost5 ~]# kubectl get pod --all-namespaces
NAMESPACE     NAME                    READY     STATUS             RESTARTS   AGE
kube-system   kube-flannel-ds-dz6hs   0/1       CrashLoopBackOff   38         3h
kube-system   kube-flannel-ds-gpd2v   1/1       Running            0          3h
kube-system   kube-flannel-ds-kb86v   1/1       Running            3          3h
kube-system   kube-flannel-ds-sdwjg   0/1       CrashLoopBackOff   38         3h
kube-system   kube-flannel-ds-ws9gk   0/1       CrashLoopBackOff   39         3h

发现一台node节点已启动，还有两台CrashLoopBackOff.
[root@cloudhost5 ~]# kubectl logs kube-flannel-ds-ws9gk -n kube-system
E0409 05:51:09.717479       1 main.go:232] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-ws9gk': Get https://10.68.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-ws9gk: dial tcp 10.68.0.1:443: getsockopt: no route to host

是能看到这个clusterip的
[root@cloudhost5 ~]# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.68.0.1    <none>        443/TCP   5d

防火墙看起来master节点和node节点也一样

**Comment by weilinqwe** [comment]
镜像已经拉下来了：
[root@cloudhost5 ~]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
jmgao1983/flannel                    v0.10.0-amd64       f0fad859c909        2 months ago        44.6MB
mirrorgooglecontainers/pause-amd64   3.0                 99e59f495ffa        23 months ago       747kB

起不来原因是apiserver连不通
[root@cloudhost5 ~]# kubectl get pod --all-namespaces
NAMESPACE     NAME                    READY     STATUS             RESTARTS   AGE
kube-system   kube-flannel-ds-dz6hs   0/1       CrashLoopBackOff   68         5h
kube-system   kube-flannel-ds-gpd2v   1/1       Running            0          5h
kube-system   kube-flannel-ds-kb86v   1/1       Running            3          5h
kube-system   kube-flannel-ds-sdwjg   0/1       CrashLoopBackOff   68         5h
kube-system   kube-flannel-ds-ws9gk   0/1       CrashLoopBackOff   70         5h
[root@cloudhost5 ~]# kubectl logs kube-flannel-ds-dz6hs -n kube-system
I0409 08:36:58.871293       1 main.go:475] Determining IP address of default interface
I0409 08:36:58.872822       1 main.go:488] Using interface with name ens37 and address 10.18.13.62
I0409 08:36:58.965476       1 main.go:505] Defaulting external address to interface address (10.18.13.62)
**E0409 08:37:28.970024       1 main.go:232] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-dz6hs': Get https://10.68.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-dz6hs: dial tcp 10.68.0.1:443: i/o timeout**

**Comment by gjmzj** [comment]
你贴一下kubelet的错误日志，`journalctl -u kubelet -f`

**Comment by weilinqwe** [comment]
Apr 10 09:07:25 cloudhost5 kubelet[6379]: I0410 09:07:25.986423    6379 kuberuntime_manager.go:514] Container {Name:kube-flannel Image:jmgao1983/flannel:v0.10.0-amd64 Command:[/opt/bin/flanneld] Args:[--ip-masq --kube-subnet-mgr] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:POD_NAME Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}] Requests:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}]} VolumeMounts:[{Name:run ReadOnly:false MountPath:/run SubPath: MountPropagation:<nil>} {Name:flannel-cfg ReadOnly:false MountPath:/etc/kube-flannel/ SubPath: MountPropagation:<nil>} {Name:flannel-token-272bn ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Apr 10 09:07:25 cloudhost5 kubelet[6379]: I0410 09:07:25.986721    6379 kuberuntime_manager.go:758] checking backoff for container "kube-flannel" in pod "kube-flannel-ds-7646h_kube-system(95cf2d7a-3bd2-11e8-9eae-000c2905de47)"
Apr 10 09:07:25 cloudhost5 kubelet[6379]: I0410 09:07:25.987154    6379 kuberuntime_manager.go:768] Back-off 5m0s restarting failed container=kube-flannel pod=kube-flannel-ds-7646h_kube-system(95cf2d7a-3bd2-11e8-9eae-000c2905de47)
Apr 10 09:07:25 cloudhost5 kubelet[6379]: E0410 09:07:25.987226    6379 pod_workers.go:186] Error syncing pod 95cf2d7a-3bd2-11e8-9eae-000c2905de47 ("kube-flannel-ds-7646h_kube-system(95cf2d7a-3bd2-11e8-9eae-000c2905de47)"), skipping: failed to "StartContainer" for "kube-flannel" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-flannel pod=kube-flannel-ds-7646h_kube-system(95cf2d7a-3bd2-11e8-9eae-000c2905de47)"

**Comment by jmgao1983** [comment]
貌似日至没有特别有价值的信息；
另外想到你看下flannel相关的rbac设置是否正确：
``` bash
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---

```

**Comment by weilinqwe** [comment]
这个我没动过
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system

**Comment by weilinqwe** [comment]
这个我没动过
`---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system`

**Comment by weilinqwe** [comment]
这个配置文件没动过（/root/local/kube-system/flannel/kube-flannel.yaml）
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
```

**Comment by gjmzj** [comment]
暂时没有思路，你可以尝试`99.clean.yml`脚本删除整个集群后重装试试，或者再试试比如calico网络

**Comment by weilinqwe** [comment]
@jmgao1983 我怀疑由多网卡引起的，每个虚拟机由两张网卡，一张内网（192.168.11.0），一张外网（10.18.*），默认网关是外网。整个集群搭建时ip都是内网ip，所以cluster ip是建在内网网卡上的，而flannelid启动的时候找的默认网卡是外网网卡，三台工作节点通过外网网卡就访问不到10.68.0.1:443了，而两台master节点不知因为什么原因能访问到启动成功。 我把五台虚拟机的外网网卡ifdown之后，就因为找不到默认网卡就都起不来了，能否在flanneld配置里设置默认网卡

**Comment by weilinqwe** [comment]
@gjmzj @jmgao1983  问题已解决。就是多网卡的问题。 我把外网网卡down掉，然后把默认网关改成内网网卡，就能正常启动了。
