### ISSUE TITLE
etcd里面找不到 /registry 目录

### ISSUE THREAD

**Issue by amoyx** [gjmzj/kubeasz#154]
用kubeasz部署完kubernetes后，发现在etcd 里面没有 /registry 目录，但是其他节点都正常。要如何修复？
![image](https://user-images.githubusercontent.com/19795002/38569748-b38383a0-3d1e-11e8-93b9-92b6cdbedf03.png)
![image](https://user-images.githubusercontent.com/19795002/38570168-cc34f536-3d1f-11e8-9b4d-2c804515028f.png)

**Comment by jmgao1983** [comment]
现在k8s默认已经使用etcd v3版本的API记录数据。而默认etcdctl是使用v2版本的API，查看不到v3的数据，需要`export ETCDCTL_API=3`；
例如：
查询所有k8s存储在etcd的数据：
``` bash
ETCDCTL_API=3 etcdctl --endpoints="https://10.100.97.24:2379" --cacert=/etc/kubernetes/ssl/ca.pem --cert=/etc/etcd/ssl/etcd.pem --key=/etc/etcd/ssl/etcd-key.pem get --prefix /registry
```
查询某个数据：
``` bash
ETCDCTL_API=3 etcdctl --endpoints="https://10.100.97.24:2379" --cacert=/etc/kubernetes/ssl/ca.pem --cert=/etc/etcd/ssl/etcd.pem --key=/etc/etcd/ssl/etcd-key.pem get /registry/services/specs/default/kubernetes
```

**Comment by amoyx** [comment]
@jmgao1983 可以了，多谢！ 
![image](https://user-images.githubusercontent.com/19795002/38591846-658d57e6-3d6b-11e8-8ad5-905591b87d5b.png)
