### ISSUE TITLE
更改高可用master ip

### ISSUE THREAD

**Issue by yuzhiquan** [gjmzj/kubeasz#155]
之前用的一个虚ip因为种种原因无法继续使用了，需要更改高可用ip
证书需要更改
master配置需要更改
node配置估计也得更改
因为上面已经有服务了，所以需要考虑一定稳定性
这种情况下有没有比较稳妥的方案？

**Comment by jmgao1983** [comment]
首先 master那边要重新生成包含新vip的证书，然后修改 `kubectl` `kube-proxy`的配置，这些修改都还方便，就是kubelet连接的比较麻烦，因为它是靠bootstrap自动生成的证书，这个需要改好些地方，我看看能不能专门整个文档，除非你对整个集群运行架构很了解，建议先不要动

**Comment by yuzhiquan** [comment]
哦
或者有什么方案可以快速增加一个ip到证书的hosts里吗？

**Comment by gjmzj** [comment]
@yuzhiquan 我已经专门更新了一个集群操作文档，你可以参考下 https://github.com/gjmzj/kubeasz/blob/master/docs/guide/op/ChangeVIP.md

**Comment by yuzhiquan** [comment]
感谢，我们试下相应操作
