### ISSUE TITLE
集群搭建成功后开启dashboard失败#Failed to create SubnetManager

### ISSUE THREAD

**Issue by yummykang** [gjmzj/kubeasz#158]
Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-m8srl': Get https://10.68.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-m8srl: dial tcp 10.68.0.1:443: i/o timeout

可能是我的SERVICE_CIDR设置错误，我的内网是10.29.x.x

**Comment by weilinqwe** [comment]
这和我前几天碰到的问题类似， 10.68.0.1是apiserver service clusterid，很可能你有两张网卡，它找的默认网卡不对，把非k8s集群的那张网卡停掉，把默认网关改成k8s集群网络网关，再试试？

**Comment by weilinqwe** [comment]
这和我前几天碰到的问题类似#153， 10.68.0.1是apiserver service clusterid，很可能你有两张网卡，它找的默认网卡不对，把非k8s集群的那张网卡停掉，把默认网关改成k8s集群网络网关，再试试？

**Comment by yummykang** [comment]
我的日志是这样的：
Determining IP address of default interface
I0412 02:59:13.025831       1 main.go:488] Using interface with name eth1 and address x.x.x.x
I0412 02:59:13.025866       1 main.go:505] Defaulting external address to interface address (x.x.x.x)
E0412 02:59:43.027648       1 main.go:232] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-p4rmd': Get https://10.68.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-p4rmd: dial tcp 10.68.0.1:443: i/o timeout
我有一个eth0的内网网卡，还有一个eth1的，我关掉了eth0然后重新安装了一下还是不可以 @weilinqwe

**Comment by weilinqwe** [comment]
那猜是不是这样，估计你k8s是建在eth1上的，eth0是外网的，停掉eth0之后，会找到默认网卡eth1，就能访问到10.68.0.1这个clusterip了。但是因为eth0停掉，外网访问不了，就拉不到镜像了，报ImagePullBackOff错误？ 要不建个私有镜像库？

**Comment by yummykang** [comment]
谢谢，镜像问题自己可以解决了，上述问题确实是你说的那样，非常感谢 @weilinqwe
