### ISSUE TITLE
kube-dns 容器不断重启

### ISSUE THREAD

**Issue by 88265920** [gjmzj/kubeasz#159]
`# kubectl get po -n kube-system`
NAME                                                     READY     STATUS    RESTARTS   AGE
calico-kube-controllers-77d5968764-5nwhg                 1/1       Running   0          23h
calico-node-2q6z9                                        2/2       Running   0          23h
...
kube-dns-566c7c77d8-x99hr                                3/3       Running   411        3d

kubernetes集群启动和部署都正常，kube-dns不断重启，容器内部nslookup正常，主机配置/etc/resolv.conf后，有时候能够nslookup kubernetes，有时候不能，nslookup其他svc失败

`# kubectl logs -n kube-system kube-dns-566c7c77d8-x99hr -c sidecar`

W0412 08:03:23.696930       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:55840->127.0.0.1:53: i/o timeout
W0412 08:03:36.413330       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:43778->127.0.0.1:53: i/o timeout

`# kubectl logs -n kube-system kube-dns-566c7c77d8-x99hr -c dnsmasq`
I0412 08:01:54.365383       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local./127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0412 08:01:54.365861       1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local./127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0412 08:01:56.012306       1 nanny.go:116] dnsmasq[20]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0412 08:01:56.012360       1 nanny.go:116] dnsmasq[20]: using nameserver 127.0.0.1#10053 for 
I0412 08:01:56.012418       1 nanny.go:116] dnsmasq[20]: reading /etc/resolv.conf
I0412 08:01:56.012433       1 nanny.go:116] dnsmasq[20]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0412 08:01:56.012487       1 nanny.go:116] dnsmasq[20]: read /etc/hosts - 7 addresses

I0412 08:03:49.494796       1 nanny.go:116] dnsmasq[20]: Maximum number of concurrent DNS queries reached (max: 150)

**Comment by gjmzj** [comment]
从dnsmasq的日志来看是你的dns查询并发已经达到上限；是不是你在对集群进行压测，你可以通过：
`kubectl scale -n kube-system deployment kube-dns --replicas=3` 
通过副本数提升并发能力试试看；
当然你也可以使用coredns代替kube-dns来做域名解析，记得也合理设置coredns的副本数；
据介绍coredns稳定性更好些

**Comment by 88265920** [comment]
这是刚搭起来的集群，还没跑什么服务，不明白为什么会达到上限

**Comment by gjmzj** [comment]
简介下你的环境：
部署模式：allinone，单主多节点，多主多节点？
硬件资源情况：cpu /内存
操作系统：
其他可能有用的信息

**Comment by 88265920** [comment]
ubuntu16.04 multi-master 7个节点 8cores 8g

**Comment by 88265920** [comment]
其中6个节点是vmware虚拟的

**Comment by 88265920** [comment]
增加3个副本，观察了一天，没有再重启，感谢作者 ：）
