### ISSUE TITLE
heapster配置问题

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#16]
@jmgao1983 @gjmzj 
二位大神,您们好. 
我搭建好k8s系统后, 增加了kubedns和dashboard, 但最后在配置heapster碰到问题了.在 dashboard里看不到各个node的CPU或图形情况, 另外heapster相关的网站也打不开,如下所示:

root@k8-d-1:/etc/ansible/kubeasz/kubeasz# ls -al manifests/heapster/
drwxr-xr-x 2 root root 4096 12月 11 10:20 .
drwxr-xr-x 6 root root 4096 12月 11 10:20 ..
-rw-r--r-- 1 root root 2238 12月 11 10:20 grafana.yaml
-rw-r--r-- 1 root root 1450 12月 11 10:20 heapster.yaml
-rw-r--r-- 1 root root 4471 12月 11 10:20 influxdb.yaml

kubectl create -f manifests/heapster/
deployment "monitoring-grafana" created
service "monitoring-grafana" created
serviceaccount "heapster" created
clusterrolebinding "heapster" created
deployment "heapster" created
service "heapster" created
deployment "monitoring-influxdb" created
service "monitoring-influxdb" created
configmap "influxdb-config" created

kubectl get pod -n kube-system | grep heapster
heapster-6956dd7956-gfpmw                  1/1       Running   0          1m

kubectl get svc -n kube-system|grep heapster
heapster               ClusterIP   10.68.48.43     <none>        80/TCP                        1m

root@k8-d-2:~# kubectl get pods -n kube-system | grep -E 'heapster|monitoring'
heapster-6956dd7956-gfpmw                  1/1       Running   0          47m
monitoring-grafana-747cd57c4b-kk9jr        1/1       Running   0          47m
monitoring-influxdb-6755bd4788-6454k       1/1       Running   0          47m
root@k8-d-2:~# kubectl get deployments -n kube-system | grep -E 'heapster|monitoring'
heapster                  1         1         1            1           49m
monitoring-grafana        1         1         1            1           49m
monitoring-influxdb       1         1         1            1           49m

root@k8-d-2:~# kubectl cluster-info
Kubernetes master is running at https://10.10.2.17:8443
Heapster is running at https://10.10.2.17:8443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://10.10.2.17:8443/api/v1/namespaces/kube-system/services/kube-dns/proxy
kubernetes-dashboard is running at https://10.10.2.17:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
monitoring-grafana is running at https://10.10.2.17:8443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
monitoring-influxdb is running at https://10.10.2.17:8443/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

请问一下我的问题出在哪里呢? 我该怎么样才能访问heapster的相关资源呢?(Heapster + InfluxDB + Grafana) , 再次感谢!

**Comment by evenye** [comment]
当我打开Heapster is running at https://10.233.2.17:8443/api/v1/namespaces/kube-system/services/heapster/proxy时,提示404 page not found.
当我打开monitoring-grafana is running at https://10.233.2.17:8443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy时,提示:
{{alert.title}}
Docs
Support Plans
Community
Grafana vv4.4.3 (commit: unknown-dev)

**Comment by gjmzj** [comment]
@evenye 重启下你的dashboard POD，然后再访问dashboard应该可以看到资源使用率了，可以参考操作：
先删除
`kubectl scale deploy kubernetes-dashboard --replicas=0 -n kube-system `
然后
`kubectl scale deploy kubernetes-dashboard --replicas=1 -n kube-system `

**Comment by evenye** [comment]
@gjmzj 谢谢! 重启dashboard的POD后,可以看到资源使用率了,但还是无法访问heapster的相关资源, (Heapster + InfluxDB + Grafana), 
打开的网页显示异常,
当我打开monitoring-grafana is running at https://10.233.2.17:8443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy时,提示:
{{alert.title}}
Docs
Support Plans
Community
Grafana vv4.4.3 (commit: unknown-dev)

谢谢您! 期待着heapster的大作再次更新!!!!!

**Comment by gjmzj** [comment]
已更新 heapster文档

**Comment by evenye** [comment]
@gjmzj 太强大了, 大神请收下我对你的敬意!!!

按您的教程配置很顺利地运行起来了, 最后能否请您再指点一下几个问题呢? 
1. 我想修改grafana image的路径/etc/grafanal到本地的一个NFS mount目录上(这样我就可以手动修改配置或启用ldap),请问我如何map这个目录到node上呢? 如果不能更新的话如何修改grafana.yaml来实现全新配置呢? 同样对于influxdb,我也想将它的/data数据库改到本地的NFS 目录上来,(这个数据库占用的空间非常大)
2. 因为同时间influxdb和grafana 容器只在某一个node节点中运行,如果这个节点被重启,容器迁移到另外一台node,则原来存储下来的数据是否就会丢失呢?    因为有这个担心,所以我在尝试学习怎么将它们的数据或配置目录改到node节点上的folder上来. (所有的node节点都使用NFS mount到某个共享目录. )

再次感谢您的指点!

**Comment by gjmzj** [comment]
不要吹捧，这样没法接话了...
大概明白你的意思，可以尝试下这个笨办法，你在每个node都挂载nfs到相同目录比如：/data/nfs/，然后你在pod里面都挂载这个hostdir，这样不管pod活在哪个node，都可以持久化到nfs中

**Comment by tianjiangtao999** [comment]
@gjmzj 大神，我也有上述问题，咋解决的，没有看明白啊？我只是在访问heapster的时候有问题，另外，在做hpa的时候有问题
