### ISSUE TITLE
readonly无法登录dashboard

### ISSUE THREAD

**Issue by fjibj** [gjmzj/kubeasz#160]
用readonly用户登录之后，无论用什么token都无法登录进去，请问是什么问题？

**Comment by gjmzj** [comment]
readonly用户是针对 dashboard 1.6.x 版本设计，当时它没有自带的认证机制；
如果是dashboard 1.8.x版本可以首先用证书或者admin用户密码通过api-server方式认证，然后再dashboard自带的认证界面去创建类似readonly的Service Account 和 ClusterRoleBinding，然后获取 它Bearer Token登陆dashboard

**Comment by fjibj** [comment]
那就是说每个user需要有一个与它权限对应的service account，并且用该service account的token才能登录dashboard？ user与service account是一一对应的吗？

**Comment by gjmzj** [comment]
在 k8s 里面 user 和 serviceaccount 可以看作是同样对待的，它们的权限是由绑定的role决定的；
我的意思是，在dashboard 1.8.x里面你不用去区分user了，用统一的admin用户（或证书）登陆，区分权限你可以给他们不同的serviceaccount对应的secret（token）

**Comment by fjibj** [comment]
理解了，谢谢
