### ISSUE TITLE
centos7 运行ansible-playbook失败

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#166]
ansible 报错如下：

k8s版本为1.10.0

TASK [flannel : 运行 flannel网络] *******************************************************************************************************************************************************************************
fatal: [192.168.2.128]: FAILED! => {"changed": true, "cmd": "/root/local/bin/kubectl create -f /root/local/kube-system/flannel/ && sleep 5", "delta": "0:00:00.244558", "end": "2018-04-18 13:37:05.352820", "msg": "non-zero return code", "rc": 1, "start": "2018-04-18 13:37:05.108262", "stderr": "Error from server (BadRequest): error when creating \"/root/local/kube-system/flannel/kube-flannel.yaml\": DaemonSet in version \"v1beta1\" cannot be handled as a DaemonSet: v1beta1.DaemonSet: Spec: v1beta1.DaemonSetSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: Value: ReadString: expects \" or n, but found 6, error found in #10 byte of ...|,\"value\":6443}],\"ima|..., bigger context ...|.128\"},{\"name\":\"KUBERNETES_SERVICE_PORT\",\"value\":6443}],\"image\":\"jmgao1983/flannel:v0.10.0-amd64\",\"n|...", "stderr_lines": ["Error from server (BadRequest): error when creating \"/root/local/kube-system/flannel/kube-flannel.yaml\": DaemonSet in version \"v1beta1\" cannot be handled as a DaemonSet: v1beta1.DaemonSet: Spec: v1beta1.DaemonSetSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: Value: ReadString: expects \" or n, but found 6, error found in #10 byte of ...|,\"value\":6443}],\"ima|..., bigger context ...|.128\"},{\"name\":\"KUBERNETES_SERVICE_PORT\",\"value\":6443}],\"image\":\"jmgao1983/flannel:v0.10.0-amd64\",\"n|..."], "stdout": "clusterrole.rbac.authorization.k8s.io \"flannel\" created\nclusterrolebinding.rbac.authorization.k8s.io \"flannel\" created\nserviceaccount \"flannel\" created\nconfigmap \"kube-flannel-cfg\" created", "stdout_lines": ["clusterrole.rbac.authorization.k8s.io \"flannel\" created", "clusterrolebinding.rbac.authorization.k8s.io \"flannel\" created", "serviceaccount \"flannel\" created", "configmap \"kube-flannel-cfg\" created"]}

NO MORE HOSTS LEFT ******************************************************************************************************************************************************************************************
	to retry, use: --limit @/etc/ansible/90.setup.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
192.168.2.128              : ok=97   changed=78   unreachable=0    failed=1

![error](https://user-images.githubusercontent.com/17851645/38913648-70ea1df6-430e-11e8-934d-9cdbd2417bab.png)

**Comment by gjmzj** [comment]
sorry, 昨天更新的kube-flannel.yaml.j2配置没有测试到位，新增的 env变量忘记打双引号了，已经commit解决，请拉取最新代码
