### ISSUE TITLE
请教阿里云怎么访问dashboard？

### ISSUE THREAD

**Issue by ancon** [gjmzj/kubeasz#167]
因为master写的阿里云的内网地址，外网是访问不到的，所以请教怎么访问呢？
如图：
命令：kubectl cluster-info
输出：
Kubernetes master is running at https://172.18.184.218:6443
kubernetes-dashboard is running at https://172.18.184.218:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
monitoring-grafana is running at https://172.18.184.218:6443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy

**Comment by gjmzj** [comment]
我想两种方式：
1. 在创建dashboard service的时候使用 type=LoadBalancer ，阿里云应该会自动为你创建负载均衡，然后再绑一个EIP即可。
2. 在创建dashboard service的时候使用 type=NodePort , 然后在NAT网关那边做个destination NAT转换即可。

**Comment by ancon** [comment]
@gjmzj 我是默认安装的，也就是type=NodePort，之前一直不能访问，今天可以访问了。把内网ip地址换成阿里云的公网地址即可。
多谢！

**Comment by liaoyizhe** [comment]
你好，请问你是怎么把内网ip转成公网的呢？

**Comment by RuifMaxx** [comment]
https://zhuanlan.zhihu.com/p/562697522?这篇文章的访问dashboard一节有说明
