### ISSUE TITLE
安装dashboard插件后无法访问

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#168]
k8s v1.10.0 按照教程安装dashboard后访问异常
![cat4](https://user-images.githubusercontent.com/17851645/38987955-27032d12-4404-11e8-927b-3232f75cab29.png)

![cat5](https://user-images.githubusercontent.com/17851645/38989310-fa0fa236-4408-11e8-8e07-538702e14f6d.png)

**Comment by gjmzj** [comment]
看着是RBAC问题，你是用什么方式通过apiserver认证，然后又是用什么方式登陆dashboard自带的登陆界面

**Comment by Hello-Linux** [comment]
@gjmzj  我是通过这个步骤进行的 k8s token从/etc/ansible/hosts拷贝出来的
![cat6](https://user-images.githubusercontent.com/17851645/39027145-1cced9d4-4483-11e8-981c-5cb48df62ddc.png)

**Comment by gjmzj** [comment]
你token搞错了，hosts那里的token是kubelet bootstrap机制使用的，两回事；
按照文档来获取
``` bash
# 创建Service Account 和 ClusterRoleBinding
$ kubectl create -f /etc/ansible/manifests/dashboard/admin-user-sa-rbac.yaml
# 获取 Bearer Token，找到输出中 ‘token:’ 开头那一行
$ kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')
```

**Comment by Hello-Linux** [comment]
好的 我试试
