### ISSUE TITLE
kubernetes安装后发布deployment,但是在pod里无法访问外网

### ISSUE THREAD

**Issue by yummykang** [gjmzj/kubeasz#169]
按照文档安装了kubernetes,single-master，系统是centos，容器是基于alpine的，手动启动的容器可以ping通www.baidu.com，但是通过deployment启动的pod就无法ping通，网络是flannel

**Comment by gjmzj** [comment]
首先你确定集群每个节点是否正常，有否可能某个节点有问题，当pod调度到某个节点不能ping出去；
你能不能描述下复现的步骤，比如手动的pod，你的yaml文件是什么，deployment又是怎么配置的。

**Comment by yummykang** [comment]
问题已经解决了，需要安装kube-dns或者coredns插件，dns解析方面我没有安装
