### ISSUE TITLE
添加node kubelet 无法正常启动 谢谢！

### ISSUE THREAD

**Issue by DavenAaron** [gjmzj/kubeasz#17]
Dec 12 14:29:06 vm4 systemd: Starting Kubernetes Kubelet...
Dec 12 14:29:06 vm4 iptables: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Dec 12 14:29:06 vm4 systemd: kubelet.service: control process exited, code=exited status=4
Dec 12 14:29:06 vm4 systemd: Failed to start Kubernetes Kubelet.
Dec 12 14:29:06 vm4 systemd: Unit kubelet.service entered failed state.
Dec 12 14:29:06 vm4 systemd: kubelet.service failed.
Dec 12 14:29:11 vm4 systemd: kubelet.service holdoff time over, scheduling restart.
Dec 12 14:29:11 vm4 systemd: Starting Kubernetes Kubelet...
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.753694   27943 feature_gate.go:156] feature gates: map[]
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.753790   27943 controller.go:114] kubelet config controller: starting controller
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.753799   27943 controller.go:118] kubelet config controller: validating combination of defaults and flags
Dec 12 14:29:11 vm4 systemd: Started Kubernetes systemd probe.
Dec 12 14:29:11 vm4 systemd: Starting Kubernetes systemd probe.
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.760317   27943 mount_linux.go:205] Detected OS with systemd
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.760346   27943 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.760375   27943 client.go:95] Start docker client with request timeout=2m0s
Dec 12 14:29:11 vm4 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Dec 12 14:29:11 vm4 kubelet: I1212 14:29:11.768808   27943 feature_gate.go:156] feature gates: map[]
Dec 12 14:29:11 vm4 kubelet: error: failed to run Kubelet: unknown cloud provider "''"
Dec 12 14:29:12 vm4 systemd: Failed to start Kubernetes Kubelet.
Dec 12 14:29:12 vm4 systemd: Unit kubelet.service entered failed state.
Dec 12 14:29:12 vm4 systemd: kubelet.service failed.

**Comment by gjmzj** [comment]
/etc/systemd/system/kubelet.service　文件中找到 `--cloud-provider` 这一行，删除这行保存后，`systemctl daemon-reload && systemctl restart kubelet`
