### ISSUE TITLE
大神，问一个关于挂载ceph的问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#170]
我用statefulsets模式创建zookeeper集群，挂载ceph存储，一直出现报错。报错内容如下
Unable to mount volumes for pod "zk-0_zookeeper(3162a20b-46da-11e8-8a6e-525453c0ef0a)": timeout expired waiting for volumes to attach/mount for pod "zookeeper"/"zk-0". list of unattached/unmounted volumes=[datadir]

我的yaml文件是参照https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/tutorials/stateful-application/zookeeper.yaml 这个的，实在找不到问题了，求大神指点，谢谢

**Comment by xiaozhiqi2000** [comment]
使用statefulset storageclass遇到这个问题？

rbac.go:116] RBAC DENY: user "system:node:docker-k8s-04" groups ["system:nodes" "system:authenticated"] cannot "get" resource "persistentvolumeclaims" named "data-ceph-storageclass-nginx-0" in namespace "default"

 **kubectl get pvc**
NAME                             STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS        AGE
data-ceph-storageclass-nginx-0   Pending                                       ceph-storageclass   1m

**kubectl describe pvc data-ceph-storageclass-nginx-0**
Name:          data-ceph-storageclass-nginx-0
Namespace:     default
StorageClass:  ceph-storageclass
Status:        Pending
Volume:        
Labels:        app=ceph-storageclass-nginx
Annotations:   volume.beta.kubernetes.io/storage-class=ceph-storageclass
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  14s (x11 over 2m)  persistentvolume-controller  Failed to provision volume with StorageClass "ceph-storageclass": failed to get admin secret from ["default"/"ceph-secret"]: failed to get secret from ["default"/"ceph-secret"]

不知道你有没遇到这个问题？

**Comment by gjmzj** [comment]
@sunchangming ceph环境没有实践过，群里问问看有没有能回答你
@xiaozhiqi2000 这个像是rbac没有设置

**Comment by sunchangming** [comment]
已经解决，谢谢大神

**Comment by motecshine** [comment]
@sunchangming  怎么解决的

**Comment by Tinet-AaronAn** [comment]
应该是没有设置好secret

**Comment by Auggie321** [comment]
我也遇到可这个问题，最终的解决办法：  
1.检查secrets是否存在问题，没问题；  
2.检查sc是否存在问题，没问题；  
3.检查ceph -s是否存在问题，没问题；  
4.kubectl describe pods  xxx   ,发现落点在xx.xx.xx.xx服务器上，  
然后ssh xxx.xx.xx.xx节点systemctl restart docker kubelet  ;   
5.master节点 kubelet delete -f xxx.yaml ; kubelet apply -f xxx.yaml，然后就成功恢复了；
