### ISSUE TITLE
大神，calico问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#171]
今天不知道操作什么了，导致master节点的calico网络插件挂掉了，在node节点上执行calicoctl node status显示master是 Active Socket: Connectio，不知道怎么解决了，master节点执行命令之后显示
Calico process is running.

IPv4 BGP status
No IPv4 peers found.

IPv6 BGP status
No IPv6 peers found
求教怎么弄

**Comment by sunchangming** [comment]
kubernetes版本是1.9.3

**Comment by gjmzj** [comment]
` kubectl logs -n kube-system calico-node-xxxxx calico-node` 查看下master上的calico-node日志

**Comment by sunchangming** [comment]
没有这个pod了已经

**Comment by sunchangming** [comment]
弄好了，谢谢大神

**Comment by yexq** [comment]
相同的情况 我是1.11的 但pod是running状态的
