### ISSUE TITLE
关于dashboard配置basic认证的问题

### ISSUE THREAD

**Issue by yeaheo** [gjmzj/kubeasz#173]
## 关于dashboard配置basic认证的问题
- 大神，按照您写的[文档](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/dashboard.md)部署dashboard-1.8.3后，在apiserver中也加了`--basic-auth-file=/etc/kubernetes/ssl/basic-auth.csv`参数，apiserver可以正常启动，dashboard也可以通过<http://master-ip:8080/ui>访问，但是不知道为什么dashboard的登录页面没有<用户名/密码>相关选项，只有默认的两种登录方式
- 还请帮忙解决一下，谢谢！

**Comment by gjmzj** [comment]
建议使用api-server方式登陆：
- <用户名/密码>方式其实只是用来通过apiserver的认证
- dashboard 1.8.3其实自带了安全登陆认证，使用kubeconfig或者token方式
