### ISSUE TITLE
Scaled up and down导致influxdb识别出多个pod

### ISSUE THREAD

**Issue by wyfaq** [gjmzj/kubeasz#175]
RT，最近在修改deployment的配置，需要频繁replace yml文件，监控中发现，会出现多个pod，包好已经消失的pod。
我知道这个是influxdb的过滤问题，没有想到好的解决方案，楼主有什么建议吗？

**Comment by gjmzj** [comment]
这个确实存在，好处是可以回头查看各个阶段的pod实际副本的监控数据，在实际环境中很有用；坏处就是历史pod会很多，选择起来也麻烦；
如果一定要删除一些pod，可以考虑直接去调用相关influxdb restful api进行操作，没有实践过。

**Comment by wyfaq** [comment]
3q。其实我还是期望能有想pmm client purge数据那样的功能。pod下线 数据自动purge。
