### ISSUE TITLE
使用kubectl proxy 访问 dashboard 1.8.3

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#178]
dashboard从1.6.3升级到1.8.3之后，用proxy的方式访问不了，页面一直在加载，用NodePort方式可以访问
dashboard日志如下
![image](https://user-images.githubusercontent.com/18720841/39559769-52b4c804-4ecb-11e8-8b92-fcb8fe1c29d2.png)

**Comment by gjmzj** [comment]
dashboard 1.6.3和1.8.x 使用rbac不一样的，建议按照文档清除 1.6.x版本后再安装 1.8.x
https://github.com/gjmzj/kubeasz/blob/master/docs/guide/dashboard.md

**Comment by sunchangming** [comment]
我就是按照文档清楚之后又安装的，今天又重新安装了一遍，还是这个问题

**Comment by gjmzj** [comment]
抱歉，确实没测试过用proxy方式去访问，对于dashboard的访问，还是建议使用apiserver方式，临时访问用NodePort方式

**Comment by gjmzj** [comment]
实测使用 `kubectl proxy --address='0.0.0.0'  --accept-hosts='^*$'` 然后如下访问dashboard是可以的：
http://x.x.x.x:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
