### ISSUE TITLE
我这边安装的时候一直停留在

### ISSUE THREAD

**Issue by a33151** [gjmzj/kubeasz#180]
TASK [kube-node : 轮询等待node达到Ready状态] ************************************************************************************************************************************
FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
changed: [172.18.173.239]

FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (7 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (7 retries left).
...
已经等待到最后了还是不成功

我去到172.18.173.238服务器上 kubctl get node

[root@k8s-node1 ~]# kubectl get node         
NAME             STATUS                     ROLES     AGE       VERSION
172.18.173.238   Ready,SchedulingDisabled   <none>    36m       v1.9.1
172.18.173.239   Ready,SchedulingDisabled   <none>    36m       v1.9.1
是ready状态的。请问是什么原因引起的？

**Comment by a33151** [comment]
望能得到一个答复 万分感谢!

**Comment by khadgarmage** [comment]
@a33151 啥原因呢

**Comment by DreamIsCollapsing** [comment]
有原因了吗。。。我这边也是，node节点卡住了，看日志说是未认证
