### ISSUE TITLE
我这边使用了 Horizontal Pod Autoscaling 进行压测 ，整个集群突然就挂了。没找到原因 ，想请教一下

### ISSUE THREAD

**Issue by a33151** [gjmzj/kubeasz#184]
大神，首先感谢使用你的脚步已经搭建成功了k8s，我这边一步一步执行对应的测试
其中我测试 hpa的时候
突然容器就挂掉，kubelet 有很多的错误日志。我尝试去谷歌百度 ，未能找到答案
我贴部分上来
May 08 17:02:28 k8s-node1 kubelet[18657]: E0508 17:02:28.893978   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.0.100:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:28 k8s-node1 kubelet[18657]: E0508 17:02:28.898625   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.100:8443/api/v1/pods?fieldSelector=spec.nodeName%3D192.168.0.10&limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:28 k8s-node1 kubelet[18657]: E0508 17:02:28.901522   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.0.100:8443/api/v1/nodes?fieldSelector=metadata.name%3D192.168.0.10&limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:30 k8s-node1 kubelet[18657]: E0508 17:02:30.090485   18657 event.go:209] Unable to write event: 'Post https://192.168.0.100:8443/api/v1/namespaces/default/events: dial tcp 192.168.0.100:8443: i/o timeout' (may retry after sleeping)
May 08 17:02:30 k8s-node1 kubelet[18657]: E0508 17:02:30.564425   18657 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node "192.168.0.10" not found
May 08 17:02:37 k8s-node1 kubelet[18657]: E0508 17:02:37.913430   18657 kubelet_node_status.go:106] Unable to register node "192.168.0.10" with API server: Post https://192.168.0.100:8443/api/v1/nodes: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:40 k8s-node1 kubelet[18657]: E0508 17:02:40.565224   18657 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node "192.168.0.10" not found
May 08 17:02:44 k8s-node1 kubelet[18657]: I0508 17:02:44.913862   18657 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
May 08 17:02:44 k8s-node1 kubelet[18657]: I0508 17:02:44.917679   18657 kubelet_node_status.go:431] Recording NodeHasSufficientDisk event message for node 192.168.0.10
May 08 17:02:44 k8s-node1 kubelet[18657]: I0508 17:02:44.917775   18657 kubelet_node_status.go:431] Recording NodeHasSufficientMemory event message for node 192.168.0.10
May 08 17:02:44 k8s-node1 kubelet[18657]: I0508 17:02:44.917796   18657 kubelet_node_status.go:431] Recording NodeHasNoDiskPressure event message for node 192.168.0.10
May 08 17:02:44 k8s-node1 kubelet[18657]: I0508 17:02:44.917841   18657 kubelet_node_status.go:82] Attempting to register node 192.168.0.10
May 08 17:02:50 k8s-node1 kubelet[18657]: E0508 17:02:50.565655   18657 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node "192.168.0.10" not found
May 08 17:02:59 k8s-node1 kubelet[18657]: E0508 17:02:59.895851   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.0.100:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:59 k8s-node1 kubelet[18657]: E0508 17:02:59.899659   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.100:8443/api/v1/pods?fieldSelector=spec.nodeName%3D192.168.0.10&limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:02:59 k8s-node1 kubelet[18657]: E0508 17:02:59.902504   18657 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.0.100:8443/api/v1/nodes?fieldSelector=metadata.name%3D192.168.0.10&limit=500&resourceVersion=0: dial tcp 192.168.0.100:8443: i/o timeout
May 08 17:03:00 k8s-node1 kubelet[18657]: E0508 17:03:00.584185   18657 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node "192.168.0.10" not found

root@k8s-node2:/opt/kube/bin# kubectl get node
NAME           STATUS                        ROLES                      AGE          VERSION
192.168.0.10   NotReady,SchedulingDisabled   <none>    7h        v1.9.3
192.168.0.11   Ready,SchedulingDisabled        <none>    7h        v1.9.3
192.168.0.12   Ready                                        <none>    7h        v1.9.3
192.168.0.13   Ready                                        <none>    7h        v1.9.3

node的状态变成notready 。 请教下 能看出是什么问题吗。

**Comment by gjmzj** [comment]
从这个日志看好像是访问master的VIP网络失败了，可以查下LB节点状态，确保中间没有防火墙或者其他限制。
如果是192.168.0.10变成了notReady，那首先就去这台机器上查看kubelet的日志，看看什么错误

**Comment by a33151** [comment]
感谢提醒。
我在node上找到了原因，发现node1 的flannel 网络down掉了。
但是我没能去找到这个的错误日志
我在node1上执行（就是flannel网络挂掉的那台机器）
root@k8s-node1:/opt/kube/kube-system/flannel# kubectl logs  kube-flannel-ds-rk55k -n kube-system
Unable to connect to the server: dial tcp 192.168.0.100:8443: i/o timeout

kube-system   kube-flannel-ds-cv27x                   1/1       Running    1          23h
kube-system   kube-flannel-ds-np8ct                   1/1       Running    1          23h
kube-system   kube-flannel-ds-rk55k                   1/1       NodeLost   13         23h
kube-system   kube-flannel-ds-rljj5                   1/1       Running    1          23h
我在/run/上找到flannel的文件 
有个log的文件夹 ，但是打开的都是乱码。
reocar@k8s-node1:/run/log/journal/26e59041033067c00c71849d5ad6b1e6$ ls
system@f3f73f8f12e44cd781ac845caf7a293f-0000000000037215-00056bb6b3db678d.journal
system@f3f73f8f12e44cd781ac845caf7a293f-000000000003971b-00056bb7594cf3e3.journal
system@f3f73f8f12e44cd781ac845caf7a293f-000000000003bc21-00056bb7fe5cf672.journal
system@f3f73f8f12e44cd781ac845caf7a293f-000000000003e127-00056bb8a35bd571.journal
system@f3f73f8f12e44cd781ac845caf7a293f-000000000004062d-00056bb948f23205.journal
system@f3f73f8f12e44cd781ac845caf7a293f-0000000000042b33-00056bb9ed0aabc8.journal
system@f3f73f8f12e44cd781ac845caf7a293f-0000000000045039-00056bba92813c9b.journal
system@f3f73f8f12e44cd781ac845caf7a293f-000000000004753f-00056bbb3769fc86.journal
system.journal

系统上又没能找到flannel的日志 能告知一下日志存放的地方吗？
