### ISSUE TITLE
关于harbor安装问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#185]
大神，我按照你的文档安装的harbor，kubernetes是1.9.3的，安装harbor的时候报错如下
fatal: [172.20.7.11]: FAILED! => {"changed": true, "cmd": "cd /root/local/harbor && export PATH=/root/local/bin:$PATH && ./install.sh", "delta": "0:01:11.577543", "end": "2018-05-09 17:06:21.770163", "msg": "non-zero return code", "rc": 1, "start": "2018-05-09 17:05:10.192620", "stderr": "Traceback (most recent call last):\n  File \"./prepare\", line 206, in <module>\n    email_insecure = rcp.get(\"configuration\", \"email_insecure\")\n  File \"/usr/lib/python2.7/ConfigParser.py\", line 340, in get\n    raise NoOptionError(option, section)\nConfigParser.NoOptionError: No option u'email_insecure' in section: u'configuration'", "stderr_lines": ["Traceback (most recent call last):", "  File \"./prepare\", line 206, in <module>", "    email_insecure = rcp.get(\"configuration\", \"email_insecure\")", "  File \"/usr/lib/python2.7/ConfigParser.py\", line 340, in get", "    raise NoOptionError(option, section)", "ConfigParser.NoOptionError: No option u'email_insecure' in section: u'configuration'"], "stdout": "\n\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 0]: checking installation environment ...\u001b(B\u001b[m\n\n\u001b(B\u001b[0;4m\u001b[1m\u001b[38;5;25mNote:\u001b(B\u001b[m \u001b[38;5;25mdocker version: 17.12.0\u001b(B\u001b[m\n\n\u001b(B\u001b[0;4m\u001b[1m\u001b[38;5;25mNote:\u001b(B\u001b[m \u001b[38;5;25mdocker-compose version: 1.18.0\u001b(B\u001b[m\n\n\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 1]: loading Harbor images ...\u001b(B\u001b[m\nLoaded image: vmware/notary-server-photon:v0.5.1-v1.4.0\nLoaded image: vmware/notary-signer-photon:v0.5.1-v1.4.0\nLoaded image: vmware/harbor-db:v1.4.0\nLoaded image: vmware/clair-photon:v2.0.1-v1.4.0\nLoaded image: vmware/postgresql-photon:v1.4.0\nLoaded image: vmware/harbor-adminserver:v1.4.0\nLoaded image: vmware/harbor-ui:v1.4.0\nLoaded image: vmware/harbor-log:v1.4.0\nLoaded image: vmware/harbor-jobservice:v1.4.0\nLoaded image: vmware/nginx-photon:v1.4.0\nLoaded image: vmware/registry-photon:v2.6.2-v1.4.0\nLoaded image: vmware/photon:1.0\nLoaded image: vmware/mariadb-photon:v1.4.0\nLoaded image: vmware/harbor-db-migrator:1.4\n\n\n\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 2]: preparing environment ...\u001b(B\u001b[m", "stdout_lines": ["", "\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 0]: checking installation environment ...\u001b(B\u001b[m", "", "\u001b(B\u001b[0;4m\u001b[1m\u001b[38;5;25mNote:\u001b(B\u001b[m \u001b[38;5;25mdocker version: 17.12.0\u001b(B\u001b[m", "", "\u001b(B\u001b[0;4m\u001b[1m\u001b[38;5;25mNote:\u001b(B\u001b[m \u001b[38;5;25mdocker-compose version: 1.18.0\u001b(B\u001b[m", "", "\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 1]: loading Harbor images ...\u001b(B\u001b[m", "Loaded image: vmware/notary-server-photon:v0.5.1-v1.4.0", "Loaded image: vmware/notary-signer-photon:v0.5.1-v1.4.0", "Loaded image: vmware/harbor-db:v1.4.0", "Loaded image: vmware/clair-photon:v2.0.1-v1.4.0", "Loaded image: vmware/postgresql-photon:v1.4.0", "Loaded image: vmware/harbor-adminserver:v1.4.0", "Loaded image: vmware/harbor-ui:v1.4.0", "Loaded image: vmware/harbor-log:v1.4.0", "Loaded image: vmware/harbor-jobservice:v1.4.0", "Loaded image: vmware/nginx-photon:v1.4.0", "Loaded image: vmware/registry-photon:v2.6.2-v1.4.0", "Loaded image: vmware/photon:1.0", "Loaded image: vmware/mariadb-photon:v1.4.0", "Loaded image: vmware/harbor-db-migrator:1.4", "", "", "\u001b(B\u001b[0;4m\u001b[1m\u001b[37m[Step 2]: preparing environment ...\u001b(B\u001b[m"]}
不知道是什么问题，请大神指教一下

**Comment by gjmzj** [comment]
错误日志可以用markdown语法里面的bash code形式展示，要不然可读性好差>.<
1.从错误日志看已经进行到最后一步 `./install.sh`这里了，如果失败了，你可以手动去执行下，再仔细看看错误日志，上面的初看像是少了某个python模块

**Comment by sunchangming** [comment]
手动执行报错信息如下
ConfigParser.NoOptionError: No option u'email_insecure' in section: u'configuration'

**Comment by TonyBian** [comment]
项目支持的默认harbor版本是1.2.2，看你用的是1.4.0最新版，两个版本的配置文件不一样，需要用1.4.0的配置文件去做jijia模板，替换掉kubeasz/roles/harbor/templates/harbor.cfg.j2

**Comment by sunchangming** [comment]
@TonyBian 谢谢，已经解决，就是配置文件的问题

**Comment by sunchangming** [comment]
@gjmzj 谢谢大神，已经解决，是配置文件的问题
