### ISSUE TITLE
为什么 kube-master host 里面还要安装 kubelet

### ISSUE THREAD

**Issue by steinliber** [gjmzj/kubeasz#187]
如果模式不是 allinone 的话，用其他模式为什么 master 里面还要装 kubelet 和 kube-proxy, 应该是可以不用的吧

**Comment by gjmzj** [comment]
1. 确实master节点不是必须安装kubelet和kube-proxy（参见本项目的1.8分支就没有装）；
2. 1.9和master分支都有装这两个组件，是为了安装网络组件（flannel和calico是以daemonset运行的）；
3. 当然分支1.9和master也可以不装这两个组件，缺点是在master节点不能使用proxy访问集群服务，也不能使用kubectl cluster-info里面的链接访问集群服务（只能用其他方式访问集群服务如ingress,loadbalance等）

**Comment by steinliber** [comment]
ok,了解了
