### ISSUE TITLE
kubectl get componentstatus Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by flameyucong** [gjmzj/kubeasz#189]
journalctl -u kube-controller-manager
-- Logs begin at Sun 2018-05-13 06:33:16 CST, end at Mon 2018-05-14 17:10:09 CST. --
May 14 16:53:06 K8S-node5 kube-controller-manager[21243]: E0514 16:53:06.200684   21243 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/ap
May 14 16:53:08 K8S-node5 kube-controller-manager[21243]: E0514 16:53:08.712677   21243 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/ap
May 14 16:53:11 K8S-node5 kube-controller-manager[21243]: E0514 16:53:11.696504   21243 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/ap
May 14 16:53:13 K8S-node5 kube-controller-manager[21243]: E0514 16:53:13.751092   21243 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/ap

**Comment by gjmzj** [comment]
`Unable to connect to the server` 应该首先查找kube-apiserver的服务状态，从贴的日志看是kube-controller-manager服务有报错，集群其他组件也得看看是否正常

**Comment by flameyucong** [comment]
TASK [kube-master : 以轮询的方式等待master服务启动完成] *********************************************************************************************************************************************************************
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (5 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (4 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (3 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (2 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (1 retries left).
fatal: [10.2.10.33]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/root/local/bin/kubectl", "get", "node"], "delta": "0:00:00.198479", "end": "2018-05-15 11:02:49.221149", "msg": "non-zero return code", "rc": 1, "start": "2018-05-15 11:02:49.022670", "stderr": "Unable to connect to the server: EOF", "stderr_lines": ["Unable to connect to the server: EOF"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ********************************************************************************************************************************************************************************************
        to retry, use: --limit @/etc/ansible/04.kube-master.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************
10.2.10.33                 : ok=9    changed=2    unreachable=0    failed=1
10.2.10.34                 : ok=9    changed=2    unreachable=0    failed=0
