### ISSUE TITLE
kubectl logs报错 error: You must be logged in to the server

### ISSUE THREAD

**Issue by njqaaa** [gjmzj/kubeasz#19]
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log tomcat-69574bf8d5-47nm7))

容器正常启动，但是使用kubectl logs命令 就出现上述错误，请教下这个怎么解决。

[root@k8s-master-1 ssl]# kubectl get nodes -o wide
NAME           STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
k8s-master-1   Ready     master    54m       v1.8.5    <none>        CentOS Linux 7 (Core)   4.11.8-1.el7.elrepo.x86_64   docker://17.11.0-ce
k8s-master-2   Ready     master    54m       v1.8.5    <none>        CentOS Linux 7 (Core)   4.11.8-1.el7.elrepo.x86_64   docker://17.11.0-ce
k8s-master-3   Ready     master    54m       v1.8.5    <none>        CentOS Linux 7 (Core)   4.11.8-1.el7.elrepo.x86_64   docker://17.11.0-ce
k8s-node-1     Ready     node      54m       v1.8.5    <none>        CentOS Linux 7 (Core)   4.11.8-1.el7.elrepo.x86_64   docker://17.11.0-ce
k8s-node-2     Ready     node      54m       v1.8.5    <none>        CentOS Linux 7 (Core)   4.11.8-1.el7.elrepo.x86_64   docker://17.11.0-ce

[root@k8s-master-1 ssl]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE
default       hello-nginx-5d47cdc4b7-5p5jg                1/1       Running   0          7m
default       tomcat-69574bf8d5-2s96b                     1/1       Running   0          41m
default       tomcat-69574bf8d5-47nm7                     1/1       Running   0          41m
default       tomcat-69574bf8d5-8kd8m                     1/1       Running   0          41m
default       tomcat-69574bf8d5-lp4gh                     1/1       Running   0          41m
kube-system   calico-policy-controller-8487549c89-kpjkg   1/1       Running   0          50m
kube-system   kube-apiserver-k8s-master-1                 1/1       Running   0          51m
kube-system   kube-apiserver-k8s-master-2                 1/1       Running   0          51m
kube-system   kube-apiserver-k8s-master-3                 1/1       Running   0          51m
kube-system   kube-controller-manager-k8s-master-1        1/1       Running   0          52m
kube-system   kube-controller-manager-k8s-master-2        1/1       Running   1          52m
kube-system   kube-controller-manager-k8s-master-3        1/1       Running   0          52m
kube-system   kube-dns-5595fc64b9-sbqn4                   3/3       Running   0          50m
kube-system   kube-proxy-9fj5w                            1/1       Running   0          50m
kube-system   kube-proxy-ctbnd                            1/1       Running   0          50m
kube-system   kube-scheduler-k8s-master-1                 1/1       Running   0          52m
kube-system   kube-scheduler-k8s-master-2                 1/1       Running   0          52m
kube-system   kube-scheduler-k8s-master-3                 1/1       Running   0          52m
kube-system   kubernetes-dashboard-574bdff9f-hjbbp        1/1       Running   0          50m

**Comment by gjmzj** [comment]
你能贴一下是使用具体哪个命令报这个错吗？
还有，你使用kubectl logs 查看所有pod都会报错吗？

**Comment by njqaaa** [comment]
对的 就是查看所有的pod都报错  不管namespaces是kube-system还是defalult
其他的命令都是正常的
如果kubectl logs  不存在的pod，会正常报不存在该pod

**Comment by njqaaa** [comment]
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2017-12-14T07:37:47Z"},"level":"Metadata","timestamp":"2017-12-14T07:37:47Z","auditID":"1395dae1-fa9a-4b4b-81cd-56d3ed9ec318","stage":"RequestReceived","requestURI":"/api/v1/namespaces/default/pods/tomcat-69574bf8d5-68t72","verb":"get","user":{"username":"admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.28.50.60"],"objectRef":{"resource":"pods","namespace":"default","name":"tomcat-69574bf8d5-68t72","apiVersion":"v1"}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2017-12-14T07:37:47Z"},"level":"Metadata","timestamp":"2017-12-14T07:37:47Z","auditID":"1395dae1-fa9a-4b4b-81cd-56d3ed9ec318","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/default/pods/tomcat-69574bf8d5-68t72","verb":"get","user":{"username":"admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.28.50.60"],"objectRef":{"resource":"pods","namespace":"default","name":"tomcat-69574bf8d5-68t72","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2017-12-14T07:37:47Z"},"level":"Metadata","timestamp":"2017-12-14T07:37:47Z","auditID":"804bb359-7bb6-4736-8106-1f63486e6e8d","stage":"RequestReceived","requestURI":"/api/v1/namespaces/default/pods/tomcat-69574bf8d5-68t72/log","verb":"get","user":{"username":"admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.28.50.60"],"objectRef":{"resource":"pods","namespace":"default","name":"tomcat-69574bf8d5-68t72","apiVersion":"v1","subresource":"log"}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2017-12-14T07:37:47Z"},"level":"Metadata","timestamp":"2017-12-14T07:37:47Z","auditID":"804bb359-7bb6-4736-8106-1f63486e6e8d","stage":"ResponseStarted","requestURI":"/api/v1/namespaces/default/pods/tomcat-69574bf8d5-68t72/log","verb":"get","user":{"username":"admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.28.50.60"],"objectRef":{"resource":"pods","namespace":"default","name":"tomcat-69574bf8d5-68t72","apiVersion":"v1","subresource":"log"},"responseStatus":{"metadata":{},"status":"Failure","message":"the server has asked for the client to provide credentials ( pods/log tomcat-69574bf8d5-68t72)","reason":"Unauthorized","details":{"name":"tomcat-69574bf8d5-68t72","kind":"pods/log"},"code":401}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2017-12-14T07:37:47Z"},"level":"Metadata","timestamp":"2017-12-14T07:37:47Z","auditID":"804bb359-7bb6-4736-8106-1f63486e6e8d","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/default/pods/tomcat-69574bf8d5-68t72/log","verb":"get","user":{"username":"admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.28.50.60"],"objectRef":{"resource":"pods","namespace":"default","name":"tomcat-69574bf8d5-68t72","apiVersion":"v1","subresource":"log"},"responseStatus":{"metadata":{},"status":"Failure","message":"the server has asked for the client to provide credentials ( pods/log tomcat-69574bf8d5-68t72)","reason":"Unauthorized","details":{"name":"tomcat-69574bf8d5-68t72","kind":"pods/log"},"code":401}}
```
``` bash
{
    "CN": "kubernetes",
    "hosts": [
      "127.0.0.1",
      "k8s-master-1",
      "k8s-master-2",
      "k8s-master-3",
      "10.96.0.1",
      "10.28.50.60",
      "10.28.50.61",
      "10.28.50.62",
      "k8s-apiserver.test.xx.com",
      "kubernetes",
      "kubernetes.default",
      "kubernetes.default.svc",
      "kubernetes.default.svc.cluster",
      "kubernetes.default.svc.cluster.local"
    ],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "C": "CN",
            "ST": "ShangHai",
            "L": "ShangHai",
            "O": "system:masters",
            "OU": "System"
        }
    ]
}
```

``` bash
# admin set-cluster
kubectl config set-cluster kubernetes \
    --certificate-authority=${SSL_PATH}/ca.pem \
    --embed-certs=true \
    --server=${KUBE_APISERVER} \
    --kubeconfig=../admin.conf

# admin set-credentials
kubectl config set-credentials kubernetes-admin \
    --client-certificate=${SSL_PATH}/admin.pem \
    --client-key=${SSL_PATH}/admin-key.pem \
    --embed-certs=true \
    --kubeconfig=../admin.conf

# admin set-context
kubectl config set-context kubernetes-admin@kubernetes \
    --cluster=kubernetes \
    --user=kubernetes-admin \
    --kubeconfig=../admin.conf

# admin set default context
kubectl config use-context kubernetes-admin@kubernetes \
    --kubeconfig=../admin.conf
```
请问下，使用admin用户为什么会验证失败？
还是说需要创建rbac？

**Comment by gjmzj** [comment]
你的集群是kubeadm创建的吧，kubectl使用 admin的证书按照你的配置应该不需要手动配置RBAC了，因为预定义的 ClusterRoleBinding 已经将 Group system:masters 与 ClusterRole cluster-admin 绑定，所以具体原因不好判断
