### ISSUE TITLE
请问下现在支持 1.9 版本的 metrics-server 吗

### ISSUE THREAD

**Issue by steinliber** [gjmzj/kubeasz#191]
我看 ansible 脚本中还没有支持这个，之后 heapster 会被废弃吧

**Comment by gjmzj** [comment]
是的，后续项目会跟进metrics-server内容
DEPRECATED: Heapster is deprecated. Consider using metrics-server and a third party metrics pipeline to gather Prometheus-format metrics instead. See the deprecation timeline for more information on support. We will not be adding any new features to Heapster.
