### ISSUE TITLE
upgrade_k8s 22.upgrade 升级Pod会出现failed to open log file

### ISSUE THREAD

**Issue by yfm10** [gjmzj/kubeasz#193]
ansible-playbook -t upgrade_k8s 22.upgrade.yml
虽然业务不中断，但是会出现日志文件打不开的情况
`
failed to open log file "/var/log/pods/1af03e47-58f3-11e8-83c5-0894ef55127a/data-platform-api/0.log": open /var/log/pods/1af03e47-58f3-11e8-83c5-0894ef55127a/data-platform-api/0.log: no such file or directory
`

**Comment by gjmzj** [comment]
感谢反馈，
我也发现了该问题，暂时没有很好的办法，我是通过rollingupdate，或者通过增加业务pod副本，然后把老的pod删除重建，可以暂时解决该问题。
等待更好的办法出现
