### ISSUE TITLE
安装dashboard插件后无法访问

### ISSUE THREAD

**Issue by flameyucong** [gjmzj/kubeasz#197]
namespaces is forbidden: User "kubelet-bootstrap" cannot list namespaces at the cluster scope

**Comment by gjmzj** [comment]
是按照kubeasz项目里面的dashboard文档安装的吗?
是dashboard 1.8.3 吗？
是用什么方式登陆dashboard界面的，证书？用户名+密码？NodePort？
是用什么方式登陆dashboard自带的登陆界面的，kubeconfig？token?
