### ISSUE TITLE
关于harbor问题

### ISSUE THREAD

**Issue by pengyan2018** [gjmzj/kubeasz#20]
@gjmzj 你好，在“集群规划和基础参数设定”中需要配置Harbor：
#私有仓库 harbor服务器 (域名或者IP) 【可选】
#需要把 harbor服务器证书复制到roles/harbor/files/harbor-ca.crt
HARBOR_SERVER="harbor.mydomain.com"

这个是要求harbor要提前安装好并生成CA证书，是吧？但是在执行kubeasz的自动化安装脚本前，理论上dodker是没有安装的。这个时候harbor能正常安装吗？请指教

**Comment by gjmzj** [comment]
这个harbor配置是预留的，目前还没有把harbor部署的脚本集成进去

**Comment by pengyan2018** [comment]
@gjmzj 好的，那我这边就先执行kubeasz自动化安装，然后再手动安harbor
