### ISSUE TITLE
关于虚机allinone 部署后的复制问题

### ISSUE THREAD

**Issue by dotnet123** [gjmzj/kubeasz#201]
大神你好，我在虚拟机A装了一台allinone，搭建一套开发环境，我想通过copy A出来一套B然后交给测试，copy后ip变了，请问有办法在B上面改下ip，能够直接运行吗？有没有好的方式。

**Comment by dotnet123** [comment]
因为有其它持久化的东西，我们认为copy最简单，谢谢。

**Comment by dotnet123** [comment]
再问个小问题，如果真的无法通过改ip把B运行起来，我可以重新装一遍吧，装的时候可不可以跳过第三部03-安装docker服务，因为里面已经有docker了，里面有我手动运行的一些服务，不想清空掉，谢谢。

**Comment by gjmzj** [comment]
1.可以通过虚机copy来分享测试环境；
2.如果ip有变更，可以在/etc/ansible/hosts修改ip后，重新运行'ansible-playbook 90.setup.yml'即可，切记不要运行99.clean.yml；
3.03.docker.yml不跳过也没关系，它只会重启下你的docker服务而已

**Comment by dotnet123** [comment]
多谢了，等待你的文档。

**Comment by gjmzj** [comment]
文档在这里 https://github.com/gjmzj/kubeasz/blob/master/docs/op/change_ip_allinone.md
注意，操作前请拉取最新项目代码

**Comment by dotnet123** [comment]
多谢，多谢！

**Comment by dotnet123** [comment]
多谢大神, 我已经操作成功.
