### ISSUE TITLE
pod 无法获取到 pod ip问题

### ISSUE THREAD

**Issue by steinliber** [gjmzj/kubeasz#203]
使用的 cni 插件是 calico, 会出现 pod 时不时重启的情况, 看描述是说 Pod sandbox changed, it will be killed and re-created， 看 kubelet 的日志报以下错误

> failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod

**Comment by gjmzj** [comment]
是新装的集群吗? 最近没升级calico版本，试试如下命令：
`kubectl logs -n kube-system calicoxxxxxxxx calico-node`
`kubectl describe pod -n kube-system calicoxxxxxxxxxxxx`

**Comment by steinliber** [comment]
不是最新的，是1.9 版本的, 以下是 description 的输出 

>   Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "var-run-calico"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "etcd-certs"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "cni-net-dir"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "cni-bin-dir"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "lib-modules"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "calico-node-token-8wf2l"
  Normal   Pulled                 44m (x2 over 46m)  kubelet, 192.168.0.37  Container image "calico/cni:v2.0.3" already present on machine
  Normal   Started                44m (x2 over 46m)  kubelet, 192.168.0.37  Started container
  Normal   Created                44m (x2 over 46m)  kubelet, 192.168.0.37  Created container
  Normal   Started                44m (x2 over 46m)  kubelet, 192.168.0.37  Started container
  Normal   Killing                40m (x2 over 44m)  kubelet, 192.168.0.37  Killing container with id docker://calico-node:Need to kill Pod
  Normal   Created                40m (x3 over 46m)  kubelet, 192.168.0.37  Created container
  Normal   Pulled                 40m (x3 over 46m)  kubelet, 192.168.0.37  Container image "calico/node:v3.0.4" already present on machine
  Normal   Killing                40m (x2 over 44m)  kubelet, 192.168.0.37  Killing container with id docker://install-cni:Need to kill Pod
  Normal   SandboxChanged         19m (x8 over 44m)  kubelet, 192.168.0.37  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff                6m (x48 over 16m)  kubelet, 192.168.0.37  Back-off restarting failed container
  Warning  BackOff                1m (x85 over 19m)  kubelet, 192.168.0.37  Back-off restarting failed container

下面是日志

> bird: bird: device1: State changed to updirect1: Connected to table master
bird: direct1: State changed to feedbird:
direct1: State changed to upbird:
Mesh_192_168_0_34: Starting
bird: Mesh_192_168_0_34: State changed to start
bird: Mesh_192_168_0_31: Starting
bird: Mesh_192_168_0_31: State changed to start
bird: Graceful restart started
bird: Started
bird: device1: State changed to up
bird: direct1: State changed to up
2018-05-25 08:35:35.248 [INFO][75] config.go 82: Skipping confd config file.
2018-05-25 08:35:35.248 [INFO][75] confd.go 27: Starting calico-confd
2018-05-25 08:35:35.255 [INFO][75] watchersyncer.go 83: Start called
2018-05-25 08:35:35.255 [INFO][75] watchersyncer.go 89: Sending status update Status=wait-for-ready
2018-05-25 08:35:35.255 [INFO][75] watchersyncer.go 103: Starting main event processing loop
2018-05-25 08:35:35.255 [INFO][75] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/ipam/v2/host/k8s-master"
2018-05-25 08:35:35.256 [INFO][75] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-05-25 08:35:35.256 [INFO][75] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/bgpconfigurations"
2018-05-25 08:35:35.257 [INFO][75] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/nodes"
2018-05-25 08:35:35.257 [INFO][75] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/bgppeers"
2018-05-25 08:35:35.258 [INFO][75] watchercache.go 218: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/bgpconfigurations"
2018-05-25 08:35:35.258 [INFO][75] watchercache.go 218: Sending synced update ListRoot="/calico/ipam/v2/host/k8s-master"
2018-05-25 08:35:35.258 [INFO][75] watchersyncer.go 166: Received InSync event from one of the watcher caches
2018-05-25 08:35:35.258 [INFO][75] watchersyncer.go 89: Sending status update Status=resync
2018-05-25 08:35:35.258 [INFO][75] watchersyncer.go 166: Received InSync event from one of the watcher caches
2018-05-25 08:35:35.259 [INFO][75] watchercache.go 218: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-05-25 08:35:35.259 [INFO][75] watchersyncer.go 166: Received InSync event from one of the watcher caches
2018-05-25 08:35:35.260 [INFO][75] watchercache.go 218: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/bgppeers"
2018-05-25 08:35:35.260 [INFO][75] watchersyncer.go 166: Received InSync event from one of the watcher caches
2018-05-25 08:35:35.260 [INFO][75] watchercache.go 218: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/nodes"
2018-05-25 08:35:35.260 [INFO][75] watchersyncer.go 166: Received InSync event from one of the watcher caches
2018-05-25 08:35:35.261 [INFO][75] watchersyncer.go 178: All watchers have sync'd data - sending data and final sync
2018-05-25 08:35:35.261 [INFO][75] watchersyncer.go 89: Sending status update Status=in-sync
bird: Mesh_192_168_0_34: Connected to table master
bird: Mesh_192_168_0_34: State changed to wait
bird: Mesh_192_168_0_31: Connected to table master
bird: Mesh_192_168_0_31: State changed to wait
bird: Graceful restart done
bird: Mesh_192_168_0_34: State changed to feed
bird: Mesh_192_168_0_31: State changed to feed
bird: Mesh_192_168_0_34: State changed to up
bird: Mesh_192_168_0_31: State changed to up
bird: Mesh_192_168_0_34: State changed to start
bird: Mesh_192_168_0_34: State changed to feed
bird: Mesh_192_168_0_34: State changed to up
bird: Mesh_192_168_0_34: State changed to start
bird: Mesh_192_168_0_31: State changed to start
bird: Mesh_192_168_0_31: State changed to feed
bird: Mesh_192_168_0_31: State changed to up
bird: Mesh_192_168_0_31: State changed to start
bird: Mesh_192_168_0_31: State changed to feed
bird: Mesh_192_168_0_31: State changed to up
bird: Mesh_192_168_0_34: State changed to stop
bird: Mesh_192_168_0_34: State changed to down
bird: Mesh_192_168_0_34: Starting
bird: Mesh_192_168_0_34: State changed to start

我看 kubelet 的日志如下 

> May 25 16:43:52 k8s-master kubelet[24513]: I0525 16:43:52.512761   24513 kuberuntime_manager.go:768] Back-off 5m0s restarting failed container=calico-node pod=calico-node-s649b_kube-system(ef799262-5fef-11e8-a670-00163e02f1da)
May 25 16:43:52 k8s-master kubelet[24513]: E0525 16:43:52.512789   24513 pod_workers.go:186] Error syncing pod ef799262-5fef-11e8-a670-00163e02f1da ("calico-node-s649b_kube-system(ef799262-5fef-11e8-a670-00163e02f1da)"), skipping: failed to "StartContainer" for "calico-node" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=calico-node pod=calico-node-s649b_kube-system(ef799262-5fef-11e8-a670-00163e02f1da)"
May 25 16:43:54 k8s-master kubelet[24513]: E0525 16:43:54.259378   24513 fs.go:418] Stat fs failed. Error: no such file or directory
May 25 16:44:07 k8s-master kubelet[24513]: E0525 16:44:07.080967   24513 fs.go:418] Stat fs failed. Error: no such file or directory
May 25 16:44:07 k8s-master kubelet[24513]: I0525 16:44:07.512483   24513 kuberuntime_manager.go:514] Container {Name:calico-node Image:calico/node:v3.0.4 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:ETCD_ENDPOINTS Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_endpoints,Optional:nil,},SecretKeyRef:nil,}} {Name:CALICO_NETWORKING_BACKEND Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:calico_backend,Optional:nil,},SecretKeyRef:nil,}} {Name:CLUSTER_TYPE Value:k8s,bgp ValueFrom:nil} {Name:CALICO_DISABLE_FILE_LOGGING Value:true ValueFrom:nil} {Name:CALICO_K8S_NODE_REF Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:FELIX_DEFAULTENDPOINTTOHOSTACTION Value:ACCEPT ValueFrom:nil} {Name:CALICO_IPV4POOL_CIDR Value:172.20.0.0/16 ValueFrom:nil} {Name:CALICO_IPV4POOL_IPIP Value:always ValueFrom:nil} {Name:FELIX_IPV6SUPPORT Value:false ValueFrom:nil} {Name:FELIX_LOGSEVERITYSCREEN Value:warning ValueFrom:nil} {Name:FELIX_IPINIPMTU Value:1440 ValueFrom:nil} {Name:ETCD_CA_CERT_FILE Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_ca,Optional:nil,},SecretKeyRef:nil,}} {Name:ETCD_KEY_FILE Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_key,Optional:nil,},SecretKeyRef:nil,}} {Name:ETCD_CERT_FILE Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_cert,Optional:nil,},SecretKeyRef:nil,}} {Name:IP Value:autodetect ValueFrom:nil} {
May 25 16:44:07 k8s-master kubelet[24513]: Name:IP_AUTODETECTION_METHOD Value:can-reach=223.5.5.5 ValueFrom:nil} {Name:FELIX_HEALTHENABLED Value:true ValueFrom:nil}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:250 scale:-3} d:{Dec:<nil>} s:250m Format:DecimalSI}]} VolumeMounts:[{Name:lib-modules ReadOnly:true MountPath:/lib/modules SubPath: MountPropagation:<nil>} {Name:var-run-calico ReadOnly:false MountPath:/var/run/calico SubPath: MountPropagation:<nil>} {Name:etcd-certs ReadOnly:false MountPath:/calico-secrets SubPath: MountPropagation:<nil>} {Name:calico-node-token-8wf2l ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/liveness,Port:9099,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:10,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:6,} ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/readiness,Port:9099,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 25 16:44:07 k8s-master kubelet[24513]: I0525 16:44:07.512667   24513 kuberuntime_manager.go:758] checking backoff for container "calico-node" in pod "calico-node-s649b_kube-system(ef799262-5fef-11e8-a670-00163e02f1da)"
May 25 16:44:08 k8s-master kubelet[24513]: I0525 16:44:08.331345   24513 kubelet.go:1896] SyncLoop (PLEG): "calico-node-s649b_kube-system(ef799262-5fef-11e8-a670-00163e02f1da)", event: &pleg.PodLifecycleEvent{ID:"ef799262-5fef-11e8-a670-00163e02f1da", Type:"ContainerStarted", Data:"9b7506af7c1379e2e2db2923e6fed8864013cccfc231f5b5d6567de79efe67e8"}

**Comment by steinliber** [comment]
是因为防火墙的配置问题吗

**Comment by gjmzj** [comment]
你配置了什么防火墙吗？
不过日志里面就是提示“ Pod sandbox ”改变了，其他看不出什么，那你看看问题的机器上sandbox运行`docker ps -a `看看 pause容器怎么改变了

**Comment by steinliber** [comment]
现在是全部都开了，还是不行
![image](https://user-images.githubusercontent.com/13215800/40538903-a768097a-6045-11e8-8522-f3c72aa26ac6.png)

**Comment by steinliber** [comment]
是创建 pause 容器有问题吗

**Comment by gjmzj** [comment]
前面日志是提示 pause容器问题，要不升级下k8s集群试试：
https://github.com/gjmzj/kubeasz/blob/master/docs/op/upgrade.md
