### ISSUE TITLE
harbor部署脚本有些问题，麻烦帮助看一下.

### ISSUE THREAD

**Issue by jiayizhang** [gjmzj/kubeasz#207]
环境是这样的：
[deploy]
172.17.65.119

# etcd集群请提供如下NODE_NAME、NODE_IP变量,注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
172.17.108.11 NODE_NAME=etcd1 NODE_IP="172.17.108.11"
172.17.108.12 NODE_NAME=etcd2 NODE_IP="172.17.108.12"
172.17.108.18 NODE_NAME=etcd3 NODE_IP="172.17.108.18"

[kube-master]
172.17.108.11 NODE_IP="172.17.108.11"
172.17.108.12 NODE_IP="172.17.108.12"

# 负载均衡至少两个节点，安装 haproxy+keepalived
[lb]
172.17.108.11 LB_IF="ens160" LB_ROLE=backup  # 注意根据实际使用网卡设置 LB_IF变量
172.17.108.12 LB_IF="ens160" LB_ROLE=master
[lb:vars]
master1="172.17.108.11:6443"    # 根据实际master节点数量设置
master2="172.17.108.12:6443"    # 需同步设置roles/lb/templates/haproxy.cfg.j2 
#master3="172.17.108.1x:6443"
ROUTER_ID=57                    # 取值在0-255之间，区分多个instance的VRRP组播，同网段不能重复

[kube-node]
172.17.108.21 NODE_IP="172.17.108.21"
172.17.108.22 NODE_IP="172.17.108.22"
172.17.108.23 NODE_IP="172.17.108.23"

# 如果启用harbor，请配置后面harbor相关参数
[harbor]
172.17.108.18 NODE_IP="172.17.108.18"

所以前面部署都正常，但在harbor部署时出现如下问题。
如下图：

![image](https://user-images.githubusercontent.com/15817767/40603903-e77d9006-628f-11e8-98aa-54a323bbded1.png)

注释这一段后：
![image](https://user-images.githubusercontent.com/15817767/40604036-4f7a9f28-6290-11e8-9e25-149e60aefb3a.png)

仍然会出现：
![image](https://user-images.githubusercontent.com/15817767/40604048-5b61fe80-6290-11e8-899d-5fb2cd1b0202.png)

**Comment by jiayizhang** [comment]
把这三步，屏蔽掉（改成手动安装就可以成功）。
![image](https://user-images.githubusercontent.com/15817767/40604580-1e1e03b4-6292-11e8-9fe0-aa365779cfa6.png)

**Comment by gjmzj** [comment]
确实需要调整下，感谢提醒

**Comment by tanshion** [comment]
应该是解压harbor离线安装包有问题，11脚本部署harbor时，把roles/harbor/tasks/main.yml 的解压harbor 离线安装包步骤注释掉，然后手动解压harbor离线包到目标服务器的/opt 目录，再运行11脚本可以部署成功。

**Comment by tanshion** [comment]
![1650356f-4f87-4c25-b364-f8a4d891a6e9](https://user-images.githubusercontent.com/9196558/40870403-1f56c734-6661-11e8-87f4-945b55855343.png)
