### ISSUE TITLE
机器重启后   异常

### ISSUE THREAD

**Issue by DavenAaron** [gjmzj/kubeasz#21]
----- dashboard ----

2017/12/14 06:25:31 Starting overwatch
2017/12/14 06:25:31 Using in-cluster config to connect to apiserver
2017/12/14 06:25:31 Using service account token for csrf signing
2017/12/14 06:25:31 No request provided. Skipping authorization
2017/12/14 06:25:34 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.68.0.1:443/version: dial tcp 10.68.0.1:443: getsockopt: connection timed out
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

**Comment by DavenAaron** [comment]
dns 启动也是异常的

**Comment by gjmzj** [comment]
机器重启应该没有影响，有没有确认过重启前工作正常？或者尝试删除dashboard后按照[这个文档](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/dashboard.md)重新安装下，确定工作正常后再尝试重启机器验证下
