### ISSUE TITLE
以单节点安装时轮询等待kubelet启动任务错误

### ISSUE THREAD

**Issue by raighneweng** [gjmzj/kubeasz#210]
```
TASK [kube-node : 轮询等待kubelet启动] ********************************************************************************************************************************************
FAILED - RETRYING: 轮询等待kubelet启动 (8 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (7 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (6 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (5 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).
fatal: [192.168.122.1]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.005522", "end": "2018-05-29 05:51:44.792189", "rc": 0, "start": "2018-05-29 05:51:44.786667", "stderr": "", "stderr_lines": [], "stdout": "   Active: activating (auto-restart) (Result: exit-code) since Tue 2018-05-29 05:51:42 EDT; 2s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) since Tue 2018-05-29 05:51:42 EDT; 2s ago"]}

PLAY RECAP ******************************************************************************************************************************************************************
192.168.122.1              : ok=23   changed=8    unreachable=0    failed=1
```

HOST配置如下
```
[deploy]
192.168.122.1

[etcd]
192.168.122.1 NODE_NAME=etcd1 NODE_IP="192.168.122.1"

[kube-master]
192.168.122.1 NODE_IP="192.168.122.1"

[kube-node]
192.168.122.1 NODE_IP="192.168.122.1"

[all:vars]
DEPLOY_MODE=allinone

#集群 MASTER IP
MASTER_IP="192.168.122.1"

#集群 APISERVER
KUBE_APISERVER="https://192.168.122.1:6443"

#TLS Bootstrapping 使用的 Token，使用 head -c 16 /dev/urandom | od -An -t x | tr -d ' ' 生成
BOOTSTRAP_TOKEN="d18f94b5fa585c7123f56803d925d2e7"

# 集群网络插件，目前支持calico和flannel
CLUSTER_NETWORK="flannel"

# 部分calico相关配置，更全配置可以去roles/calico/templates/calico.yaml.j2自定义
# 设置 CALICO_IPV4POOL_IPIP=“off”,可以提高网络性能，条件限制详见 05.安装calico网络组件.md
CALICO_IPV4POOL_IPIP="always"
# 设置 calico-node使用的host IP，bgp邻居通过该地址建立，可手动指定端口"interface=eth0"或使用如下自动发现
IP_AUTODETECTION_METHOD="can-reach=223.5.5.5"

# 部分flannel配置，详见roles/flannel/templates/kube-flannel.yaml.j2
FLANNEL_BACKEND="vxlan"

# 服务网段 (Service CIDR），部署前路由不可达，部署后集群内使用 IP:Port 可达
SERVICE_CIDR="10.68.0.0/16"

# POD 网段 (Cluster CIDR），部署前路由不可达，**部署后**路由可达
CLUSTER_CIDR="172.20.0.0/16"

# 服务端口范围 (NodePort Range)
NODE_PORT_RANGE="20000-40000"

# kubernetes 服务 IP (预分配，一般是 SERVICE_CIDR 中第一个IP)
CLUSTER_KUBERNETES_SVC_IP="10.68.0.1"

# 集群 DNS 服务 IP (从 SERVICE_CIDR 中预分配)
CLUSTER_DNS_SVC_IP="10.68.0.2"

# 集群 DNS 域名
CLUSTER_DNS_DOMAIN="cluster.local."

# etcd 集群间通信的IP和端口, **根据实际 etcd 集群成员设置**
ETCD_NODES="etcd1=https://192.168.122.1:2380"

# etcd 集群服务地址列表, **根据实际 etcd 集群成员设置**
ETCD_ENDPOINTS="https://192.168.122.1:2379"

# 集群basic auth 使用的用户名和密码
BASIC_AUTH_USER="admin"
BASIC_AUTH_PASS="test1234"

# ---------附加参数--------------------
#默认二进制文件目录
bin_dir="/opt/kube/bin"

#证书目录
ca_dir="/etc/kubernetes/ssl"

#部署目录，即 ansible 工作目录
base_dir="/etc/ansible"
```

**Comment by gjmzj** [comment]
等待kubelet启动错误，那就要查看错误日志：
1.systemctl status kubelet 确认状态
1.journalctl -u kubelet 查看错误日志

**Comment by omaidb** [comment]
[root m1 /etc/kubeasz/clusters/default] WORK 0
# systemctl status kubelet.service -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2025-03-31 05:02:46 EDT; 4s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 68485 ExecStart=/opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///run/containerd/containerd.sock --hostname-override=k8s-192-168-171-133 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --root-dir=/var/lib/kubelet --v=2 (code=exited, status=1/FAILURE)
  Process: 68483 ExecStartPre=/bin/mount -o remount,rw /sys/fs/cgroup (code=exited, status=0/SUCCESS)
 Main PID: 68485 (code=exited, status=1/FAILURE)

Mar 31 05:02:46 k8s-192-168-171-133 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 31 05:02:46 k8s-192-168-171-133 systemd[1]: Unit kubelet.service entered failed state.
Mar 31 05:02:46 k8s-192-168-171-133 systemd[1]: kubelet.service failed.

**Comment by omaidb** [comment]
--
-- The start-up result is done.
Mar 31 05:03:22 k8s-192-168-171-133 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 31 05:03:22 k8s-192-168-171-133 systemd[1]: Unit kubelet.service entered failed state.
Mar 31 05:03:22 k8s-192-168-171-133 systemd[1]: kubelet.service failed.
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: Stopped Kubernetes Kubelet.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished shutting down.
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: Starting Kubernetes Kubelet...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has begun starting up.
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: Started Kubernetes Kubelet.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Mar 31 05:03:28 k8s-192-168-171-133 kubelet[68720]: E0331 05:03:28.171634   68720 run.go:72] "command failed" err="failed to run Kubelet: validate service connection: validate CRI v1 runtime API for endpoint \
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: Unit kubelet.service entered failed state.
Mar 31 05:03:28 k8s-192-168-171-133 systemd[1]: kubelet.service failed.
