### ISSUE TITLE
centos7 下没有出现calico网卡

### ISSUE THREAD

**Issue by pengyan2018** [gjmzj/kubeasz#22]
@gjmzj  我在centos7下执行AllINOne的ansible-playbook 90.setup.yml，经验证除了calico外，其余都OK，很完美 :)

calico的现象是，ip addr后没有看到calico网卡，不知道是怎么回事？
其中**calicoctl node status**的输出是：
Calico process is running.

IPv4 BGP status
No IPv4 peers found.

IPv6 BGP status
No IPv6 peers found.

**calicoctl get ipPool -o yaml**的输出是：
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 172.17.0.0/16
  spec:
    nat-outgoing: true

kubectl get pod -n kube-system -o wide的输出看似也是正确的
NAME                                       READY     STATUS    RESTARTS   AGE       IP            NODE
calico-kube-controllers-699495f8d4-hshk4   1/1       Running   0          10m       10.65.93.34   10.65.93.34

**Comment by gjmzj** [comment]
那是因为你还没有创建其他POD，创建了就有了
