### ISSUE TITLE
kubectl logs 失败

### ISSUE THREAD

**Issue by onlonely** [gjmzj/kubeasz#221]
以下是kubeconfig和apiserver配置
`[root@www .kube]# cat config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVZmQyRGtxOE9pNHF2ZHVRaHZibmN2SnRYeldJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURZd05UQTFORFl3TUZvWERUSXpNRFl3TkRBMU5EWXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBN1BuYW11QXhlRW1uRlBGSVNsNXUKWXhOZTZYZEx3L0VFdHcyZUR5SFd2cWcxNHBuZHlESUY5V0pRZDlvRnZVWGpLSnAydzFNeXh6KzhjMUlVbTFYWQpMbGtUZWFjNFI2SElMZlpLL3F0SW5uOTdpTWhtV2VYYmQzUEluQ2lKMG9FelNGT3g4cHU0YjJJMVNFaldsRTF5CmhNQXdtSGQzMDVvRnBIMXBvdlVPa1lhL25MU3VlWUZYakI1QlZWNzhTVEI4RzJTSzh2cGhMNFFER0xBZStueXAKakh2a2U0V2dNV3JyaVRHQk1razVIRkhXL0l4TUR0QUMrdjhXTFRUTGVrdFowVUVEbUF4b0RuZFZPVnlxUldJeApkR2JadWU5anpzRFRKZ3hYRUNNcFhzTkRMUEZwMFFVQmM2Z1hUS0NGODFSeG5XYSsrU24rZjJDUFJ1ang2RmFOCmh3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVRkwreXpKU0VERDVZcWs2MXpaOTBtVlp2N213d0h3WURWUjBqQkJnd0ZvQVVGTCt5ekpTRQpERDVZcWs2MXpaOTBtVlp2N213d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFOUXcrdVQ2OUFPS042SXF3SmJrClhGMitlQnRmcThLejZ0OEw3aFFNRUk4Q1J1WnBINFhueDhSMEQ3ZW04SDFIempwa3pOaEJCSDIvSHZ2NUVhMnAKUXk1Y05WZ20wS0l3aTVBYVJROCtFeEVwVlVMZGRlZzVvcWtQQmhDT1dDU2lObzdrVkJEU1pVajB6S3VuQWZSTAp3V2p0V1ppRTF3T0JNdmU3TzhFVTNxSmw4M2tpdC9MVU5PVmRqdWJKVDVQSFBXSFQzUTEvWVNQQUVSTjkrR3NkClZaZlY4WjBZTWZQbkpqUnFBdks5RVJQZ0ZDK1ZqdUVzYkRUdVl0Z0hSSWx1UVZVUlhIWCtNUWdsbmJtaU9OMG4KRElPYjk3RUNPNmk5aTdwYlVucDdIbENXa3gyeHRWdTFlMG1yQ3VteCtmL2hYWERHSWd1VjBwQU9vUmtHSTJCMgpBUUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://11.11.11.200:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    as-user-extra: {}
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzVENDQXNXZ0F3SUJBZ0lVWTFhcGtQNGtteHZkMC80VUt6ZUE4WW1oWmJjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURZd05UQTFORFl3TUZvWERUSTRNRFl3TWpBMU5EWXdNRm93YXpFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RnpBVgpCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RGpBTUJnTlZCQU1UCkJXRmtiV2x1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3Mjh0TXFaVHMvZmwKTisvclU5Q1M3Vy9TN0E5RjQ0bVZrU0RucUhRL1FWdzE1S0NRL1FlR1U1K1hVUWpyUUhiajRmdkhyREpmcExDWApNUlNNREl5eDBYUS9EdC8zZjJydkRjMnJzTXhJVWUyMGJ5ak9pd3lPRXh5M3ZRVUx3UE8yUDZVTHlSYWFCSU5nCjk1c3E2OUtSNG9tMW4wZldua042OGp5TzRxUUVjNTlOZHdLOE1aQ0NOcHUrN2VpcTNVQmRBL2Rzb0pWaUFDZWsKdXJHRkVqdXFQeUpVYmR3NUNKRDdjZk10SnlPZ2dsWmN2OVN2bTBmbC9ocGhCTVd1eVlxZ3dPaGNocWgvRU40QwpqRXV1ZTdvN0VQVWNQZ0RhdWlHZE5CR3ljM04zckNkY1ZwazhUbm4xQnF5SU9od0RrbWZtWFgweUltRGJ0V2NQCkc1RXBFS2swRFFJREFRQUJvMzh3ZlRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZCcDdKMG5JcEFhUAp2WFdGWnB3dnQ4OERHcmtXTUI4R0ExVWRJd1FZTUJhQUZCUy9zc3lVaEF3K1dLcE90YzJmZEpsV2IrNXNNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFDNHcvOFRZTlRKUlVkbkdWMFhxWkdHZFRFVjQ3UGtoeWNuS2lsZGFVbmgKZlFyZDV0eTNJcUlrYkdlMkF5c2dWcld2VU9hby81cHdSZTVxQ2dpOVNLRk1wc2VhaHlhY0tZSlp6MC9iNUw3RwpBNXJYQlJmMjRNV3dOVld2NWNJc00xSjl1R3V4U1Q0SEhCS3gyZ0FXTmQ2c2FQRUorQ2txUnB1dFZ6dkVra0Q4Cm1pQWdpRnJZK3VIaExhb0lpZUs3MVl6ZGlKUU54TFpBcEJZT09ORlJXOUk3Mjh3MnVmQWZCMUpuZmxCOXloMVgKVllmN0d4cUc2Yi9keDdGSDlKc1dlVUdLLzl6a0RQQmg1ZWdUZkoyN3BhbVkzV1BpQ3RSYitRMGtlMGt6bVZzeQpPTXhLZDZ0dUx5UENMU0dKV1R1eGlCK3pFdHcwdzJmZW8ydWFtenNBRndZNwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdzI4dE1xWlRzL2ZsTisvclU5Q1M3Vy9TN0E5RjQ0bVZrU0RucUhRL1FWdzE1S0NRCi9RZUdVNStYVVFqclFIYmo0ZnZIckRKZnBMQ1hNUlNNREl5eDBYUS9EdC8zZjJydkRjMnJzTXhJVWUyMGJ5ak8KaXd5T0V4eTN2UVVMd1BPMlA2VUx5UmFhQklOZzk1c3E2OUtSNG9tMW4wZldua042OGp5TzRxUUVjNTlOZHdLOApNWkNDTnB1KzdlaXEzVUJkQS9kc29KVmlBQ2VrdXJHRkVqdXFQeUpVYmR3NUNKRDdjZk10SnlPZ2dsWmN2OVN2Cm0wZmwvaHBoQk1XdXlZcWd3T2hjaHFoL0VONENqRXV1ZTdvN0VQVWNQZ0RhdWlHZE5CR3ljM04zckNkY1ZwazgKVG5uMUJxeUlPaHdEa21mbVhYMHlJbURidFdjUEc1RXBFS2swRFFJREFRQUJBb0lCQUI5MnE2a20yL3p5WVFYVAphMmlRQU1lWEpEYjY4bjZDYlFEemNqaE5sczE0QWZrdjNJZlFDVkUzTlU1SGlGQlZrN1NUSzM5T2tOVmIxTXVECkNsVU81YVhaK0RqMTE4dTh0SVhkWWRIUjRhYkhCVENNT2t4cWxnai9xNWtUMGVPYm1QREFLcGlTT2ZPV0R5dHQKNE1nY20zNEVPNmhNRVlKalRNem84UHdOK2VWL0xRZUVCYU5FaGxLODcrdFVDTkxXbmxZZE5Oc1JjN3JHdzBkWApYM3R2eDRyTHNrSTBsUE8vUlppc3BLdElCWjA0cnlnOEJ5ZVhTU1BsUzljQTNiNGtqcXo4R2U4TXg4S3FYeE02ClhhaGJ3RElNMU9WYUljWHpuRjlvYkZITmcrRUQvWm1SRHpMbFZ3OEVmYXFXbElYak04b2E5cnl4aExzUTlXT2EKN2ZxWGs0VUNnWUVBNnJrc080NmJEQjF3b1BaMUNqaytwYW5BT2Vlam5YWnBUd1dsUGp5b3JjT09YMS9HeEF3VAo5UW9DNmZubG1FTmZOQW9DYU0vR3l6QkNadW9YdDA0M25zcVBucm5iV3NYMDAvS25TSGJpcjhjTnFtRTFlMEdICmMyeVJMMm1kTWlDdndtODh2czIrY3FuaHY1NHRxWWd5SWh4L1BHNUM4MWRWamd3M3JxNHhBWk1DZ1lFQTFTWksKRUYwNUJReldJYmlRRloyOGNObXVTRHkxdUxFdThFSzZpZUM2bFl0d3M1NnI2SjNDZ1pkUmpKTU95Mk5nakh0cQpaWkhlWnlHalNLOWxMdjdZNVZmSzdQQ0dCLzJ6MVhGbk8rZWt2M3ZEbkFiOHZzeCtwQmJTc3Bhd05lZ084SUp2ClgyUzRRbExPZ09qalBJeUNjaVBicDlQTVdWN3MxT0FUeDc4ODk5OENnWUFUR01XMGdzR3lscUtYTmZZSHd1aUoKNmVtdHpGN1BiTmJjaXdVS3J6eTZCbk1LNTJ2d2Yxc1FVS1EwRFJUVThvWklZWmdZbHU4QmtRZVYvKzIyQ0RNVwpSRHl6R1VQemVxK1VudVZsUytiZGprQmFZRlpObE9ORVRNenpJcENiaDNWRlNHK1V4b0I4Szc0bUxPUmlLcWFKCmgvQUNKcVpqemZNei8ySjRYOHUwNlFLQmdDYjRQeVpLeFBnRlpzajNnM0JRVEhtZGN0M0dLN3MrdWNRM2p2OVMKVlFxdVdjYWRSZlRia3dvNmJqQnpXb3NZK2pmMUFIamRlSG9Ham1IbG4ydytMODJPaFkxWVZFajF1NEZVb0hrMQpXc3VmaHgzcHNSLzVKMVk4emZ6VXpCYXUvTHhBUExpR0k2SU1uYkMzNDRQWWRLa0ZvVTFIemQ2eEdqKzVVQ1IrCjlGaWxBb0dCQU10azhaNm43M1NCMmVDZ3E5cXlQY2I1L3VwMVdIcHJHQXZBYkRoV3Jmak5BRFRuaEJ2Rmt6WWwKNXp4THBUbm9jT1Q3RVRDejJGeWorVGtVR282Z0xNRXUyNlVKS29lcGlmUFJaYzFTVjJQMFlpUUxFakl0c2lKbApiQmwyZmhnQVZVTlhkUHJBRDdqRnh3MmdiQUMrU01WYkpSK0xZWUVsdCtmTjhmRTFFVC96Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==`

`ExecStart={{ bin_dir }}/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction \
  --bind-address=0.0.0.0 --secure-port=6443 \
  --insecure-bind-address=127.0.0.1 --insecure-port=8080 \
  --authorization-mode=Node,RBAC \
  --requestheader-client-ca-file={{ kube_bin }}/ssl/ca.pem \
  --kubelet-https=true \
  --kubelet-client-certificate={{ kube_bin }}/ssl/kubernetes.pem \
  --kubelet-client-key={{ kube_bin }}/ssl/kubernetes-key.pem \
  --anonymous-auth=false \
  --basic-auth-file={{ kube_bin }}/ssl/basic-auth.csv \
  --enable-bootstrap-token-auth \
  --token-auth-file={{ kube_bin }}/ssl/token.csv \
  --service-cluster-ip-range={{ SERVICE_CIDR }} \
  --service-node-port-range={{ NODE_PORT_RANGE }} \
  --tls-cert-file={{ kube_bin }}/ssl/kubernetes.pem \
  --tls-private-key-file={{ kube_bin }}/ssl/kubernetes-key.pem \
  --client-ca-file={{ kube_bin }}/ssl/ca.pem \
  --service-account-key-file={{ kube_bin }}/ssl/ca-key.pem \
  --etcd-cafile={{ kube_bin }}/ssl/ca.pem \
  --etcd-certfile={{ kube_bin }}/ssl/kubernetes.pem \
  --etcd-keyfile={{ kube_bin }}/ssl/kubernetes-key.pem \
  --etcd-servers={{ ETCD_ENDPOINTS }} \
  --enable-swagger-ui=true \
  --endpoint-reconciler-type=lease \
  --allow-privileged=true \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/lib/audit.log \
  --event-ttl=1h \
  --v=1`

执行报错如下
`[root@www ssl]# kubectl get pods -o wide
NAME                         READY     STATUS    RESTARTS   AGE       IP            NODE
deploy-25-8675c9dd46-frsc6   1/1       Running   0          10m       172.30.69.2   11.11.11.202
[root@www ssl]# kubectl logs deploy-25-8675c9dd46-frsc6
Error from server (Forbidden): Forbidden (user=kubernetes, verb=get, resource=nodes, subresource=proxy) ( pods/log deploy-25-8675c9dd46-frsc6)`

我百思不得其解的是明明定义了使用user是admin,这里报错却说我的user是kubernetes
而kubectl get clusterrole这样的需要管理员权限的命令是可以正确执行的...就这个logs和exec不行权限不足

**Comment by onlonely** [comment]
搜索到了是下面这个文章里面的问题...安装脚本希望添加这个node权限
https://www.kubernetes.org.cn/3096.html

**Comment by gjmzj** [comment]
这个问题我碰到过，最新的kubeasz代码应该是解决了该问题；
`kubectl logs`命令还有`kubectl exec`命令，按我的理解它们的执行过程分为两部分：
1.首先是kubectl这个客户端与apiserver的交互（这部分肯定是有权限的）
2.其次是apiserver去访问kubelet服务执行相应的操作（提示没有权限应该是这里的原因，特别的如果kubelet禁用了匿名访问）
关于这个问题说明和解决方式，请查看 https://github.com/gjmzj/kubeasz/blob/master/docs/mixes/01.fix_kubelet_annoymous_access.md

**Comment by onlonely** [comment]
@gjmzj 能说说在那里做了什么配置么,因为我搜索整个项目都没找到你这里在那里进行了哪个文章里面说的赋权
如果不是最近几天修复的应该是没有修复呢,因为我就是最近部署产生的,我是按照哪个文章里面的对这个user赋权才恢复正常的

**Comment by gjmzj** [comment]
1. 做的配置是首先禁用了kubelet 的匿名访问，并开启证书认证 kubelet.service.j2
``` bash
+  --client-ca-file={{ ca_dir }}/ca.pem \
+  --anonymous-auth=false \
```
2. 开启apiserver访问kubelet时候的证书配置 kube-apiserver.service.j2
``` bash
+  --kubelet-client-certificate={{ ca_dir }}/kubernetes.pem \
+  --kubelet-client-key={{ ca_dir }}/kubernetes-key.pem \
```
