### ISSUE TITLE
升级操作时，机子上的service服务无法正常修改可执行路径

### ISSUE THREAD

**Issue by loverto** [gjmzj/kubeasz#225]
1.9.6升级到1.10.2时有以下问题
kubelet的版本不正常，经排查，发现

![image](https://user-images.githubusercontent.com/3992018/41151247-c37d8db2-6b42-11e8-9ee4-34220886d787.png)

这个execstart的路径时通过读取ansible-play模板文件中的bin_dir的变量的，这里的值没有修改，暂时不知道那里的问题
下图时ansible的hosts文件中的变量的值
![image](https://user-images.githubusercontent.com/3992018/41151388-2bf34d8c-6b43-11e8-89fd-3358186a34aa.png)

感觉流程确实啊，为啥创建启动服务的步骤没有打印日志啊
![image](https://user-images.githubusercontent.com/3992018/41152248-ae414ea4-6b45-11e8-9f6c-3b36347bf639.png)

**Comment by gjmzj** [comment]
因为升级不是重新部署一遍，所以hosts文件里面像 bin_dir 这种参数不能去变更它；
当然你要是想重新设置也没问题，那就需要setup.yml脚本完整跑一遍，已有的pod不会丢失，只是会中断一会儿
