### ISSUE TITLE
开启etcd服务失败

### ISSUE THREAD

**Issue by zhouzhi3859** [gjmzj/kubeasz#226]
这是deploy上的
`fatal: [47.52.141.103]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload && systemctl restart etcd", "delta": "0:00:00.094354", "end": "2018-06-10 15:30:45.329974", "msg": "non-zero return code", "rc": 1, "start": "2018-06-10 15:30:45.235620", "stderr": "Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}
fatal: [47.75.184.41]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload && systemctl restart etcd", "delta": "0:00:00.097033", "end": "2018-06-10 15:30:45.405983", "msg": "non-zero return code", "rc": 1, "start": "2018-06-10 15:30:45.308950", "stderr": "Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}`

这是在目标机器上打印出来的
`Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: etcd Version: 3.3.4
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: Git SHA: fdde8705f
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: Go Version: go1.9.5
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: Go OS/Arch: linux/amd64
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false, crl-file = 
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ etcd[20743]: listen tcp 47.75.184.41:2380: bind: cannot assign requested address
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ systemd[1]: Failed to start Etcd Server.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ systemd[1]: Unit etcd.service entered failed state.
Jun 10 15:27:29 iZj6cahkjrz69jaiu06c5yZ systemd[1]: etcd.service failed.`

**Comment by zhouzhi3859** [comment]
@gjmzj

**Comment by gjmzj** [comment]
```
listen tcp 47.75.184.41:2380: bind: cannot assign requested address
```
无法绑定这个IP地址，请检查下etcd服务上有这个IP地址吗？

**Comment by kobehaha** [comment]
如果是云服务器是是不能绑定这个地址的, 查了一下这是阿里云香港的服务器， 公网ip 是没有直接绑定到服务器上的，可以尝试绑定0.0.0.0或则内网

**Comment by kobehaha** [comment]
我比较推荐你如果用阿里云的话，都用内网来处理，你直接把ip 更改为内网ip就好，如果有一些对外访问的服务，增加ingress或则SLB就好. 所有机器最好在一个vpc内
