### ISSUE TITLE
kubernetes flannel 网络插件模式下 容器ip 分配存在问题

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#227]
**文件**

目前发现通过该方式部署kubernetes 集群存在pods ip 分配问题, 查看一台node[内网ip 为192.168.0.66] 它的flannel ip地址为 172.12.2.0 不过实际分配IP的时候，分配了错误的ip地址.  分配地址为172.12.0.x

![dd](https://user-images.githubusercontent.com/14839922/41221366-847fd51a-6d96-11e8-9b7d-30fb1b602664.png)

![screen shot 2018-06-11 at 4 41 16 pm](https://user-images.githubusercontent.com/14839922/41221459-c8e2aa5c-6d96-11e8-83d0-cac66b23add7.png)

在查看启动log可以看到很明显的错误是他想去占用172.12.0.0/24，不过估计ip 段被占用了，然后启动就有问题.  

![screen shot 2018-06-11 at 4 40 48 pm](https://user-images.githubusercontent.com/14839922/41221482-d2c70af4-6d96-11e8-8e42-2a568438a8e5.png)

**Comment by gjmzj** [comment]
`kubectl delete -f /opt/kube/kube-system/flannel/`清理下flannel安装，然后重新执行`ansible-playbook 06.network.yml`安装，看看是否解决问题；当然已有的pod需要删除，让deployment自动重建，看看故障现象还在不在

**Comment by kobehaha** [comment]
对整个集群都重新处理和删除所有Pods的改动比较大，我重新删除节点，重新加入，现在是恢复了.
