### ISSUE TITLE
network docker flanell

### ISSUE THREAD

**Issue by Mrhjx2** [gjmzj/kubeasz#229]
你这里好像没有配置docker的网桥属于flannel的网段也？？
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:63:e5:36:8e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether ba:f5:74:5a:df:27 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::b8f5:74ff:fe5a:df27/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by weilinqwe** [comment]
属于flannel的网桥应该是cni0好像，没有注入到docker启动参数里，所有docker0还是独立存在的，相当于有两个网桥

**Comment by gjmzj** [comment]
docker0网桥还是存在的，只是不去用它而已

**Comment by Mrhjx2** [comment]
谢谢

**Comment by ut2014** [comment]
我刚把 集群 装上 ，docker 与flannel 不在同一网段！！本想 调为同网段但这 二个网段 都能ping得通，就不调了，会对以后 有什么影响吗？
