### ISSUE TITLE
安装一切正常，但是无论如何找不到bgp peer

### ISSUE THREAD

**Issue by guohongze** [gjmzj/kubeasz#23]
使用单主多从模式
**master**
root@ubuntu:/etc/ansible# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.47.2    0.0.0.0         UG    0      0        0 ens33
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.243.192  0.0.0.0         255.255.255.255 UH    0      0        0 cali5e6a6a095c0
172.20.243.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.20.243.193  0.0.0.0         255.255.255.255 UH    0      0        0 cali01719dd8ee3
172.20.243.194  0.0.0.0         255.255.255.255 UH    0      0        0 cali79d9335e2eb
172.20.243.196  0.0.0.0         255.255.255.255 UH    0      0        0 cali86295d33f81
192.168.47.0    0.0.0.0         255.255.255.0   U     0      0        0 ens33

**node01**
root@ubuntu:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.47.2    0.0.0.0         UG    0      0        0 ens33
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.243.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.20.243.195  0.0.0.0         255.255.255.255 UH    0      0        0 cali383215e280f
192.168.47.0    0.0.0.0         255.255.255.0   U     0      0        0 ens33

**node02**
root@ubuntu:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.47.2    0.0.0.0         UG    0      0        0 ens33
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.243.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.20.243.197  0.0.0.0         255.255.255.255 UH    0      0        0 cali5ef7fb336ac
192.168.47.0    0.0.0.0         255.255.255.0   U     0      0        0 ens33

所有机器上的bgp peer信息
root@ubuntu:/etc/ansible# calicoctl node status
Calico process is running.

IPv4 BGP status
No IPv4 peers found.

IPv6 BGP status
No IPv6 peers found.

root@ubuntu:/etc/ansible#

**Comment by guohongze** [comment]
找到原因了 calico-node 服务没有正常启动，无法进行bind，应该是由于主机名不可解析导致，变更主机名，并在hosts中解析后恢复。

**Comment by eehuangyanwen** [comment]
兄弟，能不能更详细描述一下
