### ISSUE TITLE
探讨一下dashboard1.8.3双因子认证

### ISSUE THREAD

**Issue by weilinqwe** [gjmzj/kubeasz#235]
发现文档里方法很多，就有点乱，没明白里面的细节。
根据文档分为两阶段认证：一种是dashboard通过serviceaccount（kubernetes-dashboard）到apiserver认证，一种是以admin用户登录dashboard认证。
kubectl create -f kubernetes-dashboard.yaml
然后访问https://192.168.11.90:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy报错：
"services \"https:kubernetes-dashboard:\" is forbidden: User \"admin\" cannot get services/proxy in the namespace \"kube-system\"",
我理解因为通过apiserver访问dashboard，默认用admin用户（这个是不是不能改的？），没有赋权所以没法访问dashboard
kubectl create -f ui-admin-rbac.yaml  给admin用户赋权services之后，就能访问dashboard了，这是因为kubernetes-dashboard只是绑定了kubernetes-dashboard-minimal，所以出来告警好多集群的内容因为无权限访问。这时连dashboard的登录界面也没跳出来。

这时，我只能停掉dashboard，把serviceaccount kubernetes-dashboard绑到clusterrole:cluster-admin
启动dashboard就好了，连dashboard的登录界面没跳出来，就直接能看到管理集群所有信息了。

所以：
1. kubectl create -f ui-admin-rbac.yaml 给用户admin赋权访问services和services/proxy
2. 修改kubernetes-dashboard.yaml，给serviceaccount:kubernetes-dashboard绑到clusterrole:cluster-admin（集群所有权限）或者根据情况绑定响应的权限（对应dashboard只能管理相应的内容）
3. kubectl create -f kubernetes-dashboard.yaml 启动dashboard
4. https://*.*.*.*:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy免登陆访问

**Comment by weilinqwe** [comment]
1. admin-user-sa-rbac.yaml这个好像都没必要执行，serviceacount: admin-user哪里会用到？
2. dashboard怎么配置admin用户或者readonly用户登录？
3. NodeIP：NodePort无法访问，显示：NET::ERR_CERT_INVALID 。如果要关闭，是把service改成clusterip还是直接注释掉service？

**Comment by gjmzj** [comment]
其实dashboard 1.8.3没必要那么复杂，可以考虑用nodeport方式暴露服务，然后直接用dashboard自带的登陆方式去认证；
文档中讲到认证apiserver的方式主要是因为之前dashboard版本没有认证机制，所以我加上去的；

**Comment by weilinqwe** [comment]
最简单的办法是：nodeport方式暴露服务，然后kubernetes-dashboard.yaml里serviceaccount:kubernetes-dashboard绑到clusterrole:cluster-admin（集群所有权限）就ok了，连dashboard自带的登录可以跳过。但也碰到个问题：虽然按照文档做的，但浏览器访问nodeport报CA证书有问题，chrome没办法跳过，firefox可以允许例外跳过

**Comment by forbxy** [comment]
@weilinqwe 老哥这个证书报错有解决方案吗?

**Comment by forbxy** [comment]
chrome的提示不完备吧，证书错误是因为证书是自签名的。

**Comment by forbxy** [comment]
火狐中查看该证书，起始和结束时间均为
1901/1/1 上午8:00:00 (Asia/Shanghai)
