### ISSUE TITLE
分步安装calico文档有误，请确认。

### ISSUE THREAD

**Issue by lovebaicai** [gjmzj/kubeasz#236]
## [06-安装calico网络组件.md](https://github.com/gjmzj/kubeasz/blob/master/docs/06.calico.md)
- 本项目提供多种网络插件可选，如果需要安装calico，请在/etc/ansible/hosts文件中设置变量 **`CLUSTER_NETWORK="kube-router"`**（**此处应该为`CLUSTER_NETWORK="calico"`？**）
- calico配置文件[calico.yaml.j2](https://github.com/gjmzj/kubeasz/blob/master/roles/calico/templates/calico.yaml.j2)，第137行：此处配置`CALICO_IPV4POOL_IPIP`，这个value在之前的hosts文件里可配置，现在[hosts](https://github.com/gjmzj/kubeasz/blob/master/example/hosts.m-masters.example)文件更新取消了这个选项，是否目前calico版本已默认支持跨网段？或是在其他配置文件里设置。
```
- name: CALICO_IPV4POOL_IPIP
  value: "{{ CALICO_IPV4POOL_IPIP }}"
```
  
- 以上，请帮忙确认，谢谢！

**Comment by gjmzj** [comment]
1.文档的笔误，感谢提醒
2.calico新的配置文件在roles/calico/defaults/main.yml

**Comment by lovebaicai** [comment]
@gjmzj 非常感谢！
