### ISSUE TITLE
多主多节点 master virtual  ip

### ISSUE THREAD

**Issue by lsy643** [gjmzj/kubeasz#24]
请教一下，在多主多节点的配置中，您提到要规划一个额外的master VIP。
这个master VIP是只需要分配一个与其他master同网段的就行，还是得有其他什么要求？
或者您能详细解释一下这个master VIP吗？
谢谢

**Comment by gjmzj** [comment]
是的，master VIP分配一个与其他master同网段的即可；vip是靠keepalived生成的，活在keepalived的主节点上，如果主节点故障能够切换到备节点上

**Comment by lsy643** [comment]
@gjmzj 
多谢
