### ISSUE TITLE
coredns  的问题

### ISSUE THREAD

**Issue by songhe2136** [gjmzj/kubeasz#241]
coredns 日志如下
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
10.10.3.61 是我的上游 内网 dns。
检查了配置，组件日志也没啥问题。不知道怎么回事
然后
我配置上游dns 为公共dns 也不行：
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout

**Comment by gjmzj** [comment]
你是在coredns deployment中使用configmap配置的吗？能否贴一下你的配置；
另外，目前我这边主要是靠在node的主机resolv.conf中配置实现内网dns/上游dns功能的，比如：
``` bash
cat /etc/resolv.conf
domain test.localdomain
search test.localdomain
nameserver 10.x.x.x
```

**Comment by songhe2136** [comment]
对是 在 coredns deployment中使用configmap：
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
---

我也是 继承的 node 上的 resolv.conf 配置文件。  resolv.conf 配置文件我无论写内网还是公共dns 地址，都是  有日志   i/o timeout的记录。虽然 coradns 的日志一直报这个  i/o timeout，但是我起的pod 依然能解析 公网 dns 记录，就是 有明显的卡顿，每次解析要先停 3 秒，才解析通过。

**Comment by gjmzj** [comment]
172.30.47.5 这个地址是coredns的一个pod吧，这个pod访问外网有问题吗？如果有问题是不是k8s的网络插件有问题

**Comment by songhe2136** [comment]
172.30.47.5 是 我起的  其他的 pod ，kubectl exec 到 pod 里  查看 /etc/resov.conf ，获取到了 coredns 的地址。
我所有的 pod 都能  ping 通  公网ip，没有丢包延迟现象，唯独ping 公网域名，i/o timeout

**Comment by gjmzj** [comment]
请问有没有找到原因？

**Comment by songhe2136** [comment]
已经解决了

**Comment by gjmzj** [comment]
能不能简要分享下解决过程

**Comment by zchunhai** [comment]
我也遇到了同样的问题，请问最后的解决方法是什么了

**Comment by songhe2136** [comment]
把 宿主机的 /etc/resolv.conf  清空，zhixie

**Comment by medzeus2** [comment]
> 把 宿主机的 /etc/resolv.conf 清空, 只写 nameserver xxx 多余的部分全部删除。然后删除重建coredns.

按照楼主的方法解决了。这个缺陷能不能修复下。

**Comment by WTwilight** [comment]
我也遇到了这个问题，但是按照 @songhe2136 说的来做在我这不起效。coredns容器中/etc/resolv.conf文件里获取的还是它自己的service的地址。  
我是通过修改配置临时解决了这个问题：  
将配置文件中的
```
proxy . /etc/resolv.conf
```
改为
```
proxy . xxx.xxx.xxx.xxx
```
其中`xxx.xxx.xxx.xxx`表示主机所在的局域网中可用的DNS地址

**Comment by wyfaq** [comment]
> > 我也遇到了这个问题，但是按照 @songhe2136 说的来做在我这不起效。coredns容器中/etc/resolv.conf文件里获取的还是它自己的service的地址。
> > 我是通过修改配置临时解决了这个问题：
> > 将配置文件中的
> > ```
> > proxy . /etc/resolv.conf
> > ```
> > 改为
> > ```
> > proxy . xxx.xxx.xxx.xxx
> > ```
> > 其中`xxx.xxx.xxx.xxx`表示主机所在的局域网中可用的DNS地址
> 
> 这个问题的终极原因是 NetworkManager 这个服务，把这个服务关掉，重新部署coredns，就可以了。

确定为NetworkManager 服务吗？我这个NetworkManager 服务并没有启动，但是也有这个问题。
# systemctl list-unit-files | grep Network
NetworkManager-dispatcher.service             disabled
NetworkManager-wait-online.service            enabled 
NetworkManager.service                        disabled

**Comment by 1998729** [comment]
I found the final solution. If your network uses Flannel, then you can apply directly. You need to modify the cidr inside and be consistent with the podcidr in kubelet and kube-proxy

**Comment by ChenJhua** [comment]
i have same issue
