### ISSUE TITLE
根CA和签发的证书有效期问题（根CA有效期为5年，而签发的证书有效期为10年）

### ISSUE THREAD

**Issue by yuyicai** [gjmzj/kubeasz#242]
cfssl签发的根CA默认有效期是5年（43800h），而CA签发的证书设定有效期为10年（87600h），签发的证书有效期比CA有效期长。  
https://github.com/cloudflare/cfssl/blob/793fa93522ffd9a66d743ce4fa0958b6662ac619/initca/initca.go#L224  
cfssl certinfo -cert ca.pem  
```
......
......
  "not_before": "2018-06-18T09:37:00Z",
  "not_after": "2023-06-17T09:37:00Z",
......
......
```

cfssl certinfo -cert kube-proxy.pem
```
......
......
  "not_before": "2018-06-18T09:37:00Z",
  "not_after": "2028-06-15T09:37:00Z",
......
......
```

**Comment by gjmzj** [comment]
很仔细；不过我觉得不管是5年，10年都是足够长的时间了，况且即便真到期，整个集群换掉CA证书和所有其他证书应该也可以；
另外在创建CA证书的时候应该也有参数设置有效期，如果你熟悉，请分享给大家

**Comment by ssslkj123** [comment]
刚刚测试了一下 ，该方式确实有效，能够签署100年的证书，防止由于ca自己的密钥对过期，反而ca签署证书的没有过期这种逻辑错误的情况出现，感谢 @gjmzj
