### ISSUE TITLE
关于dashboard文档中“证书访问”的证书导出无效的问题

### ISSUE THREAD

**Issue by klgd** [gjmzj/kubeasz#246]
之前试了几次导出证书，浏览器始终显示是无效证书，后来就放弃这种方式，今天无意间在别的文档里看到了下面的命令
```sh
openssl pkcs12 -export -in admin.pem -inkey admin-key.pem -certfile ca.pem -out kube-admin.p12
```
试了一下，结果成功，比对文档中的命令，发现是少了参数`-certfile ca.pem`   
`openssl pkcs12 --help` 查看了一下help，显示`-certfile f   add all certs in f`    
不过不是很懂这个参数是什么作用，所以也没有提交PR

**Comment by gjmzj** [comment]
感谢提醒；
导出证书操作应该我这边测试一直是成功的，可能一些环境或者其他原因导致你导出不成功；
你找到的命令，可以作为补充；btw这个参数help信息我也没看懂

**Comment by vsxen** [comment]
dashboard文档好像需要更新

1. 临时访问：使用 https://NodeIP:NodePort 方式直接访问 dashboard，生产环境建议关闭该途径

这个已经不行了

版本 67.0.3396.99（正式版本） （64 位） NET::ERR_CERT_INVALID

**Comment by vsxen** [comment]
https://github.com/gjmzj/kubeasz/blob/master/roles/prepare/tasks/main.yml#L26
这个好像有问题，deploy的机器应该是生成的config 而不是直接copy吧  （前提ansible和master不是同一台机器）

**Comment by dushitaoyuan** [comment]
是的,证书位置在:/etc/kubernetes/ssl,但是我可能没设置ntp时间服务器更新,不知道为啥,我allinone安装之前,更新了服务器时间,但是安装完毕后,时间不对,使用命令导出p12并给主机安装后,但是证书未生效
k8s新手,
个人建议:可将证书时间提前一天,或新增dashboard访问说明,我是新手,排查问题花了很久
