### ISSUE TITLE
这里必须是3吗？如果我的master想部署5个这里是3还是5？

### ISSUE THREAD

**Issue by TimeBye** [gjmzj/kubeasz#251]
https://github.com/gjmzj/kubeasz/blob/48f473b74545923f027420da46ca85a7bb825b1a/roles/kube-master/templates/kube-apiserver-v1.8.service.j2#L30

**Comment by gjmzj** [comment]
不是必须3，不过考虑设置3，足够好了，3可以应对master1个，2个，3个情况；
即便master扩展到4个，5个，这里设置3应该也没事，它可以保障apiserver endpoints有3个（某个时刻从5个里选3个，从整体一段时间看还是5个master在轮流工作）；
当然我相信设置5也可以的；
更好的一种做法是根据master实际数量来设置这个值；

**Comment by TimeBye** [comment]
哦  好的   谢谢讲解    将此处改为以下变量可好？
```
 --apiserver-count={% if DEPLOY_MODE == "multi-master" %}{{ groups['kube-master']|length + groups['new-master']|length }}{% else %}1{% endif %}
```

**Comment by gjmzj** [comment]
有道理:)
