### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#26]
请问我如何升级dashboard到1.8呢

**Comment by gjmzj** [comment]
dashboard 1.8我还没测试过，测完我更新dashboard文档吧

**Comment by kobehaha** [comment]
请问dashboard我这边更新的很慢，然后经常需要刷很久，这是我网路设置有问题吗？

**Comment by kobehaha** [comment]
还是说可能是机器单页面刷新就很慢，获取数据采集慢？
