### ISSUE TITLE
ansible centos7.4 单主多node安装失败

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#269]
这个down 目录下之前版本一直没有问题为啥
这次要去里面找东西（flannel_v0.10.0-amd64.tar,/etc/ansible/down/pause_3.1.tar）既然是二进制安装那么你的东西都应该放入down目录而不是在线下载查找？ 还有就是ansible down下的这些东西在哪里下载 我看你的ansible里面没有提到这些文件的下载
![3](https://user-images.githubusercontent.com/17851645/43127277-b55214e0-8f61-11e8-8c7a-2c3c4cc98021.png)
![4](https://user-images.githubusercontent.com/17851645/43127293-bf49f4f4-8f61-11e8-8f22-4c34733b86c9.png)

![2](https://user-images.githubusercontent.com/17851645/43127021-f815c174-8f60-11e8-9733-ff001fbb5880.png)

**Comment by gjmzj** [comment]
这个不一定是安装失败，如果没有手动下载离线docker镜像，是比较慢；如果服务器能上网的话，会下载并运行的

**Comment by Hello-Linux** [comment]
本地服务器上网都没有问题的,运行了10次了都卡在了这个地方

**Comment by Hello-Linux** [comment]
还有一个问题就是安装成功过了 kuber的二进制命令好像都放在了/opt/kube/bin 并没有在linux的PATH变量里面定义

**Comment by Hello-Linux** [comment]
安装完后运行kubectl cluster-info      kubectl get nodes 显示
![6](https://user-images.githubusercontent.com/17851645/43129849-db132c04-8f67-11e8-96a6-b13732e2c3cc.png)
![7](https://user-images.githubusercontent.com/17851645/43129922-06c037fc-8f68-11e8-813d-7574bafce2c2.png)
@gjmzj

**Comment by Hello-Linux** [comment]
还有就是flannel 镜像都下载下来了为什么flannel error呢？
![8](https://user-images.githubusercontent.com/17851645/43130224-ce9ac184-8f68-11e8-8730-748cfce3c42a.png)
![9](https://user-images.githubusercontent.com/17851645/43130232-d5968702-8f68-11e8-81c1-07071a6b44fe.png)

**Comment by Hello-Linux** [comment]
还有就是如果ansible安装k8s失败了该怎么回退呢？

**Comment by gjmzj** [comment]
看你的输出，应该是master节点和node都已经安装成功了；就在安装flannel网络的时候有问题；
你问的问题安装文档里面都有，但是需要你去看它们

**Comment by Hello-Linux** [comment]
恩恩后面我看看报错,刚提交了一个pull request 请求你看看可以不,因为centos7有很多prepare条件你的ansible里面没有涉及到或者您自己修改一下也可以
![1](https://user-images.githubusercontent.com/17851645/43177537-555270e0-8ffb-11e8-9bc9-505c598589b5.png)

**Comment by Hello-Linux** [comment]
还有就是每次添加新东西到master前最好测试一下整个流程能否跑通,   否则不要合并到master分支,   刚把你的代码更新就跑不通了.....

@gjmzj 


![3](https://user-images.githubusercontent.com/17851645/43180282-c3379d5c-9009-11e8-985b-261b6a81b6c8.png)
