### ISSUE TITLE
harbor的证书文件存放目录

### ISSUE THREAD

**Issue by zhaop33** [gjmzj/kubeasz#278]
你好：
安装好集群之后设置harbor（是另外的主机上的harbor），安装证书目录是在/etc/docker下面吗？这个下面没有任何的证书文件，我把证书放在这个下面，也不行，其它机子上就可以，请问这个安装后的docker的证书文件是在哪个目录下面呢？

**Comment by gjmzj** [comment]
如果你harbor使用ip（例如192.168.1.8）地址访问，那么你要把harbor证书放到node节点的如下目录：
`/etc/docker/certs.d/192.168.1.8/ca.crt`
如果使用域名（例如harbor.test.lo）访问，那么放到如下：
`/etc/docker/certs.d/harbor.test.lo/ca.crt`

**Comment by gjmzj** [comment]
如果你harbor使用ip（例如192.168.1.8）地址访问，那么你要把harbor证书放到node节点的如下目录：
`/etc/docker/certs.d/192.168.1.8/ca.crt`
如果使用域名（例如harbor.test.lo）访问，那么放到如下：
`/etc/docker/certs.d/harbor.test.lo/ca.crt`

**Comment by zhaop33** [comment]
弄好了，谢谢
