### ISSUE TITLE
启动kubelet报错

### ISSUE THREAD

**Issue by chenyj796** [gjmzj/kubeasz#283]
按照https://github.com/gjmzj/kubeasz/blob/master/docs/quickStart.md 执行到以下任务时报错：
**TASK [kube-node : 轮询等待kubelet启动]** ***************************************************************************************************************
FAILED - RETRYING: 轮询等待kubelet启动 (8 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (7 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (6 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (5 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).
fatal: [192.168.1.175]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.006"2018-08-08 15:10:36.996597", "rc": 0, "start": "2018-08-08 15:10:36.990282", "stderr": "", "stderr_lines": [], "stdout": "   Active: activatingt) (Result: exit-code) since Wed 2018-08-08 15:10:32 CST; 4s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) si08-08 15:10:32 CST; 4s ago"]}
	to retry, use: --limit @/etc/ansible/90.setup.retry

**journalctl -u kubelet**
Aug 08 15:11:30 ecs-fbfb-0002.novalocal systemd[1]: Starting Kubernetes Kubelet...
Aug 08 15:11:30 ecs-fbfb-0002.novalocal systemd[1]: Started Kubernetes Kubelet.
Aug 08 15:11:30 ecs-fbfb-0002.novalocal kubelet[83909]: I0808 15:11:30.208834   83909 feature_gate.go:220] feature gates: &{{} map[]}
Aug 08 15:11:30 ecs-fbfb-0002.novalocal kubelet[83909]: I0808 15:11:30.208900   83909 controller.go:114] kubelet config controller: starting controller
Aug 08 15:11:30 ecs-fbfb-0002.novalocal kubelet[83909]: I0808 15:11:30.208906   83909 controller.go:118] kubelet config controller: validating combination of
Aug 08 15:11:30 ecs-fbfb-0002.novalocal kubelet[83909]: **error: unable to load client CA file /etc/kubernetes/pki/ca.crt**: open /etc/kubernetes/pki/ca.crt: no 
Aug 08 15:11:30 ecs-fbfb-0002.novalocal systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Aug 08 15:11:30 ecs-fbfb-0002.novalocal systemd[1]: Unit kubelet.service entered failed state.
Aug 08 15:11:30 ecs-fbfb-0002.novalocal systemd[1]: kubelet.service failed.

错误信息：没有找到/etc/kubernetes/pki/ca.crt

**Comment by gjmzj** [comment]
单节点的部署吗?这步是安装05.kube-node.yml，那么前几步都验证成功了吗？
按理说按照kubeasz部署的话，ca证书是放在 /etc/kubernetes/ssl/ca.pem的；是不是你之前装过其他的，没有清理干净？

**Comment by chenyj796** [comment]
是单节点部署。
我直接运行ansible-playbook 90.setup.yml，是需要单独每一步来执行么？
测试机器是电信天翼云的，以前安装过docker，在运行脚本前我已经把它给卸载了

**Comment by gjmzj** [comment]
正常安装的kubelet服务文件如下：（/etc/systemd/system/kubelet.service）不会去寻找找到/etc/kubernetes/pki/ca.crt

``` bash
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
#--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest
ExecStart=/opt/kube/bin/kubelet \
  --address=10.100.x.x \
  --hostname-override=10.100.x.x \
  --pod-infra-container-image=mirrorgooglecontainers/pause-amd64:3.1 \
  --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --cert-dir=/etc/kubernetes/ssl \
  --client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --network-plugin=cni \
  --cni-conf-dir=/etc/cni/net.d \
  --cni-bin-dir=/opt/kube/bin \
  --cluster-dns=10.68.0.2 \
  --cluster-domain=cluster.local. \
  --hairpin-mode hairpin-veth \
  --allow-privileged=true \
  --fail-swap-on=false \
  --anonymous-auth=false \
  --logtostderr=true \
  --v=2
#kubelet cAdvisor 默认在所有接口监听 4194 端口的请求, 以下iptables限制内网访问
ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
~                                                               
```
如果没法排查出来，建议使用新的虚机安装

**Comment by chenyj796** [comment]
谢谢，我重新刻一台CentOS Minimal，安装成功了
