### ISSUE TITLE
针对centos7.5 service使用IPVS负载均衡问题

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#287]
我现在想知道现在k8s V11版本使用kube-proxy的PROXY_MODE=IPVS模式会有问题么？

**Comment by Hello-Linux** [comment]
我看之前已经有人提起过了说是V1.11.1已经解决这个问题了,不知道 @gjmzj 有没有更新离线安装包呢？
![error](https://user-images.githubusercontent.com/17851645/44086500-5f0a1d64-9fef-11e8-921e-055741d89550.png)

**Comment by gjmzj** [comment]
离线包已经更新到 1.11.2了；
另外建议centos 更新内核版本，3.x太老了，更新内核很方便，可以参考这里：
https://github.com/gjmzj/kubeasz/blob/master/docs/guide/kernel_upgrade.md

**Comment by Hello-Linux** [comment]
ok
