### ISSUE TITLE
关于nginx-ingress-controller问题

### ISSUE THREAD

**Issue by pengyan2018** [gjmzj/kubeasz#3]
gjmzj 你好，很高兴看到国内有人在做K8S的自动化部署，而且做到如此棒的地步！
现在有个问题，想咨询一下：在你的这种部署方式下，跑nginx-ingress-controller是否有问题？
我目前的情况是：我是用kubeadm部署的K8S集群，pod、svc这些都能正常运行。但是部署nginx-ingress-controller(https://github.com/kubernetes/ingress-nginx)时，该pod总是CrashLoopBackOff。查看日志发现是api server连不上。进一步用https://github.com/kubernetes/ingressnginx/blob/master/docs/troubleshooting.md中方法来验证：kubectl exec test-701078429-s5kca -- curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H  "Authorization: Bearer $TOKEN_VALUE" https://10.96.0.1  总是提示Failed to connect to 10.96.0.1 port 443: Connection timed out

10.96.0.1是我的kubernetes svc地址：
NAMESPACE       NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default         kubernetes             ClusterIP   10.96.0.1      <none>        443/TCP         26d
ingress-nginx   default-http-backend   ClusterIP   10.102.71.61   <none>        80/TCP          2d
kube-system     kube-dns               ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP   26d

**Comment by gjmzj** [comment]
@pengyan2018 [你好，目前我还没有在这个部署中跑过nginx-ingress-controller，所以恐怕不能确定性回复你的问题；不过我已经实践过[安装traefik ingress](https://github.com/feiskyer/kubernetes-handbook/blob/master/practice/service-discovery-lb/traefik-ingress-installation.md)没有问题，且一直在运行中。
因此猜测这种部署方式下，跑nginx-ingress-controller也没有问题

**Comment by pengyan2018** [comment]
@gjmzj 很高兴收到你的回复，我会尽快验证traefik ingress

**Comment by gjmzj** [comment]
@pengyan2018 `traefik ingress` 的部署可以参考manifests/ingress里面的，另外项目持续更新中，期待你的关注和建议
