### ISSUE TITLE
k8s 官方建议的etcd版本为 3.1.10

### ISSUE THREAD

**Issue by DiamondYuan** [gjmzj/kubeasz#30]
具体详情可以看这里

External Dependencies
The supported etcd server version is 3.1.10, as compared to 3.0.17 in v1.8 (#49393, @hongchaodeng)
The validated docker versions are the same as for v1.8: 1.11.2 to 1.13.1 and 17.03.x
The Go version was upgraded from go1.8.3 to go1.9.2 (#51375, @cblecker)
The minimum supported go version bumps to 1.9.1. (#55301, @xiangpengzhao)
Kubernetes has been upgraded to go1.9.2 (#55420, @cblecker)

**Comment by gjmzj** [comment]
目前这边采用的是3.2.x版本，也没啥问题，当然如果上生产环境可以使用官方推荐的版本来部署
