### ISSUE TITLE
关于Prometheus问题，求教大神解答

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#310]
利用helm安装Prometheus，后端存储需要在那里修改，比如后端存储用的是阿里云的NFS，应该在那里添加参数实现远程存储呢

**Comment by gjmzj** [comment]
修改都在values.yaml里面，具体需要把几个persistentVolume参数设置 enabled: true;
然后再利用阿里云的NFS创建PV，这个可以网上找文档，也可以直接使用kubeasz里面支持的aliyun nfs创建PV（https://github.com/gjmzj/kubeasz/blob/master/docs/08-cluster-storage.md）

**Comment by sunchangming** [comment]
谢谢大神
