### ISSUE TITLE
大神，求教grafana问题

### ISSUE THREAD

**Issue by sunchangming** [gjmzj/kubeasz#313]
利用helm安装Prometheus和grafana，如果我想在grafana上安装插件应该怎样才能使插件生效呢，我是kubectl exec进入到grafana容器之后执行的grafana-cli install方式安装，但是不能重启grafana服务，插件不能生效

**Comment by sunchangming** [comment]
好的，明白

**Comment by catherine703** [comment]
请问一下，我自己安装了grafana插件，然后做成了镜像，传到阿里云的镜像服务里面，那怎么指定每次启动时，是读取的我自己的镜像文件呢？

**Comment by HBQ7WsVVwL** [comment]
> 好的，明白

我也有你这个需求，然后是直接修改的配置文件，就可以实现了

**Comment by gold-dream-teacher** [comment]
> > 好的，明白
> 
> 我也有你这个需求，然后是直接修改的配置文件，就可以实现了

你是怎么修改的呢?我想装一个阿里云的第三方监控插件,在value.plugins修改发现容器不能正常启动
