### ISSUE TITLE
在 node上安装kubelet后，报错error: failed to run Kubelet: cannot create certificate signing request: Post https://${NODE_IP}:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp ${NODE_IP}:6443: getsockopt: connection refused 

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#32]

**Comment by peterpijing** [comment]
求助

**Comment by DiamondYuan** [comment]
你的配置文件发一下

**Comment by peterpijing** [comment]
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet2
ExecStart=/root/local/bin/kubelet \
  --address=${NODE_IP} \
  --hostname-override=${NODE_IP} \
  --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest \
  --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
  --kubeconfig=/etc/kubernetes/kubelet-kubeconfig \
  --require-kubeconfig \
  --cert-dir=/etc/kubernetes/ssl \
  --container-runtime=docker \
  --cluster-dns=10.254.0.2 \
  --cluster-domain=cluster.local. \
  --hairpin-mode promiscuous-bridge \
  --allow-privileged=true \
  --serialize-image-pulls=false \
  --register-node=true \
  --logtostderr=true \
  --v=2
ExecStopPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT
ExecStopPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT
ExecStopPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT
ExecStopPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by gjmzj** [comment]
@peterpijing 你的配置可不是我项目里面对应的配置 `roles/kube-node/templates/kubelet.service.j2`
你可以手动把参数  `${NODE_IP}` 替换成你实际IP

**Comment by peterpijing** [comment]
我安装是写的node节点的实际ip(10.10.xx.xx)，只是这里留言写的${NODE_IP}  @gjmzj

**Comment by peterpijing** [comment]
我看你的文档都是基于ansible,所以ansible都是基于key认证到非deploy节点进行部署对应的服务对吧？
但是现在的问题是我们为了安全禁止了key认证登陆的方式，除了手动部署，还有其他办法吗？请问？@gjmzj

**Comment by gjmzj** [comment]
@peterpijing ansible 也支持用户名+密码登陆的，手动部署多麻烦，而且容易出错；
还有你的配置文件跟本项目的还是有点不一样，k8s v1.8 1.9 根据你的配置kubelet可能无法运行；
题外话：为了安全其实就应该用Key认证的，用户名+密码安全问题多；

**Comment by peterpijing** [comment]
是这样的，服务器为了安全！ key认证和用户名+密码的认证，这两种认证方式都被禁用了！ 这就是痛点@gjmzj  所以，还有别的建议吗？

**Comment by gjmzj** [comment]
@peterpijing 你说的情况大概是公司的服务器运维都上了堡垒机，那可以集群创建阶段暂时开放权限，之后再纳管起来

**Comment by peterpijing** [comment]
只需要deploy节点和其他节点认证就可以了吧？？那ansible的认证方式，除了key和用户-密码,
agent的认证的方式你用过吗？@gjmzj c

**Comment by gjmzj** [comment]
只需要deploy节点能够登陆其他节点即可；
我只用过key认证方式
