### ISSUE TITLE
k8s v1.111.3 安装后无法打开dashboard

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#324]
k8s v1.111.3 安装后无法打开dashboard

运行方法: nsible-playbook 90.setup.yml

安装后ansible-playbook 90.setup.yml

安装好了后一切正常,但是无法打开bashboard.网页提示错误如下:
Error: 'net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://172.20.xx.xx:8443/'

换成同目录下面的1.6.3/kubernetes-dashboard.yaml正常可以打开. 

请问这是否需要纠正? 谢谢!

**Comment by evenye** [comment]
更新一下,找到原因了. 在安装的时候集群网络插件如果选用kube-router就会引发这个问题,但改选calico则一切正常.

**Comment by gjmzj** [comment]
说明下你安装的机器是公有云，还是自有的虚机，物理机？
公有云上一般是不支持kube-router

**Comment by gjmzj** [comment]
这个应该没啥影响，如果你们的基础设施有什么特殊的地方，那需要咨询网络工程师了

**Comment by evenye** [comment]
谢谢,我用的是vmware. 不确定是什么原因. 用calico解决了这个问题.
