### ISSUE TITLE
关于CA证书以及kubeconfig的分发问题

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#333]
我看ansible里面ca证书以及kubeconfig配置文件应该是分发到master node etcd上的但是anbile playbook里面为啥写的是delegated_to deploy节点呢那样的话同步模块不就在本地执行了么？如何分发到节点？
![error](https://user-images.githubusercontent.com/17851645/46604669-9513ca80-cb29-11e8-8d63-7eed8ba8ba13.png)

**Comment by Hello-Linux** [comment]
- name: Synchronization of src on delegate host to dest on the current inventory host.
  synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: delegate.host

**Comment by weilinqwe** [comment]
这是准备工作，在deploy节点上生成密钥和配置文件，到时create master和node节点的时候会下发下去的
