### ISSUE TITLE
dashboard无法安装成功

### ISSUE THREAD

**Issue by dennis0721** [gjmzj/kubeasz#338]
kubeasz版本：kubeasz-0.3.1.tar.gz
k8s版本：k8s.1-11-3.tar.gz
基础镜像包版本：basic_images_kubeasz_0.3.tar.gz

问题：
执行 “cluster-addon : 获取dashboard离线镜像推送情况” task时会卡住
<img width="790" alt="wx20181010-224344 2x" src="https://user-images.githubusercontent.com/23226155/46744602-0bf1c480-ccde-11e8-87da-d5a8f1abad4b.png">

**Comment by gjmzj** [comment]
手动安装试一下，在deploy节点 `kubectl apply -f /etc/ansible/manifests/dashboard/`

**Comment by dennis0721** [comment]
> 手动安装试一下，在deploy节点 `kubectl apply -f /etc/ansible/manifests/dashboard/`

好的，我试一下，我之前是删除dashboard相关的资源，然后用yml重新创建，也不行，不是用的这种文件夹的方式

**Comment by dennis0721** [comment]
还是无法安装成功，k8s换成1.9.10安装成功
