### ISSUE TITLE
can't extend the node if that is ubuntu 14.04 version. 

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#34]
Hi , 
I tried to run the 20.addnode.yml for extend the additional node server but it is fail. 
since the ubuntu 14.04 no systemd/systemctl services by default . so I can't not enable calico service through the command "systemctl daemon-reload && systemctl enable calico-node && systemctl restart calico-node"

may I know how to fix this issue for ubuntu 14.04 version ? 

thanks so much !

**Comment by gjmzj** [comment]
比较好奇如果你没处理好 `systemd`问题，那么你集群本身就没起来，更谈不上增加`node`的问题；
没有研究过ubuntu14.04的up-start启动机制，sorry!

**Comment by evenye** [comment]
@gjmzj all the cluster server using the ubuntu 16.04 but we want to use another node with is ubuntu 14.04 specifically . 
thanks again.
