### ISSUE TITLE
如何更改k8s节点中的IP

### ISSUE THREAD

**Issue by 5m1** [gjmzj/kubeasz#345]
目前由于服务器需要迁移至新的网络中，网段的话需要更改，不知道有没有什么办法能够在不破坏当前cluster的情况下更改各节点中的IP地址呢？先多谢帮忙考虑！

**Comment by gjmzj** [comment]
这个理论上可以操作，不过很麻烦，感觉还是重建方便。。。
思路可以参考如下：（不建议在生产环境操作）
1.在新网段找服务器加入旧集群（新增新node）
2.通过kubectl cordon/ kubectl drain 操作，迁移旧服务器容器到新服务器
3.通过项目中[更改集群VIP](https://github.com/gjmzj/kubeasz/blob/master/docs/op/ChangeVIP.md)操作尝试修改master节点

**Comment by 5m1** [comment]
抱歉一直在忙才看到大神的回复，非常感谢大神的思路，还是像您说的，最好还是重新部署，不然更改起来还是有点略复杂而且风险会大一些（半生产环境）。我们还是重新部署吧，再次感谢大神的回复！
