### ISSUE TITLE
如何修改master节点keepalive的VIP？

### ISSUE THREAD

**Issue by Zweib** [gjmzj/kubeasz#351]
hosts文件里写的master节点以及VIP为：
[kube-master]
172.16.33.11
172.16.33.12
MASTER_IP="172.16.33.11" (virtual ip)
现在想把vip改成172.16.33.19，于是去两台master节点上修改了/etc/keepalive/keepalive.conf修改了vip并重启keepalive。但是使用kubectl访问https://172.16.211.29:8443时，出现了
Unable 通connect通他和server: x509: Certificate is valid for 127.0.0.1, 172.16.33.11, 172.16.33.12, 10.68.0.1, not 172.16.33.19.
想请教一下需要重做哪一步的证书呢？
重新运行 ansible-playback 01.prepare.yml也不行

**Comment by gjmzj** [comment]
看你的hosts文件像是很早一起的版本，较新的版本里面我专门有个文档写更改vip的；https://github.com/gjmzj/kubeasz/blob/master/docs/op/ChangeVIP.md

**Comment by Zweib** [comment]
非常感谢！其实我就是想知道，是kubernetes.pem这个需要重新生成，限制了证书对那些地址是有效的。
