### ISSUE TITLE
内核使用最新版本4.19.1，无法加载nf_conntrack_ipv4模块

### ISSUE THREAD

**Issue by duanzhanling** [gjmzj/kubeasz#366]
内核使用最新版本4.19.1，无法加载nf_conntrack_ipv4模块

4.19.1最新版本的内核，nf_conntrack_ipv4已经修改为nf_conntrack。

可以参考这个issue：
https://github.com/coreos/bugs/issues/2518

**Comment by gjmzj** [comment]
感谢提醒，已在dev修改了 roles/prepare/tasks/common.yml 部分任务，做个workaround处理

**Comment by duanzhanling** [comment]
辛苦了，谢谢
