### ISSUE TITLE
master 节点高可用问题

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#37]
比如：
- name: 创建kube-scheduler的systemd unit文件
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service

**Comment by gjmzj** [comment]
是的，master高可用只需要代理 apiserver服务

**Comment by peterpijing** [comment]
1.apiserver,那其实三个master节点，同一时间只有一个节点的apiserver对外提供服务？active/standby
2.scheduler+controller-manager都是选主的形式提供服务？
3.scheduler+controller-manager也在三个master节点上都安装了，会不会出现选主失败的情况？
4.如果一个master节点挂了，另外两个master节点服务scheduler+controller-manager将如何进行选主？会不会出现选主失败？@gjmzj

**Comment by gjmzj** [comment]
1. 同一时间肯定是3个apiserver对外服务，原理可以参考 `docs/01-创建CA证书和环境配置.md`
``` text
keepalived与haproxy配合，实现master的高可用过程如下：
    1.keepalived利用vrrp协议生成一个虚拟地址(VIP)，正常情况下VIP存活在keepalive的主节点，当主节点故障时，VIP能够漂移到keepalived的备节点，保障VIP地址可用性。
    2.在keepalived的主备节点都配置相同haproxy负载配置，并且监听客户端请求在VIP的地址上，保障随时都有一个haproxy负载均衡在正常工作。并且keepalived启用对haproxy进程的存活检测，一旦主节点haproxy进程故障，VIP也能切换到备节点，从而让备节点的haproxy进行负载工作。
    3.在haproxy的配置中配置多个后端真实kube-apiserver的endpoints，并启用存活监测后端kube-apiserver，如果一个kube-apiserver故障，haproxy会将其剔除负载池。
```
2. scheduler+controller-manager 是否选主失败可以查看对应日志，官方文档就是这么实现的 `https://kubernetes.io/docs/admin/high-availability/`

**Comment by peterpijing** [comment]
嗯，我看到master节点上的controller-manager 服务都是写的本机master-ip。
这意思就是每一个客户端请求－>经过vip->再经过haproxy的配置中配置多个后端真实kube-apiserver的endpoints，并启用存活监测后端kube-apiserver-> 然后每台节点的scheduler和controller-manager监听本机的apiserver服务->发起调度和副本控制器请求？对吗？

controller-manager 的服务文件
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart={{ bin_dir }}/kube-controller-manager \
  --address=127.0.0.1 \
  --master=http://127.0.0.1:8080 \
  --allocate-node-cidrs=true \
  --service-cluster-ip-range={{ SERVICE_CIDR }} \
  --cluster-cidr={{ CLUSTER_CIDR }} \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file={{ ca_dir }}/ca.pem \
  --cluster-signing-key-file={{ ca_dir }}/ca-key.pem \
  --service-account-private-key-file={{ ca_dir }}/ca-key.pem \
  --root-ca-file={{ ca_dir }}/ca.pem \
  --leader-elect=true \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by gjmzj** [comment]
@peterpijing 对的
