### ISSUE TITLE
偶尔连不上kubernetes svc的错误

### ISSUE THREAD

**Issue by SmileSees** [gjmzj/kubeasz#379]
Hi @gjmzj , 我们现在在azure redhat上面遇到flannel 经常会重启的情况，一会儿running一会儿就重启，查看log时候发现 它获取kubernetes services timeout.
"Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-nxvm8': Get https://10.254.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-nxvm8: dial tcp 10.254.0.1:443: i/o timeout "

我看你的kubeasz-0.4.0 发布说明里面提到了 “修复 ipvs 模式下网络组件偶尔连不上kubernetes svc的错误”， 请问和这个有关系吗，具体是修改的哪里呢？我们用的是k8s 1.9.1, kubeasz 大概是v196-r1之前的版本。

**Comment by SmileSees** [comment]
现在执行 flannel 的task， 都不去install-cni 了， 然后ansible 还是会去删除 /etc/cni/net.d 里面的东西，就会导致kubelet 没有cni configuration file. 该怎么去debug呢？

**Comment by gjmzj** [comment]
1.kubeasz那个版本太老了，新的版本已经改动很多，如果是新集群建议都使用新版本
2.azure公有云上部署多主集群，要注意安全组问题和负载均衡问题，https://github.com/gjmzj/kubeasz/blob/master/docs/setup/kubeasz_on_public_cloud.md

**Comment by gjmzj** [comment]
3. 删除/etc/cni/net.d就是为了删除默认的cni插件，只要flannel安装成功，kubelet也就能够正常

**Comment by SmileSees** [comment]
Hi @gjmzj ， 1.由于一些原因我们不得不继续用现在的脚本。 
2. 我们azure上面还有一个centos的集群现在已经升级到了1.12.0-rc.1的版本，而且都可以正常运行，flannel，dashboard都没有问题。
3. 现在的问题出在azure redhat上面，我更改了ansible脚本里面的一些ansible_distribution成RedHat，之前是flannel至少是可以init 成功，现在在跑完flannel的ansible的脚本后，在删除/etc/cni/net.d/后，不会出现10-flannel.conflist，kubelet也就没有cni，pod也就不会有。

现在奇怪的是为什么跑完flannel的脚本后没有在/etc/cni/net.d/下面生成10-flannel.conflist？
（cluster-info 看master是running的，kubectl命令也可以用，etcd也是healthy的）。

**Comment by SmileSees** [comment]
大概已经解决了问题。
cloudprovider 这个问题是因为我们在kubelet里面多加了一个关于cloudprovider的flag。
然后flannel这边，设置了 
net.ipv4.ip_forward=1
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1

并且用的kubeproxy ipvs mode，现在可以运行了， 也能看到dashboard。
