### ISSUE TITLE
centos7.2 run error

### ISSUE THREAD

**Issue by aixj1984** [gjmzj/kubeasz#38]
TASK [prepare : 分发CA 证书] *****************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/etc/ansible/kubeasz/ca.pem
failed: [10.0.12.220] (item=ca.pem) => {"changed": false, "item": "ca.pem", "msg": "Could not find or access 'ca.pem'\nSearched in:\n\t/etc/ansible/kubeasz/roles/prepare/files/ca.pem\n\t/etc/ansible/kubeasz/roles/prepare/ca.pem\n\t/etc/ansible/kubeasz/roles/prepare/tasks/files/ca.pem\n\t/etc/ansible/kubeasz/roles/prepare/tasks/ca.pem\n\t/etc/ansible/kubeasz/files/ca.pem\n\t/etc/ansible/kubeasz/ca.pem"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/etc/ansible/kubeasz/ca-key.pem
failed: [10.0.12.220] (item=ca-key.pem) => {"changed": false, "item": "ca-key.pem", "msg": "Could not find or access 'ca-key.pem'\nSearched in:\n\t/etc/ansible/kubeasz/roles/prepare/files/ca-key.pem\n\t/etc/ansible/kubeasz/roles/prepare/ca-key.pem\n\t/etc/ansible/kubeasz/roles/prepare/tasks/files/ca-key.pem\n\t/etc/ansible/kubeasz/roles/prepare/tasks/ca-key.pem\n\t/etc/ansible/kubeasz/files/ca-key.pem\n\t/etc/ansible/kubeasz/ca-key.pem"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/etc/ansible/kubeasz/ca.csr
failed: [10.0.12.220] (item=ca.csr) => {"changed": false, "item": "ca.csr", "msg": "Could not find or access 'ca.csr'\nSearched in:\n\t/etc/ansible/kubeasz/roles/prepare/files/ca.csr\n\t/etc/ansible/kubeasz/roles/prepare/ca.csr\n\t/etc/ansible/kubeasz/roles/prepare/tasks/files/ca.csr\n\t/etc/ansible/kubeasz/roles/prepare/tasks/ca.csr\n\t/etc/ansible/kubeasz/files/ca.csr\n\t/etc/ansible/kubeasz/ca.csr"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/etc/ansible/kubeasz/ca-config.json
failed: [10.0.12.220] (item=ca-config.json) => {"changed": false, "item": "ca-config.json", "msg": "Could not find or access 'ca-config.json'\nSearched in:\n\t/etc/ansible/kubeasz/roles/prepare/files/ca-config.json\n\t/etc/ansible/kubeasz/roles/prepare/ca-config.json\n\t/etc/ansible/kubeasz/roles/prepare/tasks/files/ca-config.json\n\t/etc/ansible/kubeasz/roles/prepare/tasks/ca-config.json\n\t/etc/ansible/kubeasz/files/ca-config.json\n\t/etc/ansible/kubeasz/ca-config.json"}
	to retry, use: --limit @/etc/ansible/kubeasz/90.setup.retry

**Comment by aixj1984** [comment]
I user all in one.

**Comment by gjmzj** [comment]
确认下 `roles/prepare/tasks/files` 目录下有没有 CA证书
