### ISSUE TITLE
ansible-playbook 01.prepare.yml

### ISSUE THREAD

**Issue by bobo200128** [gjmzj/kubeasz#381]
这一步骤出错是因为啥

TASK [deploy : 生成 CA 证书和私钥] ***********************************************************************************************************************************************
fatal: [172.20.238.221]: FAILED! => {"changed": true, "cmd": "cd /etc/kubernetes/ssl && /opt/kube/bin/cfssl gencert -initca ca-csr.json | /opt/kube/bin/cfssljson -bare ca", "delta": "0:00:00.006366", "end": "2018-11-22 10:40:28.411119", "msg": "non-zero return code", "rc": 127, "start": "2018-11-22 10:40:28.404753", "stderr": "/bin/sh: /opt/kube/bin/cfssljson: No such file or directory\n/bin/sh: /opt/kube/bin/cfssl: No such file or directory", "stderr_lines": ["/bin/sh: /opt/kube/bin/cfssljson: No such file or directory", "/bin/sh: /opt/kube/bin/cfssl: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by duanzhanling** [comment]
看看创建目录这个playbook是否有问题，这个很明显是目录不存在导致的。
