### ISSUE TITLE
k8s(calico)外的服务器如何与k8s内的容器互相访问？

### ISSUE THREAD

**Issue by weilinqwe** [gjmzj/kubeasz#383]
目前我这边有个情况，硬件服务器与k8s集群混合部署，应用需要同时部署在硬件服务器和k8s集群的pod上，应用注册中心和应用网关部署在硬件服务器上， k8s中的应用pod需要用pod ip注册到注册中心，网关转发请求到应用pod上。
k8s使用calico（BGP），怎么配置才能实现？k8s外的硬件服务器能动态获取calico路由？ 是不是在硬件服务器上安装BGP agent？

**Comment by weilinqwe** [comment]
查看calico官方文档，有描述（各版本好像区别还挺大），群主calico3.1.3版本对应文档[Configuring BIRD as a BGP Route Reflector](https://docs.projectcalico.org/v3.1/usage/routereflector/bird-rr-config)。
 
因为网络设备无法控制，我设想用一台服务器做BGP reflector，集群内节点路由都注册到这个BGP reflector上，外部服务器从这个BGP reflector学到集群内的路由。

试验下来，这个BGP reflector的确拿到了集群内节点的路由，但都是unreachable。 不知道是不是因为集群内节点路由都是建立在tunl0上的， BGP reflector本机没有这个？ 还需进一步研究

**Comment by weilinqwe** [comment]
@jmgao1983 感觉calico用了IPIP，所以用到tunl0，以致于BGP reflector 收集到的路由unreachable，所以我把CALICO_IPV4POOL_IPIP改成off，然后执行change_k8s_network.yml重建了网络，但是为啥tunl0还在，路由都是通过tunl0的？
`5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 172.20.146.192/32 brd 172.20.146.192 scope global tunl0
       valid_lft forever preferred_lft forever
[root@cloudhost6 ~]# ip r
default via 10.18.0.254 dev ens37 proto dhcp metric 101 
10.18.0.0/20 dev ens37 proto kernel scope link src 10.18.14.79 metric 101 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.20.27.192/26 via 192.168.11.92 dev tunl0 proto bird onlink 
172.20.64.192/26 via 192.168.11.95 dev tunl0 proto bird onlink 
172.20.122.64/26 via 192.168.11.93 dev tunl0 proto bird onlink 
blackhole 172.20.146.192/26 proto bird 
172.20.146.207 dev cali4732593268f scope link 
172.20.146.208 dev calie2f012e6834 scope link 
172.20.146.209 dev cali387d35d7888 scope link 
172.20.146.210 dev cali68aadcb80c9 scope link 
172.20.146.211 dev cali92171e473cc scope link 
172.20.207.128/26 via 192.168.11.94 dev tunl0 proto bird onlink 
192.168.11.0/24 dev ens33 proto kernel scope link src 192.168.11.96 metric 100`

**Comment by gjmzj** [comment]
如果你节点数目不多，还可以在网关那边配置几条静态路由（节点POD网络的路由指向host地址）

**Comment by weilinqwe** [comment]
我想问的是：不用IPIP，应该用不到tunl0的吧？ 为啥我设成off了，还是通过tunl0?

**Comment by weilinqwe** [comment]
应该是change_k8s_network.yml里面 ip link del tunl0;不起作用（restart network也没生效）

**Comment by gjmzj** [comment]
这个我也没配置过，只能google或者对应项目里面提issue看看了，有些问题先记着，也许以后某天突然明白了:)

**Comment by pingod** [comment]
今天刚好实现你所说的场景，在这里分享下：https://www.notion.so/openvpn-k8s-0683b9fd18da419f9c3aa07d6e3ea145

简单的说就是通过openvpn+路由的方式
