### ISSUE TITLE
我kubeadm安装的k8s，想用本项目装harbor，会有冲突吗？

### ISSUE THREAD

**Issue by yuufnn** [gjmzj/kubeasz#385]
初步思路是想把ansible host文件改成和项目的host-s-master.yml一致，不知可否？
前提条件是啥？

**Comment by gjmzj** [comment]
可以的，目前项目支持harbor 1.5.2版本；
安装可以参考文档 https://github.com/gjmzj/kubeasz/blob/master/docs/guide/harbor.md
