### ISSUE TITLE
["mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory"]

### ISSUE THREAD

**Issue by crazy-canux** [gjmzj/kubeasz#389]
where can i find this file?

TASK [deploy : 移动 kube-proxy.kubeconfig] **********************************************************************************************************************
fatal: [10.103.239.40]: FAILED! => {"changed": true, "cmd": "mv /root/kube-proxy.kubeconfig /etc/kubernetes/", "delta": "0:00:00.005146", "end": "2018-11-29 22:46:05.203605", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-11-29 22:46:05.198459", "stderr": "mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory", "stderr_lines": ["mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by gjmzj** [comment]
这个是之前几个命令自动生成的

**Comment by crazy-canux** [comment]
可是为啥我前面没报错，说明生成成功了？ 可是没有这个文件？

TASK [deploy : 移动 kube-proxy.kubeconfig] *******************************************************************************************************************
fatal: [10.103.239.40]: FAILED! => {"changed": true, "cmd": "mv /root/kube-proxy.kubeconfig /etc/kubernetes/", "delta": "0:00:00.004107", "end": "2018-11-30 14:48:47.247405", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-11-30 14:48:47.243298", "stderr": "mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory", "stderr_lines": ["mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP *************************************************************************************************************************************************
10.103.238.16              : ok=1    changed=0    unreachable=0    failed=0
10.103.239.40              : ok=16   changed=10   unreachable=0    failed=1
10.103.239.90              : ok=1    changed=0    unreachable=0    failed=0
10.103.239.91              : ok=1    changed=0    unreachable=0    failed=0

**Comment by crazy-canux** [comment]
原来在/home/user/下面。

**Comment by xiuxiu** [comment]
遇到了一样的问题，最后只能通过手动拷贝来解决，感觉是不是脚本需要更新下。

**Comment by crazy-canux** [comment]
全程用root就好了
