### ISSUE TITLE
all in one 部署方式出现的问题

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#39]
哈喽
"msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true
我用all-in-one的方式部署的时候出现了认证问题，
一台机器部署,也需要在这台机器上执行以下步骤？
执行ssh-copy-id $IP #$IP为本虚机地址，按照提示输入yes 和root密码？

还需要本机对本机进行认证？@gjmzj

**Comment by gjmzj** [comment]
@peterpijing 是的，文档里面写清楚了啊，因为ansible通过ssh工作的

**Comment by peterpijing** [comment]
嗯，我是觉得所有的部署都在一台机器。自己还需要对自己认证，有点奇怪@gjmzj

**Comment by peterpijing** [comment]
我找了台机器试了一把，安装过程中报了两个错，all-in-one的安装方式
1.关闭selinux,这个错误应该可以忽略
ASK [prepare : 关闭 selinux] ***************************************************************************************
fatal: [192.168.12.125]: FAILED! => {"changed": true, "cmd": "setenforce 0 && echo SELINUX=disabled > /etc/selinux/config", "delta": "0:00:00.024115", "end": "2017-12-24 16:00:15.537752", "msg": "non-zero return code", "rc": 1, "start": "2017-12-24 16:00:15.513637", "stderr": "setenforce: SELinux is disabled", "stderr_lines": ["setenforce: SELinux is disabled"], "stdout": "", "stdout_lines": []}/

2.这个是什么原因了？？？这会导致本机做为node添加不成功@gjmzj
TASK [kube-node : approve-kubelet-csr] ****************************************************************************
fatal: [192.168.12.125]: FAILED! => {"changed": true, "cmd": "sleep 15 && /root/local/bin/kubectl get csr|grep 'Pending' | awk 'NR>0{print $1}'| xargs /root/local/bin/kubectl certificate approve", "delta": "0:00:15.232577", "end": "2017-12-24 16:01:39.488933", "msg": "non-zero return code", "rc": 123, "start": "2017-12-24 16:01:24.256356", "stderr": "No resources found.\nerror: one or more CSRs must be specified as <name> or -f <filename>", "stderr_lines": ["No resources found.", "error: one or more CSRs must be specified as <name> or -f <filename>"], "stdout": "", "stdout_lines": []}

**Comment by peterpijing** [comment]
已经找到原因了，环境不干净造成的，请忽略

**Comment by xnycool** [comment]
机器只是个工具，是不会思考的，只是按指令办事。
@peterpijing
