### ISSUE TITLE
always fail about install 05-kube-master.

### ISSUE THREAD

**Issue by crazy-canux** [gjmzj/kubeasz#390]
TASK [kube-node : 轮询等待kubelet启动] ***************************************************************************************************************************
FAILED - RETRYING: 轮询等待kubelet启动 (8 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (7 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (6 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (5 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).
fatal: [10.103.239.90]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.009951", "end": "2018-11-30 18:34:13.195136", "failed": true, "rc": 0, "start": "2018-11-30 18:34:13.185185", "stderr": "", "stderr_lines": [], "stdout": "   Active: activating (auto-restart) (Result: exit-code) since Fri 2018-11-30 18:34:10 CST; 2s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) since Fri 2018-11-30 18:34:10 CST; 2s ago"]}

PLAY RECAP *************************************************************************************************************************************************
10.103.239.90              : ok=30   changed=16   unreachable=0    failed=1

**Comment by crazy-canux** [comment]
fixed.

**Comment by dwgeneral** [comment]
how to fix it ?

**Comment by dwgeneral** [comment]
because I was using kubeadm install k8s, so there is the conflict,
delete this file 
/etc/systemd/system/kubelet.service.d
└─10-kubeadm.conf

and re-execute ansible-playbook
