### ISSUE TITLE
how to fix this? 

### ISSUE THREAD

**Issue by crazy-canux** [gjmzj/kubeasz#391]
TASK [flannel : 轮询等待flannel 运行，视下载镜像速度而定] *********************************************************************************************************************
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
changed: [10.103.239.90 -> 10.103.239.40]
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
fatal: [10.103.239.91 -> 10.103.239.40]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/opt/kube/bin/kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' 10.103.239.91 '|awk '{print $3}'", "delta": "0:00:00.130321", "end": "2018-12-02 18:24:33.492898", "failed": true, "rc": 0, "start": "2018-12-02 18:24:33.362577", "stderr": "", "stderr_lines": [], "stdout": "Init:0/1", "stdout_lines": ["Init:0/1"]}
fatal: [10.103.239.92 -> 10.103.239.40]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/opt/kube/bin/kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' 10.103.239.92 '|awk '{print $3}'", "delta": "0:00:00.135264", "end": "2018-12-02 18:24:33.605490", "failed": true, "rc": 0, "start": "2018-12-02 18:24:33.470226", "stderr": "", "stderr_lines": [], "stdout": "Init:0/1", "stdout_lines": ["Init:0/1"]}

**Comment by crazy-canux** [comment]
kube-flannel-ds-2695p                   1/1       Running             0          3h        10.103.239.90   10.103.239.90
kube-flannel-ds-48kcj                   0/1       Init:0/1            0          3h        10.103.239.91   10.103.239.91
kube-flannel-ds-vz6pc                   0/1       Init:0/1            0          3h        10.103.239.92   10.103.239.92

**Comment by crazy-canux** [comment]
请问这个下载的地方，可以先手动下载吗？

**Comment by crazy-canux** [comment]
fixed

**Comment by Leopan0** [comment]
为什么我还是这样

**Comment by tseegggg** [comment]
请问是如何解决的？
