### ISSUE TITLE
您好，请问centos6.5可以安装node节点吗

### ISSUE THREAD

**Issue by zhaop33** [gjmzj/kubeasz#392]
您好，请问centos6.5可以安装node节点吗

**Comment by weilinqwe** [comment]
应该不行的吧。centos6.5 内核只有2.6，默认docker好像要epel yum安装docker1.13. 群主的docker应该需要内核3.10以上

**Comment by zhaop33** [comment]
升级内核之后呢

**Comment by ilanni2460** [comment]
建议直接使用centos7，然后升级到最新版本内核
