### ISSUE TITLE
No resources found.

### ISSUE THREAD

**Issue by crazy-canux** [gjmzj/kubeasz#394]
＃kubectl get pods
No resources found.

＃get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   coredns-7ff9697f48-r8pf9                1/1       Running   0          19m
kube-system   coredns-7ff9697f48-rhxmk                1/1       Running   0          19m
kube-system   kube-flannel-ds-54m24                   1/1       Running   0          20m
kube-system   kube-flannel-ds-jsbpk                   1/1       Running   0          20m
kube-system   kube-flannel-ds-qwtdw                   1/1       Running   0          20m
kube-system   kubernetes-dashboard-8687984b47-ds9pd   1/1       Running   0          19m
kube-system   metrics-server-5d5ff7bb78-fwzvg         1/1       Running   0          19m

为什么 get pods 没资源啊？

**Comment by hanmomo** [comment]
因为默认的namespace是default，不是kube-system

**Comment by crazy-canux** [comment]
thx!
