### ISSUE TITLE
可以用ubuntu的lxd建立2个worke node，这样在一个虚拟机里更好

### ISSUE THREAD

**Issue by kitepad** [gjmzj/kubeasz#4]

**Comment by gjmzj** [comment]
抱歉没用过lxd，这个项目主要也是提供二进制部署思路，你可以改造它适应你熟悉的环境

**Comment by kitepad** [comment]
谢谢！也许这里的一些方法可以借鉴：https://github.com/IBM/deploy-ibm-cloud-private/。我在尝试将其修改为部署kubernetes，但是我是kubernetes，ansible，vagrant的新手，最头疼的问题是网络问题，看如何借鉴你的方法，把这些需要安装时下载的文件，变成本地化安装。
