### ISSUE TITLE
执行到开启etcd服务失败

### ISSUE THREAD

**Issue by ldd91** [gjmzj/kubeasz#404]
我是单主多节点部署的，执行ansible-playbook 90.setup.yaml执行到开启etcd的时候报错了，日志是这个有人有遇到过吗？
TASK [etcd : 开启etcd服务] *******************************************************************************************************************************************
fatal: [k8sv2master]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload && systemctl restart etcd", "delta": "0:00:00.074767", "end": "2018-12-12 11:41:01.660711", "msg": "non-zero return code", "rc": 1, "start": "2018-12-12 11:41:01.585944", "stderr": "Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}

PLAY RECAP *******************************************************************************************************************************************************
192.168.150.179            : ok=35   changed=14   unreachable=0    failed=0   
k8sv2master                : ok=25   changed=6    unreachable=0    failed=1   
k8sv2node1                 : ok=19   changed=5    unreachable=0    failed=0

**Comment by gjmzj** [comment]
查看具体失败日志 `journalctl -xe` 或者 `journalctl -u etcd -f`

**Comment by ldd91** [comment]
感谢及时回复，通过查看日志发现是因为hosts文件角色定义需要用IP不能用主机名，已解决 @gjmzj
