### ISSUE TITLE
新增一个node节点的flannel网络不通

### ISSUE THREAD

**Issue by liuwenzhi0318** [gjmzj/kubeasz#405]
在[new-node]
192.168.5.21
增加后，所在机器生产了一个flannel网段，但是这个网段只有本身机器能访问，其他的节点包括master都不能通信
如：在node节点上查看路由
[root@k8s_node003 ~]# route -n
... ...
172.20.5.0      0.0.0.0         255.255.255.0   U     0      0        0 cni0
... ...

在master上
[root@k8s-master001 network-scripts]# route -n 
... ...
172.20.5.0      172.20.5.0      255.255.255.0   UG    0      0        0 flannel.1
... ...
[root@k8s-master001 network-scripts]# ping 172.20.5.1
PING 172.20.5.1 (172.20.5.1) 56(84) bytes of data.

**Comment by liuwenzhi0318** [comment]
新增加两台node节点都是这个问题

**Comment by gjmzj** [comment]
是不是公有云的虚机，检查下新增节点的安全组设置有没有问题

**Comment by liuwenzhi0318** [comment]
是公有云的，新增的两台机器都是在同一网段。
[root@k8s-master001 api]# kubectl get pod --all-namespaces  -o wide |grep fla 
kube-system   kube-flannel-ds-8vxmm                                    1/1       Running   2          35d       192.168.5.15   192.168.5.15   <none>
kube-system   kube-flannel-ds-bs4vz                                    1/1       Running   1          35d       192.168.5.13   192.168.5.13   <none>
kube-system   kube-flannel-ds-kczrx                                    1/1       Running   4          35d       192.168.5.12   192.168.5.12   <none>
kube-system   kube-flannel-ds-lkhxt                                    1/1       Running   1          35d       192.168.5.14   192.168.5.14   <none>
kube-system   kube-flannel-ds-nntz4                                    1/1       Running   5          20h       192.168.5.10   192.168.5.10   <none>
kube-system   kube-flannel-ds-t9xvp                                    1/1       Running   3          3h        192.168.5.21   192.168.5.21   <none>


[root@k8s-master001 api]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.5.1     0.0.0.0         UG    100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.1.0      172.20.1.0      255.255.255.0   UG    0      0        0 flannel.1
172.20.2.0      172.20.2.0      255.255.255.0   UG    0      0        0 flannel.1
172.20.3.0      172.20.3.0      255.255.255.0   UG    0      0        0 flannel.1
172.20.4.0      172.20.4.0      255.255.255.0   UG    0      0        0 flannel.1
172.20.5.0      172.20.5.0      255.255.255.0   UG    0      0        0 flannel.1
192.168.2.0     0.0.0.0         255.255.255.0   U     101    0        0 eth1
192.168.5.0     0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.11.0    0.0.0.0         255.255.255.0   U     102    0        0 eth2
新增了一个192.168.5.10   对应 172.20.4.0
新增了一个192.168.5.21 对应 172.20.5.0

**Comment by liuwenzhi0318** [comment]
谢谢，解决了。是您说的那样
