### ISSUE TITLE
请教: kernel:unregister_netdevice: waiting for eth0 to become free. 

### ISSUE THREAD

**Issue by AEGQ** [gjmzj/kubeasz#408]
**现象：**

系统: centos7.5 
内核: 3.10.0-862 
操作: 删除长时间运行的pod 【删除 mysql redis traefik 都遇到过】
现象: 控制台频繁输出 kernel:unregister_netdevice: waiting for eth0 to become free. 
调研:  内核bug，需要升级内核

**请教:**

在此项目中未见有这个问题的讨论和建议。
所有想请教下，是否有未出现过此问题生产稳定的内核版本推荐使用，感谢  :)

**Comment by gjmzj** [comment]
我主要使用环境为 ubuntu 1604，倒真没有碰到过此bug；
不过centos自带的内核确实比较老，建议升级https://github.com/gjmzj/kubeasz/blob/master/docs/guide/kernel_upgrade.md
