### ISSUE TITLE
在进行第7步kube-node安装的时候，我的kubelet启动参数中添加了--fail-swap-on=false \   --logtostderr=true \   --v=2 这个swap的禁用，但是启动之后，还是报错error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename	

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#41]
1.kubelet service配置文件
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
#--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest
ExecStart=/root/local/bin/kubelet \
  --address=192.168.12.125 \
  --hostname-override=192.168.12.125 \
  --pod-infra-container-image=mirrorgooglecontainers/pause-amd64:3.0 \
  --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --cert-dir=/etc/kubernetes/ssl \
  --network-plugin=cni \
  --cni-conf-dir=/etc/cni/net.d \
  --cni-bin-dir=/root/local/bin \
  --cluster-dns=10.68.0.2 \
  --cluster-domain=cluster.local. \
  --hairpin-mode hairpin-veth \
  --allow-privileged=true \
  --fail-swap-on=false \
  --logtostderr=true \
  --v=2
#kubelet cAdvisor 默认在所有接口监听 4194 端口的请求, 以下iptables限制内网访问
ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT
ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
2.kubelet启动后日志输出
I1224 18:16:58.480975   23343 feature_gate.go:156] feature gates: map[]
I1224 18:16:58.481041   23343 controller.go:114] kubelet config controller: starting controller
I1224 18:16:58.481047   23343 controller.go:118] kubelet config controller: validating combination of defaults and flags
I1224 18:16:58.485590   23343 client.go:75] Connecting to docker on unix:///var/run/docker.sock
I1224 18:16:58.485616   23343 client.go:95] Start docker client with request timeout=2m0s
I1224 18:16:58.490521   23343 feature_gate.go:156] feature gates: map[]
W1224 18:16:58.490656   23343 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set explicitly
W1224 18:16:58.490684   23343 server.go:324] standalone mode, no API client
I1224 18:16:58.495607   23343 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/user.slice"
W1224 18:16:58.506257   23343 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
W1224 18:16:58.506380   23343 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
I1224 18:16:58.515926   23343 fs.go:139] Filesystem UUIDs: map[3067423f-69e6-46ce-8935-306bd637a39d:/dev/vda1 97cdcaff-a8e7-4ffe-84ac-722f528abba0:/dev/vda2 a46458ae-3165-48b6-a14a-2bcd29897389:/dev/vda3]
I1224 18:16:58.515947   23343 fs.go:140] Filesystem partitions: map[tmpfs:{mountpoint:/dev/shm major:0 minor:18 fsType:tmpfs blockSize:0} /dev/vda3:{mountpoint:/var/lib/docker/overlay major:253 minor:3 fsType:xfs blockSize:0} /dev/vda1:{mountpoint:/boot major:253 minor:1 fsType:xfs blockSize:0} shm:{mountpoint:/var/lib/docker/containers/6578f528ef25f02f60f593c9560019fa7b51ffc05490c17ad32a14cea587d6f4/shm major:0 minor:39 fsType:tmpfs blockSize:0}]
I1224 18:16:58.519260   23343 manager.go:216] Machine: {NumCores:4 CpuFrequency:2199998 MemoryCapacity:8203042816 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID:68fca30095d25e4cb832f3357e70b88a SystemUUID:DAD79F94-D5D2-4685-9E28-5B828EDF18CE BootID:7d868d39-2348-4606-963c-a4c812598ed1 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:18 Capacity:4101521408 Type:vfs Inodes:1001348 HasInodes:true} {Device:/dev/vda3 DeviceMajor:253 DeviceMinor:3 Capacity:164269654016 Type:vfs Inodes:160429824 HasInodes:true} {Device:/dev/vda1 DeviceMajor:253 DeviceMinor:1 Capacity:1063256064 Type:vfs Inodes:1048576 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:39 Capacity:67108864 Type:vfs Inodes:1001348 HasInodes:true}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:171798691840 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:52:57:00:00:36:bc Speed:0 Mtu:1500} {Name:tunl0 MacAddress:00:00:00:00 Speed:0 Mtu:1480}] Topology:[{Id:0 Memory:8589373440 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:1 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1224 18:16:58.520236   23343 manager.go:222] Version: {KernelVersion:3.10.0-327.36.3.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:17.09.1-ce DockerAPIVersion:1.32 CadvisorVersion: CadvisorRevision:}
W1224 18:16:58.521096   23343 server.go:232] No api server defined - no events will be sent to API server.
I1224 18:16:58.521111   23343 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename

**Comment by peterpijing** [comment]
上面的启动失败应该不会导致csr的问题吧？
[root@192.168.12.125  ansible]# kubectl get csr
No resources found.
但是现在这个资源找不到@gjmzj,会是什么原因导致生成不成功了？

**Comment by peterpijing** [comment]
还报找不到证书?这个证书是在第几步生成的呀？
Dec 24 18:40:15 wx-v81-152.hjidc.com kubelet[2793]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Dec 24 18:40:15 192.168.12.125 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Dec 24 18:40:15 192.168.12.125 systemd[1]: Unit kubelet.service entered failed state.
Dec 24 18:40:15 192.168.12.125 systemd[1]: kubelet.service failed.

**Comment by peterpijing** [comment]
还报找不到证书?这个证书是在第几步生成的呀？
Dec 24 18:40:15 192.168.12.125 kubelet[2793]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Dec 24 18:40:15 192.168.12.125 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Dec 24 18:40:15 192.168.12.125 systemd[1]: Unit kubelet.service entered failed state.
Dec 24 18:40:15 192.168.12.125 systemd[1]: kubelet.service failed.

**Comment by peterpijing** [comment]
已经找到原因了，环境不干净造成的，请忽略

**Comment by SmileSees** [comment]
@peterpijing 你的环境不干净的问题指的是什么呢？我遇到同样的问题，不过我是在Redhat上面部署的。
