### ISSUE TITLE
如何使用hostname作为集群的nodename

### ISSUE THREAD

**Issue by Abelief** [gjmzj/kubeasz#418]
默认使用的是节点IP，请问想使用hostname作为集群的nodename时如何操作？
如图：
![tim 20181219204906](https://user-images.githubusercontent.com/45996498/50221288-9dad3a80-03cf-11e9-9f8f-ef70a91b40b1.png)

我当前的做法是修改ansible hosts 文件，在[kube-master]  [kube-node]处填写hostname，而非节点ip地址。
但是执行部署指令后，kubelet和kube-proxy无法启动，节点无法创建。
报错如下：
kubelet
![tim 20181219205602](https://user-images.githubusercontent.com/45996498/50221585-8ae73580-03d0-11e9-97ae-b9a0b3bc9745.png)
kube-proxy
![tim 20181219205730](https://user-images.githubusercontent.com/45996498/50221641-c5e96900-03d0-11e9-86b2-8852efac6412.png)

谢谢！

**Comment by gameover453** [comment]
address需要指定绑定ip, 绑定hostname不生效

我是这样做的
部署前:
修改模板文件kubelet.service.j2 将原来的--hostname-override=替换为{{ ansible_hostname | lower }}
部署后即是主机名显示

部署后:
修改kubelet.service配置文件中的--hostname-override=到你想要的名称,重启kubelet
有可能需要重新加入集群,加入后即可正确工作

**Comment by gameover453** [comment]
另外 , hostname-override的参数必须是合法的FQDN名称
否则kubelet无法启动

**Comment by 740355215** [comment]
> 另外 , hostname-override的参数必须是合法的FQDN名称
> 否则kubelet无法启动

实践了下，修改模板文件kubelet.service.j2 将原来的--hostname-override=替换为{{ ansible_hostname | lower }} 后重启，
Kubelet 配置不太对，cluster role 还是之前的ip 配置，可能有哪里需要同步修改配置下

**Comment by 740355215** [comment]
我这边配置后，重新安装集群，Kubelet 报 ： can only access CSINode with the same name as the requesting node
