### ISSUE TITLE
关于node节点增加问题。亲，如果要增加node节点，只需要修改hosts中的new-node？然后执行ansible-playbook 20.addnode.yaml吗？

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#42]
[new-node]
#192.168.1.xx NODE_ID=node6 NODE_IP="192.168.1.xx"
#192.168.1.xx NODE_ID=node7 NODE_IP="192.168.1.xx"

ansible-playbook 20.addnode.yaml

@gjmzj

**Comment by gjmzj** [comment]
是的

**Comment by peterpijing** [comment]
请问你们在生产环境跑了多长时间啦？上生产有没有注意的地方或者是网络上的坑?@gjmzj

**Comment by DiamondYuan** [comment]
@peterpijing  我也在安装k8s 有没有什么联系方式。我们可以交流一下

**Comment by peterpijing** [comment]
把你联系方式给我，我加你@DiamondYuan

**Comment by DiamondYuan** [comment]
邮件 admin@diamondyuan.com

**Comment by xnycool** [comment]
用这个方案安装很容易就起来了。
