### ISSUE TITLE
在pre环节中，有关yum或者apt-get时，添加代理的建议

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#421]
在pre环节中，有关yum或者apt-get时，添加代理的建议

现在再部署node节点时，有部分node是不能直接连接外网的，但是公司内部有代理服务器，建议在pre阶段增加代理服务器的功能。

**Comment by gjmzj** [comment]
yum和apt的相关配置跟实际环境关联大，比如有的使用mirror站点，有的自建内网源，暂时不考虑集成这部分配置；不过欢迎提PR:)

**Comment by ilanni2460** [comment]
ok，这块确实比较复杂
