### ISSUE TITLE
建议删除coredns的部署模版中loop选项

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#423]
建议删除coredns的部署模版中loop选项

loop会寻找node节点的dns服务器作为pod节点的上游服务器，但是这个会偶然导致coredns无法正常启动。

建议删除
https://github.com/gjmzj/kubeasz/blob/master/roles/cluster-addon/templates/coredns.yaml.j2 文件中的loop选项

**Comment by gjmzj** [comment]
刚去查看了coredns的文档，loop插件还是有点作用的 https://coredns.io/plugins/loop/
它可以防止特定配置下潜在的dns查询死循环（内存泄漏）；
如果因为loop导致coredns启动不了，一般是由于/etc/resolv.conf配置有问题，注意排查即可。

**Comment by ilanni2460** [comment]
这个是会偶偶发的，我先暂时关闭

**Comment by pingod** [comment]
我今天在我的Ubuntu 18.04上也发现了这个问题，我手动将上游服务器地址写入/etc/resolv.conf,然后重启就好了。但是奇怪的是重启coredns pod 后，我写入的配置丢失了，但是pod还是起来了。

具体可以看下这篇博客：
https://blog.csdn.net/zhangxiangui40542/article/details/85016266

这个问题在github上也有人反馈：
https://github.com/coredns/coredns/issues/1647
