### ISSUE TITLE
百度网盘有新的地址么，页面不存在了。

### ISSUE THREAD

**Issue by LiuYuanZhe** [gjmzj/kubeasz#424]
第一次搭建，公司又是内网，所以只能先下好了，能再给个地址么。

**Comment by c050226113** [comment]
`
$a = 1;
$b = 2;
`

**Comment by penghu2** [comment]
这个问题解决了么，有新地址么

**Comment by LiuYuanZhe** [comment]
> 这个问题解决了么，有新地址么

有了，那个可以下载

**Comment by penghu2** [comment]
> > 这个问题解决了么，有新地址么
> 
> 有了，那个可以下载

哪个地址，方便发出来么
