### ISSUE TITLE
集群 DNS 域名命名  "cluster.local." 

### ISSUE THREAD

**Issue by AEGQ** [gjmzj/kubeasz#427]
有个疑惑：
 
> ”cluster.local.“ 

请问 最后的点有特别的作用么，如果没有是不是可以去掉 ？

**Comment by gjmzj** [comment]
好像就是这个格式而已

**Comment by AEGQ** [comment]
只是发现 kubeadm默认是 cluster.local ，以为加点有什么特别的用处。

参考:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
