### ISSUE TITLE
docker存储目录key(graph)已弃用，请更新

### ISSUE THREAD

**Issue by mogu1986** [gjmzj/kubeasz#428]
daemon.json 

key : graph 新的为 data-root

level=warning msg="The \"graph\" config file option is deprecated. Please use \"data-root\" instead

**Comment by gjmzj** [comment]
不知道是哪个版本开始改变的？

**Comment by AEGQ** [comment]
@mogu1986  我之前也提过这个问题，可以改成data-root，graph也还可以用。

参考:
https://github.com/gjmzj/kubeasz/pull/305#issuecomment-419821002 
https://github.com/moby/moby/issues/3127#issuecomment-311123927

**Comment by gjmzj** [comment]
那暂时先不改吧，为了可以兼容之前的docker版本

**Comment by liupeng0518** [comment]
Will it now supports docker 1.13?  thanks!
