### ISSUE TITLE
Pod-network有好几种，建议在脚本里可以选择需要的一种。

### ISSUE THREAD

**Issue by xnycool** [gjmzj/kubeasz#43]
Calico、Canal、Flannel、Romana、Weave Net。
@gjmzj

**Comment by gjmzj** [comment]
近期尝试整合flannel和calico，并供使用者选择

**Comment by EamonZhang** [comment]
这个给力，丰富些应用的yaml 也很好，比如Jenkins

**Comment by evenye** [comment]
请问flannel和calico之间各有什么优势吗？
