### ISSUE TITLE
centos下用root用户尝试ALLinONE模式进行安装的问题

### ISSUE THREAD

**Issue by xuzhenen** [gjmzj/kubeasz#433]
按照快速指南：https://github.com/gjmzj/kubeasz/blob/master/docs/setup/quickStart.md

尝试用ALLinONE模式进行安装。修改了hosts文件中的如下建值

# 集群部署节点：一般为运行ansible 脚本的节点
# 变量 NTP_ENABLED (=yes/no) 设置集群是否安装 chrony 时间同步
[deploy]
11.239.164.9 NTP_ENABLED=no

# etcd集群请提供如下NODE_NAME，注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
11.239.164.9 NODE_NAME=etcd1

[kube-master]
11.239.164.9
[kube-node]
11.239.164.9

在centos的root用户下执行 ansible-playbook 90.setup.yml，出现了如下错误

PLAY [all] ************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
fatal: [11.239.164.9]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"11.239.164.9\". Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP ************************************************************************************************************************************
11.239.164.9               : ok=0    changed=0    unreachable=1    failed=0

但是实际上ssh 11.239.164.9 是可以输入密码完成登录的。

请问这是什么原因？

**Comment by xuzhenen** [comment]
已经解决。发现是root用户没有正确生成/root/.ssh/id_rsa文件导致。

**Comment by waitingsong** [comment]
请教下， id_rsa 这个文件名是否可配置，或者说是否只支持 rsa 证书而不支持  id_ed25519 这种 ecc 证书？
