### ISSUE TITLE
针对文件编写过程中的空白符问题

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#437]
目前我发现很多github项目中都有这个习惯,编写文件或者程序过程中都会有很多的空白符,建议去掉这样文件看着更加整洁美观,这个只是我的小小建议呦 哈哈
![1](https://user-images.githubusercontent.com/17851645/50954952-d03fe400-14f2-11e9-98a7-e354595de89f.png)
![2](https://user-images.githubusercontent.com/17851645/50954959-d635c500-14f2-11e9-8c3a-e525a46a7145.png)

**Comment by gjmzj** [comment]
哈哈，赞一下你的强迫症，以后会注意的！

**Comment by Hello-Linux** [comment]
看好你呦
