### ISSUE TITLE
无法拉取镜像

### ISSUE THREAD

**Issue by ydzhao-reyes** [gjmzj/kubeasz#438]
新制作的docker镜像，docker可以运行，k8s显示无法拉取镜像。

**Comment by gjmzj** [comment]
新制作的镜像你上传到本地仓库，还是上传到docker.hub上了？k8s不存在无法拉取镜像问题吧

**Comment by ilanni2460** [comment]
错误信息贴出来

**Comment by ydzhao-reyes** [comment]
> 错误信息贴出来
是我的私有仓库配置的不对
