### ISSUE TITLE
集群所有的物理机IP地址改变后无法运行cluster

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#44]
@gjmzj 
请教一下,我组成的cluster集群用的是 10.10.10.xx 这次IP地址给物理机. 
今天我尝试将所有的物理机地址改为另外一个网段:  172.10.10.x ,,修改/etc/ansible/hosts内容然后再执行

ansible-playbook 99.clean.yml
ansible-playbook 90.setup.yml

最后发现运行状态不正常. 
kubectl get cs       
Unable to connect to the server: dial tcp 172.10.200:8443: getsockopt: no route to host
journalctl -n 50
看到它仍在找旧的IP服务器.
docker[1472]: bird: BGP: Unexpected connect from unknown address 10.10.10.84 (port 52815)

请问我除了重装系统之外还有办法修复这个问题吗? 

谢谢了!!!

**Comment by gjmzj** [comment]
`ansible-playbook 99.clean.yml` 这个脚本在你修改ip之前运行，
`ansible-playbook 90.setup.yml` 这个脚本在修改ip之后运行

**Comment by evenye** [comment]
@gjmzj  谢谢，可能是我忘记在修改之前运行 99.clean.yml 了，直接就修改了新的IP，现在回不去原来的环境了。 
在新的IP地址下运行 99.clean.yml 似乎并没有帮助。请问我还能手动清除吗？ 

再次感谢！

**Comment by gjmzj** [comment]
没关系啊，只要你还记得之前的ip，把hosts文件改回原来ip，然后再补充执行一把 99.clean.yml就行了

**Comment by evenye** [comment]
@gjmzj 真被我弄乱了。我那几台机器主机名换了，然后IP地址也随意换了。 现在很难恢复当初哪个IP对应哪台主机。。。。。
，我能不能手动把一些信息直接从主机上清除呢？

**Comment by gjmzj** [comment]
hosts文件中每个组把可能地址都填上，反正清除，多添一些没事，比如
``` bash
[deploy]
192.168.1.1
192.168.1.2
192.168.1.3
...
[etcd]
192.168.1.1
192.168.1.2
192.168.1.3
...
[kube-master]
192.168.1.1
192.168.1.2
192.168.1.3
...
[kube-node]
192.168.1.1
192.168.1.2
192.168.1.3
...
```

**Comment by evenye** [comment]
@gjmzj 谢谢您的提醒,我也按这个方法反复清除多次了.看起来仍然不行. 
我在ansible中修改了BASIC_AUTH_PASS的密码. 然后[kube-node]换了另外三台node节点.  , 最后bin_dir="/opt/local/bin"这里也改了. 请问这有关系吗? 

如果没有关系的话,我只能重装系统了.

**Comment by gjmzj** [comment]
这两个参数肯定没关系，你要不还是重装下吧，多装几次也就熟悉了，重装注意下载最新的代码，并从`example`目录下使用新模板配置hosts文件

**Comment by evenye** [comment]
好吧.只能重装了.谢谢!!!

**Comment by xnycool** [comment]
如果用虚拟机安装建议多打快照。
