### ISSUE TITLE
你的kube-master上为啥要安装kube-node的组件呢？

### ISSUE THREAD

**Issue by Hello-Linux** [gjmzj/kubeasz#441]
![error](https://user-images.githubusercontent.com/17851645/51108914-8dea1000-182e-11e9-98c0-9bb8d0dc35f1.png)

**Comment by gjmzj** [comment]
因为kube-master 上也要运行网络等daemonset pod；比如flannel或者calico-node，如果一定不安装的话，确实也不会有大问题，但是从master节点与业务pod不通了。

**Comment by Hello-Linux** [comment]
ok
