### ISSUE TITLE
部署好prometheus并配置邮件报警后。当规则触发时，无法发邮件

### ISSUE THREAD

**Issue by snowman990** [gjmzj/kubeasz#448]
您好，我部署好prometheus并配置邮件报警后。当规则触发时，无法发邮件。排查报错过程如下。
尝试修改了几次都不行，麻烦看下是什么原因能，谢谢了！
---
当前配置如下：
    ]#cat manifests/prometheus/prom-alertsmanager.yaml
    alertmanagerFiles:
      alertmanager.yml:
        global:
          smtp_smarthost: 'smtp.qiye.163.com:465'
          smtp_from: 'aaa@aaa.com'
          smtp_auth_username: 'aaa@aaa.com'
          smtp_auth_password: 'xxxxxx'
          smtp_require_tls: true

        route:
          group_by: ['alertname', 'pod_name']
          group_wait: 10s
          group_interval: 5m
          receiver: AlertMail
          repeat_interval: 3h

        receivers:
        - name: 'AlertMail'
          email_configs:
          - to: 'tomcat@aaa.com'
          
查看相应日志报错如下：
    ]# kubectl logs --namespace=monitoring --all-containers=true  -f pod/monitor-prometheus-alertmanager-67dd877d66-8gsk7
    level=error ts=2019-01-26T05:17:38.807255689Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="require_tls: true (default), but \"smtp.qiye.163.com:465\" does not advertise the STARTTLS extension"
---           
尝试修修改配置如下:==>关闭smtp_require_tls
    ]#cat manifests/prometheus/prom-alertsmanager.yaml
    alertmanagerFiles:
      alertmanager.yml:
        global:
          smtp_smarthost: 'smtp.qiye.163.com:465'
          smtp_from: 'aaa@aaa.com'
          smtp_auth_username: 'aaa@aaa.com'
          smtp_auth_password: 'xxxxxx'
          smtp_require_tls: false

        route:
          group_by: ['alertname', 'pod_name']
          group_wait: 10s
          group_interval: 5m
          receiver: AlertMail
          repeat_interval: 3h

        receivers:
        - name: 'AlertMail'
          email_configs:
          - to: 'tomcat@aaa.com'
再次查看报错如下
    ]# kubectl logs --namespace=monitoring --all-containers=true  -f pod/monitor-prometheus-alertmanager-67dd877d66-8gsk7
    level=error ts=2019-01-26T06:36:20.195287695Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="*smtp.plainAuth failed: wrong host name"
    level=error ts=2019-01-26T06:36:20.195418142Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="*smtp.plainAuth failed: wrong host name"

---
尝试修复，修改配置如下：==>设置smtp端口是25
        ]#cat manifests/prometheus/prom-alertsmanager.yaml
        alertmanagerFiles:
          alertmanager.yml:
            global:
              smtp_smarthost: 'smtp.qiye.163.com:25'
              smtp_from: 'aaa@aaa.com'
              smtp_auth_username: 'aaa@aaa.com'
              smtp_auth_password: 'xxxxxx'
              smtp_require_tls: false

            route:
              group_by: ['alertname', 'pod_name']
              group_wait: 10s
              group_interval: 5m
              receiver: AlertMail
              repeat_interval: 3h

            receivers:
            - name: 'AlertMail'
              email_configs:
              - to: 'tomcat@aaa.com'
              
再次查看报错如下：
    ]# kubectl logs --namespace=monitoring --all-containers=true  -f pod/monitor-prometheus-alertmanager-67dd877d66-8gsk7
        level=error ts=2019-01-26T06:21:59.062483579Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="*smtp.plainAuth failed: unencrypted connection"
        level=error ts=2019-01-26T06:21:59.062634843Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="*smtp.plainAuth failed: unencrypted connection"

**Comment by marksugar** [comment]
@snowman990 

你是否应该确认下你的alertsmanager是否能够正常上网

**Comment by snowman990** [comment]
@gjmzj 补充，是我们自己用的网易的企业邮箱，非自己搭建。但其他软件配置是可以发的。配置的是25端口。但这里配置25端口就提示被安全连接。

**Comment by snowman990** [comment]
@marksugar 感谢。您说的是容器是否可以上网吗，我按如下方法试了些，可以，不知道是否有误：
]# kubectl exec monitor-prometheus-alertmanager-67dd877d66-m29pv -c prometheus-alertmanager --namespace=monitoring ping g.cn
PING g.cn (203.208.50.55): 56 data bytes
64 bytes from 203.208.50.55: seq=0 ttl=114 time=32.016 ms
64 bytes from 203.208.50.55: seq=1 ttl=114 time=31.233 ms
64 bytes from 203.208.50.55: seq=2 ttl=114 time=31.566 ms
64 bytes from 203.208.50.55: seq=3 ttl=114 time=31.246 ms

**Comment by marksugar** [comment]
@snowman990  hello ，朋友，我并没有使用邮箱，不过，我搜索了这个问题

`'smtp.qiye.163.com:587'` 有没有尝试过，如果没有，请尝试下。

另外，你或许应该尝试下腾讯或者阿里的邮箱。
可参考：
```
https://github.com/prometheus/alertmanager/issues/980
https://github.com/prometheus/alertmanager/issues/1378
```

**Comment by gjmzj** [comment]
@snowman990 刚测试了我普通的163邮箱可以发送告警邮件：
```
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'jxxxx@163.com'
      smtp_auth_username: 'jxxxx@163.com'
      smtp_auth_password: '*********'
      smtp_require_tls: false
```

**Comment by snowman990** [comment]
> @snowman990 hello ，朋友，我并没有使用邮箱，不过，我搜索了这个问题
> 
> `'smtp.qiye.163.com:587'` 有没有尝试过，如果没有，请尝试下。
> 
> 另外，你或许应该尝试下腾讯或者阿里的邮箱。
> 可参考：
> 
> ```
> https://github.com/prometheus/alertmanager/issues/980
> https://github.com/prometheus/alertmanager/issues/1378
> ```
> 希望对你有用


多谢，我再找找其他方法试试！

**Comment by snowman990** [comment]
> @ snowman990刚测试了我个人的普通163邮箱可以发送告警邮件：
> 
> ```
>       smtp_smarthost: 'smtp.163.com:25'
>       smtp_from: 'jxxxx@163.com'
>       smtp_auth_username: 'jxxxx@163.com'
>       smtp_auth_password: '*********'
>       smtp_require_tls: false
> ```


谢谢作者大大，我是用公司的企业邮箱的，之后我再使用自己的163邮箱试试。

**Comment by sunnoy** [comment]
腾讯企业邮箱推荐配置，本人已经测试通过

- 使用端口 587
- 开启客户端专用密码

配置

```yaml
global:
  smtp_smarthost: 'smtp.exmail.qq.com:587'
  smtp_from: '##'
  smtp_auth_username: '##'
  smtp_auth_password: '##'
  smtp_require_tls: true
```

如果没有配置客户端专用密码，会报错

```bash
evel=error ts=2019-04-30T06:33:39.542678243Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="sending mail from: 501 ϵͳ\ufffd\ufffdǿ\ufffdƿ\ufffd\ufffd\ufffd\ufffdʺ\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdã\ufffd\ufffd\ufffd\ufffd\ufffd¼exmail.qq.com\ufffd\ufffd\ufffd\ufffd΢\ufffd\ufffd "
```

如果使用465 会报错

```bash
level=error ts=2019-04-30T06:35:35.13402723Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="require_tls: true (default), but \"smtp.exmail.qq.com:465\" does not advertise the STARTTLS extension"
level=error ts=2019-04-30T06:35:35.134092599Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="require_tls: true (default), but \"smtp.exmail.qq.com:465\" does not advertise the STARTTLS extension"
```
关于端口 465 和 587

- 587是STARTTLS协议的 属于TLS通讯协议 只是他是在STARTTLS命令执行后才对之后的原文进行保护。
- 465端口是为SMTPS（SMTP-over-SSL）协议服务。alert需要使用587端口，走的STARTTLS协议

**Comment by hackerain** [comment]
腾讯企业邮箱，我发现没有开启客户端专用密码，也可以发送成功，只是把端口改成587了。
