### ISSUE TITLE
elasticsearch-logging pod内存占用过大

### ISSUE THREAD

**Issue by neo-feng** [gjmzj/kubeasz#454]
昨天刚刚部署一个新的集群，并且部署了efk(动态pv)， 发现elasticsearch-logging内存占用高达2.3G，查看代码， es-statefulset.yaml中并没有做内存limit设置。
我现在想设置memory limit为500M，请教一下 这样做会不会有风险？ 比如导致efk运作不畅

**Comment by gjmzj** [comment]
java 应用确实费内存，可以尝试限制一些，如果发现运行不顺畅就调大一些吧:)

**Comment by neo-feng** [comment]
多谢回复 下午查了一下 是个已知问题 https://github.com/kubernetes/kubernetes/issues/13051 https://github.com/kubernetes/kubernetes/pull/10653#issue-92503401。
目前的方案就设个limit 然后爆了让他重启。。。
