### ISSUE TITLE
更改hosts文件中ca_dir="/etc/kubernetes/ssl"设置导致kube-node执行失败

### ISSUE THREAD

**Issue by neo-feng** [gjmzj/kubeasz#455]
一开始把hosts中的ca_dir 改为/opt/kubernetes/ssl, 运行到kube-nodes.yml时 报错 说/etc/kubernetes 文件夹不存在， 改为默认设置 从头执行 顺利执行完毕。
可能是kube-node准备文件夹的时候并没有创建这个文件夹， 直接使用了ca证书创建时的文件夹，默认设置改掉以后ca证书不再创建/etc/kubernetes 导致错误

**Comment by gjmzj** [comment]
确实，这个参数 ca_dir 目前只能使用默认值，请不要修改
