### ISSUE TITLE
使用Ubuntu16.04部署muti-master在第二步出错

### ISSUE THREAD

**Issue by DanceKiddle** [gjmzj/kubeasz#458]
环境：ubuntu16.04 
          hosts文件主要部分：
          [deploy]
          192.168.168.160 NTP_ENABLED=no
          [kube-master]
          192.168.168.160
          192.168.168.161
          [lb]
          192.168.168.160 LB_ROLE=backup
          192.168.168.161 LB_ROLE=master
          [kube-node]
          192.168.168.162
          192.168.168.163

问题描述：
依照教程在执行完ansible-playbook 01-prepare.yml后，发现第一个master节点(192.168.168.160)ping第二个master节点(192.168.168.161)无法ping通，反过来却可以，其它节点也都正常。导致后续安装过程无法正常执行。请教各位该如何解决？

**Comment by gjmzj** [comment]
后面的 MASTER_IP 你配置了什么地址？
160/161两台机器上执行以下命令看看：
```
ip a
ip route
```

**Comment by DanceKiddle** [comment]
> 后面的 MASTER_IP 你配置了什么地址？
> 160/161两台机器上执行以下命令看看：
> 
> ```
> ip a
> ip route
> ```

MASTER_IP配置的192.168.168.160

**_160:_**
### **~$ ip a**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8e:11:6f brd ff:ff:ff:ff:ff:ff
    inet 192.168.168.160/24 brd 192.168.168.0 scope global ens160
       valid_lft forever preferred_lft forever
    inet 192.168.168.160/32 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8e:116f/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:38:f6:61:74 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether be:f2:42:56:6f:70 brd ff:ff:ff:ff:ff:ff
    inet 172.20.2.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever

### ~$ ip route
default via 192.168.168.12 dev ens160 onlink 
169.254.0.0/16 dev ens160  scope link  metric 1000 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
172.20.0.0/24 via 172.20.0.0 dev flannel.1 onlink 
172.20.3.0/24 via 172.20.3.0 dev flannel.1 onlink 
192.168.168.0/24 dev ens160  proto kernel  scope link  src 192.168.168.160

**_161:_**

### # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8e:be:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.168.161/24 brd 192.168.168.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet 192.168.168.160/32 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8e:be88/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:5c:ad:7c:97 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether be:86:da:3e:8e:a8 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::bc86:daff:fe3e:8ea8/64 scope link 
       valid_lft forever preferred_lft forever

### # ip route
default via 192.168.168.12 dev ens160 onlink 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
172.20.2.0/24 via 172.20.2.0 dev flannel.1 onlink 
172.20.3.0/24 via 172.20.3.0 dev flannel.1 onlink 
192.168.168.0/24 dev ens160  proto kernel  scope link  src 192.168.168.161

难道是master配错了？只能配置为非160/161的？

**Comment by gjmzj** [comment]
多主集群，master地址是个虚拟地址（VIP），必须是一个同网段内未被使用的地址

**Comment by DanceKiddle** [comment]
> 多主集群，master地址是个虚拟地址（VIP），必须是一个同网段内未被使用的地址

原来如此，多谢
