### ISSUE TITLE
多环境部署同一集群内存溢出问题

### ISSUE THREAD

**Issue by neo-feng** [gjmzj/kubeasz#459]
- 最近为开发测试环境搭建了一套kubernetes集群，3个环境dev/test/itg都部署在此集群中通过namespace隔离， 内存不是很宽裕 但调度合理的话也是够用的， 现在的情况是 总是往一台机器上拼命调度，导致内存超过95% 机器卡死 kubelet无响应。 
- 参考了kubernetes的资源管理和这个文章
 https://blog.csdn.net/liukuan73/article/details/82024085， kubelet加入下面配置：
```
 --enforce-node-allocatable=pods \
  --cgroup-driver=cgroupfs \
  --kube-reserved=cpu=200m,memory=1Gi,ephemeral-storage=2Gi \
  --system-reserved=cpu=200m,memory=1Gi,ephemeral-storage=2Gi \
  --eviction-hard=memory.available<1Gi,nodefs.available<10%
```

- 期待行为是
 给每个node预留3G内存，但貌似不管用， 没有给足3G的余量 极端情况下导致机器崩溃。
请教下 有没有此方面的经验或好的参考例子。

**Comment by gjmzj** [comment]
集群安装了metrics-server，或者heapster 可以自动平衡啊

**Comment by neo-feng** [comment]
调整了system-reserved的大小，调大了，目前比较稳定了，再观察观察。
需要调大的原因是 我的机器不光是给kubeneters用，所有这个system-reserved要留足
