### ISSUE TITLE
mac下使用vmware fusion可不可以搭建高可用的master-node集群呀

### ISSUE THREAD

**Issue by neatlife** [gjmzj/kubeasz#463]
云上服务器比较贵，如果本地网络啥的可以满足，开发的时候就使用本地的k8s集群，云上的用在生产环境上

**Comment by gjmzj** [comment]
mac 下的vmware fusion 不了解啊，既然本地是测试环境，那么单主多节点集群也可以满足了

**Comment by neatlife** [comment]
好的
