### ISSUE TITLE
node 节点crash后,cluster更新pods要很长时间.

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#47]
@gjmzj  请教一下大神,我的集群搭建好了后,做强行关机测试看看它的jobs会不会迅速切换到另外一个node上来. 

以dashboard服务为例,我在三台node节点都提前下载了它的image. 
我看到它当前运行在172.10.10.232上,所以我上去直接把这台机关机了. 
然后观察它切换到另外一台node要大约3 - 5分钟才切换到另外一台node过去.
请问这是怎么回事呢? 理论上我希望它在几秒钟就发现node异常并尽快切换任务到另外一台node上的.

谢谢!!

root@kuber-3:~# kubectl get pod -n kube-system -o wide
NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
calico-kube-controllers-86df6c7c86-g95gr   1/1       Running   0          1h        172.10.10.233   172.10.10.233
heapster-7b76dbf757-vbwpm                  1/1       Running   0          32m       172.20.127.194   172.10.10.233
kube-dns-54cff6c949-88hkz                  3/3       Running   0          34m       172.20.146.193   172.10.10.231
kubernetes-dashboard-5b9649685d-pnmjd      1/1       Running   0          14s       172.20.127.196   172.10.10.233
kubernetes-dashboard-5b9649685d-xwg7r      1/1       Unknown   0          6m        172.20.153.66    172.10.10.232
monitoring-grafana-64747d765f-nvhlg        1/1       Running   0          32m       172.20.146.194   172.10.10.231
monitoring-influxdb-7dd6654659-7mhd9       1/1       Running   0          32m       172.20.146.195   172.10.10.231

**Comment by gjmzj** [comment]
这个是集群本身的机制，可以参考这个 `http://docs.kubernetes.org.cn/304.html#Node_Controller`；
如果要手动维护某个node节点，使用`kubectl drain` 和 `kubectl cordon` 等命令操作，即可处理pod的迁移问题

**Comment by evenye** [comment]
@gjmzj 谢谢,似乎找不到什么参数可以调整加快速度的. 
我只是奇怪,它的设计中应该考虑到这点? 像docker swarm 只有一个node节点出问题, 几秒后集群就会将jobs转移. 而k8s居然要等这么久? 明显不合理的设计啊....

**Comment by gjmzj** [comment]
@evenye 可以使用参数调整，设计的理念不一样吧，master节点使用 `kube-controller-manager -v`查询参数，
``` bash
--node-monitor-grace-period=
--node-monitor-period=
--pod-eviction-timeout=
```

**Comment by evenye** [comment]
谢谢！ 原来有这些参数可以调整啊。 现在我懂了。谢谢您的指点！！ 我马上试试看。

**Comment by evenye** [comment]
@gjmzj 大神再问一个问题，
如果希望用master IP + Ports的方式来开放端口。 请问是否只需要将三台master安装kube-proxy就可以了呢？ 谢谢了！

**Comment by evenye** [comment]
kube-controller-manager --node-monitor-period=5s --node-monitor-grace-period=10s --pod-eviction-timeout=30s
I1227 11:40:29.956863   16308 controllermanager.go:109] Version: v1.8.6
W1227 11:40:29.957020   16308 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1227 11:40:29.957034   16308 client_config.go:534] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
invalid configuration: no configuration has been provided
