### ISSUE TITLE
新增节点后 kubectl logs 查看显示forbidden

### ISSUE THREAD

**Issue by neo-feng** [gjmzj/kubeasz#474]
你好，去年9月份使用kubeasz搭建了集群，上个月为了解决公有云问题更新kubeasz代码到最新，并新增了一个节点。
新节点看上去工作良好 -- pod正常分配，dashboard, kubeclt get node显示正常。
但是所有分配在新节点的pod 看log时(kubectl logs podname )会报错 -- Error from server (Forbidden): Forbidden (user=kubernetes, verb=get, resource=nodes, subresource=proxy) ( pods/log admin-service-89cc97fc4-nknc4)。

看到在以前一个issue里一条回复说这可能是 "老代码部署集群，新代码部署节点"导致。现在很难回滚到老代码了，请教下 这种情况有没有办法解决？ (让新节点正常log)

**Comment by neo-feng** [comment]
还有一个发现，该节点上fluentd 一直报错，error="Could not push logs to Elasticsearch after 2 retries. read timeout reached"。 几个节点放在同一个公有云安全组内，连通性应该没有问题

**Comment by gjmzj** [comment]
试试 git log 找到去年的提交点；然后用 git reset 回退。。。
去年有次较大安装流程优化，没法兼容老代码安装的集群

**Comment by neo-feng** [comment]
多谢回复。 有没有可能性使用最新代码把整个集群升级？ 环境down2个小时可以忍受
如果可以的话大体策略如何，有没有需要特别注意的地方？

**Comment by neo-feng** [comment]
完全重新部署了。碰到的一个问题是 clean的时候docker和network没有完全清掉 （原因是clean的playbook代码这块被注释掉了） 导致二次安装后flannel拿不到地址。 解注 重写执行clean 再安装就好了
