### ISSUE TITLE
看到只有两个节点的master，不能是3节点吗

### ISSUE THREAD

**Issue by Rmond** [gjmzj/kubeasz#48]
我之前了解的k8s的scheduler和controller-manager都是通过选举的方式产生leader的，2个节点要是网络原因不通了，不就脑裂了吗？有没有考虑node端用ng只是反向代理apiserver，也就不用配置ha和keepalived这么麻烦了

**Comment by gjmzj** [comment]
可以啊，用nginx反向代理和用ha代理效果一样的，关键你还得保障nginx的高可用，这不还是需要keepalived吗？ nginx+keepalived 或者 ha+keepalived都可以选择啊
scheduler和controller-manager就是选举产生leader的，网络故障是否脑裂，我觉得不一定，因为有etcd

**Comment by Rmond** [comment]
nginx的话每一个node上跑一个nginx的容器，不需要keepalived。etcd不是只是负责元信息的存储？如果就两个节点，还是会脑裂的啊，跟etcd的数量有关系吗，就算只有一个etcd，不是也可以跑master集群

**Comment by gjmzj** [comment]
@Rmond 你说的方式应该也可以实现apiserver高可用，哪个方便看情况了
scheduler和controller-manager选举产生leader的也是要靠apiserver的，它们的选主需要不停地从apiserver取得`lease`(有效期)，而apiserver靠etcd同步信息，这样只要etcd不脑裂，这两个组件不会出现这个问题，具体可以看官方文档 `https://kubernetes.io/docs/admin/high-availability/#master-elected-components`
