### ISSUE TITLE
关于release1.0.1 中提到的几条修复几点疑问

### ISSUE THREAD

**Issue by liupeng0518** [gjmzj/kubeasz#496]
优化journald日志服务配置，避免与syslog采集重复，节省节点资源

修复apiserver启用basic_auth认证时用户rbac设置问题

如上两条修复相关的issues在哪？

第二条的basic auth在老版本中(0.5.x)会导致什么问题

**Comment by gjmzj** [comment]
第二条，没有相关issues，是bogeit在群里反馈的，主要问题是必须等apiserver启动完成才能配置basic用户的rbac；
第一条，journald日志的优化是自己发现并解决的

**Comment by liupeng0518** [comment]
感谢，关于第二条的修复是在哪条提交里修复的呢？ 记录太多，没找到

**Comment by gjmzj** [comment]
关于第二条相比于老版本(0.6.x及之前) 中其实就是初始密码变成随机的，并且默认禁用了basic_auth；
提交1.0.0中有几个，1.0.1也有，确实不好找。

**Comment by liupeng0518** [comment]
谢谢
