### ISSUE TITLE
最新版（1.0.1）安装 07.cluster-addon.yml 后 coreDNS， dashboard，metrics 失败

### ISSUE THREAD

**Issue by waitingsong** [gjmzj/kubeasz#497]
单步安装到 06 成功
```
[root@deploy ansible]# uname -a
Linux deploy 5.0.3-1.el7.elrepo.x86_64 #1 SMP Tue Mar 19 09:51:25 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

hosts:
```

# 集群部署节点：一般为运行ansible 脚本的节点
# 变量 NTP_ENABLED (=yes/no) 设置集群是否安装 chrony 时间同步, 公有云上虚机不需要
[deploy]
10.0.0.3 NTP_ENABLED=yes

# etcd集群请提供如下NODE_NAME，注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
10.0.0.2 NODE_NAME=etcd1
10.0.0.27 NODE_NAME=etcd2
10.0.0.25 NODE_NAME=etcd3

[kube-master]
10.0.0.2
10.0.0.27
10.0.0.25

[kube-node]
10.0.0.32
10.0.0.38
10.0.0.42

[harbor]
#192.168.1.8 HARBOR_DOMAIN="harbor.yourdomain.com" NEW_INSTALL=no

[all:vars]
# ---------集群主要参数---------------
DEPLOY_MODE=multi-master

# 采用腾讯云提供的 CLB， 内网型和应用型都测试过
MASTER_IP="10.0.0.8"            # 即负载均衡内网地址
KUBE_APISERVER="https://{{ MASTER_IP }}:8443"

CLUSTER_NETWORK="flannel"

# 服务网段 (Service CIDR），注意不要与内网已有网段冲突
SERVICE_CIDR="10.68.0.0/16"

# POD 网段 (Cluster CIDR），注意不要与内网已有网段冲突
CLUSTER_CIDR="172.20.0.0/16"

# 服务端口范围 (NodePort Range)
NODE_PORT_RANGE="20000-40000"

# kubernetes 服务 IP (预分配，一般是 SERVICE_CIDR 中第一个IP)
CLUSTER_KUBERNETES_SVC_IP="10.68.0.2"

# 集群 DNS 服务 IP (从 SERVICE_CIDR 中预分配)
CLUSTER_DNS_SVC_IP="10.68.0.53"

```

集群状态：
<img width="889" alt="2019-04-02_150051" src="https://user-images.githubusercontent.com/1763067/55384255-d32ffb00-555c-11e9-9db3-bec22ccd4427.png">

节点网络：
<img width="653" alt="2019-04-02_150540" src="https://user-images.githubusercontent.com/1763067/55384285-e4790780-555c-11e9-91b9-1ae0dfd2cc8a.png">

**Comment by waitingsong** [comment]
10.0.0.8 是腾讯云的 CLB ： TCP 监听 8443， 转发到 6443， 后端为 master01-03

执行 `07.cluster-addon.yml` 后状况：
<img width="1032" alt="2019-04-02_150307" src="https://user-images.githubusercontent.com/1763067/55384396-3457ce80-555d-11e9-8578-3edd1b6686d2.png">

master01 节点日志里面有如下异常：
```
Apr 02 15:01:58 VM_0_2_centos kube-apiserver[8079]: E0402 15:01:58.173885    8079 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again
Apr 02 15:03:51 VM_0_2_centos kube-apiserver[8079]: I0402 15:03:51.010995    8079 log.go:172] http: TLS handshake error from 10.0.0.32:4400: remote error: tls: bad certificate
Apr 02 15:03:51 VM_0_2_centos kube-apiserver[8079]: E0402 15:03:51.077271    8079 memcache.go:135] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by waitingsong** [comment]
测试执行
```bash
kubectl run test --image=busybox --replicas=3 sleep 30000
```
可以启动：
<img width="1032" alt="2019-04-02_150748" src="https://user-images.githubusercontent.com/1763067/55384612-bf38c900-555d-11e9-8a6b-2b50fddf95ee.png">

但是在删除容器时要阻塞半分多钟才成功
```
kubectl delete pod -n default test-568866f478-????
```

**Comment by waitingsong** [comment]
还原 hosts 参数：
```
# kubernetes 服务 IP (预分配，一般是 SERVICE_CIDR 中第一个IP)
CLUSTER_KUBERNETES_SVC_IP="10.68.0.1"

# 集群 DNS 服务 IP (从 SERVICE_CIDR 中预分配)
CLUSTER_DNS_SVC_IP="10.68.0.2"
```

因为腾讯 VPC 会占用网段签两个(0, 1) 和最后一个 (255) 地址，所以这几次测试用的是 `10.68.0.2` ，难道哪儿有写定 `0.1` 的？

**Comment by gjmzj** [comment]
首先10.68.0.0/16 这个是k8s内部的服务网段，跟腾讯VPC没任何关系；
CLUSTER_KUBERNETES_SVC_IP 这个地址是该网段的第一个地址，是k8s里面iptables设置的；你可以在master节点查看
`iptables-save|grep 10.68.0.1`

**Comment by waitingsong** [comment]
因为之前安装 calico 屡次失败，担心是这个 10.68/16 和腾讯云 VPC 网段 10.0/16 有关系，所以改成了 0.2 结果掉坑里了。

**Comment by waitingsong** [comment]
另外， CLB 健康度检查应该是导致 TLS 握手证书错误的原因吧，是否有办法解决？
 或者说是否可通过在 CLB 上面部署某个集群节点用到的证书来解决？

**Comment by waitingsong** [comment]
另外， CLB 健康度检查应该是导致 TLS 握手证书错误的原因吧，是否有办法解决？
 或者说是否可通过在 CLB 上面部署某个集群节点用到的证书来解决？

**Comment by gjmzj** [comment]
健康检查导致TLS握手错误，目前还没找到办法

**Comment by waitingsong** [comment]
aws 的 ELB 也存在相同问题： https://github.com/kubernetes/kubernetes/issues/70411
对于腾讯云，创建 CLB 时选择 `传统型` 不会有此问题，如果创建 `应用型` 则会发生 TLS 握手错误。

**Comment by 775999665** [comment]
... 省略
# 在role:cluster-addon 中启用nfs-provisioner 安装
nfs_provisioner_install: "yes"			# 修改为yes
nfs_provisioner_namespace: "kube-system"
nfs_provisioner_ver: "v4.0.1"
nfs_storage_class: "managed-nfs-storage"	
nfs_server: "192.168.31.244"			# 修改为实际nfs server地址
nfs_path: "/data/nfs"				# 修改为实际的nfs共享目录

这个在集群下面config文件添加之后，直接启动根本没有反应
![image](https://user-images.githubusercontent.com/28975554/137099906-339bb9cf-9538-4060-9212-d61b162f84e3.png)

**Comment by 775999665** [comment]
############################
# prepare
############################
# 可选离线安装系统软件包 (offline|online)
INSTALL_SOURCE: "online"

# 可选进行系统安全加固 github.com/dev-sec/ansible-collection-hardening
OS_HARDEN: false

# 设置时间源服务器【重要：集群内机器时间必须同步】
ntp_servers:
  - "ntp1.aliyun.com"
  - "time1.cloud.tencent.com"
  - "0.cn.pool.ntp.org"

# 设置允许内部时间同步的网络段，比如"10.0.0.0/8"，默认全部允许
local_network: "0.0.0.0/0"


############################
# role:deploy
############################
# default: ca will expire in 100 years
# default: certs issued by the ca will expire in 50 years
CA_EXPIRY: "876000h"
CERT_EXPIRY: "438000h"

# kubeconfig 配置参数
CLUSTER_NAME: "cluster1"
CONTEXT_NAME: "context-{{ CLUSTER_NAME }}"


############################
# role:runtime [containerd,docker]
############################
# ------------------------------------------- containerd
# [.]启用容器仓库镜像
ENABLE_MIRROR_REGISTRY: true

# [containerd]基础容器镜像
SANDBOX_IMAGE: "easzlab/pause-amd64:3.2"

# [containerd]容器持久化存储目录
CONTAINERD_STORAGE_DIR: "/var/lib/containerd"

# ------------------------------------------- docker
# [docker]容器存储目录
DOCKER_STORAGE_DIR: "/var/lib/docker"

# [docker]开启Restful API
ENABLE_REMOTE_API: false

# [docker]信任的HTTP仓库
INSECURE_REG: '["127.0.0.1/8"]'


############################
# role:kube-master
############################
# k8s 集群 master 节点证书配置，可以添加多个ip和域名（比如增加公网ip和域名）
MASTER_CERT_HOSTS:
  - "10.1.1.1"
  - "k8s.test.io"
  #- "www.test.com"

# node 节点上 pod 网段掩码长度（决定每个节点最多能分配的pod ip地址）
# 如果flannel 使用 --kube-subnet-mgr 参数，那么它将读取该设置为每个节点分配pod网段
# https://github.com/coreos/flannel/issues/847
NODE_CIDR_LEN: 24


############################
# role:kube-node
############################
# Kubelet 根目录
KUBELET_ROOT_DIR: "/var/lib/kubelet"

# node节点最大pod 数
MAX_PODS: 110

# 配置为kube组件（kubelet,kube-proxy,dockerd等）预留的资源量
# 数值设置详见templates/kubelet-config.yaml.j2
KUBE_RESERVED_ENABLED: "yes"

# k8s 官方不建议草率开启 system-reserved, 除非你基于长期监控，了解系统的资源占用状况；
# 并且随着系统运行时间，需要适当增加资源预留，数值设置详见templates/kubelet-config.yaml.j2
# 系统预留设置基于 4c/8g 虚机，最小化安装系统服务，如果使用高性能物理机可以适当增加预留
# 另外，集群安装时候apiserver等资源占用会短时较大，建议至少预留1g内存
SYS_RESERVED_ENABLED: "no"

# haproxy balance mode
BALANCE_ALG: "roundrobin"


############################
# role:network [flannel,calico,cilium,kube-ovn,kube-router]
############################
# ------------------------------------------- flannel
# [flannel]设置flannel 后端"host-gw","vxlan"等
FLANNEL_BACKEND: "vxlan"
DIRECT_ROUTING: false

# [flannel] flanneld_image: "quay.io/coreos/flannel:v0.10.0-amd64"
flannelVer: "v0.13.0-amd64"
flanneld_image: "easzlab/flannel:{{ flannelVer }}"

# [flannel]离线镜像tar包
flannel_offline: "flannel_{{ flannelVer }}.tar"

# ------------------------------------------- calico
# [calico]设置 CALICO_IPV4POOL_IPIP=“off”,可以提高网络性能，条件限制详见 docs/setup/calico.md
CALICO_IPV4POOL_IPIP: "Always"

# [calico]设置 calico-node使用的host IP，bgp邻居通过该地址建立，可手工指定也可以自动发现
IP_AUTODETECTION_METHOD: "can-reach={{ groups['kube_master'][0] }}"

# [calico]设置calico 网络 backend: brid, vxlan, none
CALICO_NETWORKING_BACKEND: "brid"

# [calico]更新支持calico 版本: [v3.3.x] [v3.4.x] [v3.8.x] [v3.15.x]
calico_ver: "v3.15.3"

# [calico]calico 主版本
calico_ver_main: "{{ calico_ver.split('.')[0] }}.{{ calico_ver.split('.')[1] }}"

# [calico]离线镜像tar包
calico_offline: "calico_{{ calico_ver }}.tar"

# ------------------------------------------- cilium
# [cilium]CILIUM_ETCD_OPERATOR 创建的 etcd 集群节点数 1,3,5,7...
ETCD_CLUSTER_SIZE: 1

# [cilium]镜像版本
cilium_ver: "v1.4.1"

# [cilium]离线镜像tar包
cilium_offline: "cilium_{{ cilium_ver }}.tar"

# ------------------------------------------- kube-ovn
# [kube-ovn]选择 OVN DB and OVN Control Plane 节点，默认为第一个master节点
OVN_DB_NODE: "{{ groups['kube_master'][0] }}"

# [kube-ovn]离线镜像tar包
kube_ovn_ver: "v1.5.3"
kube_ovn_offline: "kube_ovn_{{ kube_ovn_ver }}.tar"

# ------------------------------------------- kube-router
# [kube-router]公有云上存在限制，一般需要始终开启 ipinip；自有环境可以设置为 "subnet"
OVERLAY_TYPE: "full"

# [kube-router]NetworkPolicy 支持开关
FIREWALL_ENABLE: "true"

# [kube-router]kube-router 镜像版本
kube_router_ver: "v0.3.1"
busybox_ver: "1.28.4"

# [kube-router]kube-router 离线镜像tar包
kuberouter_offline: "kube-router_{{ kube_router_ver }}.tar"
busybox_offline: "busybox_{{ busybox_ver }}.tar"


############################
#role:cluster-addon
############################
# coredns 自动安装
dns_install: "yes"
corednsVer: "1.7.1"
ENABLE_LOCAL_DNS_CACHE: true
dnsNodeCacheVer: "1.16.0"
# 设置 local dns cache 地址
LOCAL_DNS_CACHE: "169.254.20.10"

# metric server 自动安装
metricsserver_install: "yes"
metricsVer: "v0.3.6"

# dashboard 自动安装
dashboard_install: "yes"
dashboardVer: "v2.1.0"
dashboardMetricsScraperVer: "v1.0.6"

# nfs-provisioner 自动安装
nfs_provisioner_install: "yes"
nfs_provisioner_namespace: "kube-system"
nfs_provisioner_ver: "v4.0.1"
nfs_storage_class: "managed-nfs-storage"	
nfs_server: "192.168.137.13"
nfs_path: "/data/share"

# ingress 自动安装
ingress_install: "no"
ingress_backend: "traefik"
traefik_chart_ver: "9.12.3"

# prometheus 自动安装
prom_install: "no"
prom_namespace: "monitor"
prom_chart_ver: "12.10.6"

############################
# role:harbor
############################
# harbor version，完整版本号
HARBOR_VER: "v1.9.4"


这个是配置文件
