### ISSUE TITLE
可以为etcd，docker，kubelet等组件添加自定义配置的模板变量吗？

### ISSUE THREAD

**Issue by forbxy** [gjmzj/kubeasz#499]
虽然能直接改roles文件，加上其他配置，然后提交到新仓库里，不过这样的话，后续再合并源项目会很麻烦。还是希望能只改hosts文件来实现

**Comment by gjmzj** [comment]
etcd 模板变量在 roles/etcd/defaults/main.yml
docker 在 roles/docker/defaults/main.yml
kubelet 在 roles/kube-node/defaults/main.yml
对于正在运行的集群，不建议合并源项目的更新代码（特别是跨版本，容易出现兼容性问题）

**Comment by forbxy** [comment]
谢谢
