### ISSUE TITLE
安装文档说明

### ISSUE THREAD

**Issue by bruceforlearn** [gjmzj/kubeasz#5]
@jmgao1983 @gjmzj 
Hello 两位大神
在下在CA配置那里有一点不明
”下载证书工具 CFSSL“
怎么下载？
还有就是教程能不能改成shell+命令+变量？

谢谢

**Comment by gjmzj** [comment]
所有的二进制都在百度网盘连接里面
安装文档是配合ansible-playbook 讲解的，你需要了解下[ansible基础](http://weiweidefeng.blog.51cto.com/1957995/1895261)
用ansible主要为了自动化安装，请理解，shell的话比较难完成自动化

**Comment by vsxen** [comment]
calico 的二进制除了calicoctl其他貌似没有用

**Comment by gjmzj** [comment]
@vsxen 其他的由cni调用的

**Comment by bruceforlearn** [comment]
好的，谢谢
我昨天又找了官方的CFSSL把证书搞定了，但是我使用vmware的NAT网卡，calico的网络有问题啊
有人提这个问题吗？大神

**Comment by gjmzj** [comment]
@bruceforlearn 
vmware workstation我喜欢用host-only网络 (VMnet1)，然后在宿主机上手动把网络共享给VMnet1网卡，这样肯定可以；NAT网卡我没试过创建集群，依我理解除了不能使用NodePort，其他应该都可以吧；
1.你可以修改使用VMnet1
2.你可以先部署AllInOne

**Comment by bruceforlearn** [comment]
@gjmzj  大神好，我已经部署过一套bridge模式的V1.8.2了，就是在NAT不行，所以又出来google新的方法了，目前还是不行，就是在master上kubectl不到自己服务，端口什么都是开放的

**Comment by vsxen** [comment]
loopback 的二进制在哪里下载？？

**Comment by gjmzj** [comment]
@vsxen calico官方文档上有写[文档](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/integration)
具体链接  https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz

**Comment by gjmzj** [comment]
@bruceforlearn sorry，目前没有环境去试这个NAT模式

**Comment by vsxen** [comment]
grafana 的认证账号密码是？yaml没看见环境变量？
