### ISSUE TITLE
nodeports如何指定映射端口号? 

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#50]
@jmgao1983 @gjmzj  @277270678 
请教一下几位大神, 我运行一个nginx 的pod并成功地以node IP + ports方式访问.如下:
kubectl run nginx --image=nginx --port=80
kubectl expose deployment nginx --target-port=80 --type=NodePort

kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)       AGE
kubernetes   ClusterIP   10.68.0.1    <none>        443/TCP       1h
nginx        NodePort    10.68.97.9   <none>        80:4098/TCP   2m

但它默认是随机映射端口的,像上述被映射为4098 ,我想固定为4488端口,但是失败. 我尝试各种方法均无法指定映射的端口. 
例如:
cat nginx.yml 
apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort: 80
   nodePort: 34455
 selector:
  name: nginx

请问有什么办法可以实现我的要求吗? 谢谢了!!!

**Comment by gjmzj** [comment]
可以指定暴露的端口啊，只要确保你暴露的端口在hosts文件里面设置`NODE_PORT_RANGE`范围内，且还未被占用即可。如下yaml配置

``` bash
kind: Service
apiVersion: v1
metadata:
  name: test-svc
spec:
  selector:
    run: test
  ports:
    - protocol: TCP
      port: 80
      # 集群hosts文件中设置的 NODE_PORT_RANGE 作为 NodePort的可用范围
      # 从默认20000~40000之间选一个可用端口，让ingress-controller暴露给外部的访问
      nodePort: 23456
      name: web
type: NodePort
```

**Comment by evenye** [comment]
@gjmzj 泪流满面啊. 我昨天反复试了整整一下午都没有成功. 用您的方法反而成功了.
只是这个方法能否调整一下为直接运行kubectl命令全部实现呢? 

我目前分为二个步骤:
1. 先创建pod : kubectl run nginx --image=nginx --port=80
2. 再创建一个nginx.yml文件,按您的方法填入yaml配置.
3. 执行kubectl create -f nginx.yml 

我最后有个问题请教您, 我以否将yaml的配置直接用kubeclt 的命令一行实现? 考虑到以后我需要用脚本创建这些docker及端口映射,我希望能找到一个方法直接运行kubeclt来代替yaml文件的执行. 

像这样的yaml怎么转换成kubeclt命令呢 ?
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 23456
      name: web
  type: NodePort

**Comment by evenye** [comment]
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 23456
      name: web
  type: NodePort

**Comment by evenye** [comment]
抱歉不知道为什么我一贴过来,格式就乱了.
