### ISSUE TITLE
添加etcd节点报错

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#500]
在执行19.addetcd.yml脚本时，提示需要先添加节点到etcd集群中。

应该是执行的顺序错了，正确的顺序是应该先安装etcd程序，然后再添加到etcd节点。

除此之外，还需要把新添加的节点配置到k8s master节点的kube-apiserver.service文件中。

**Comment by gjmzj** [comment]
建议使用新版本kubeasz （最新版1.0.1），使用 easzctl add-etcd xx.xx.xx.xx添加；
另外，顺序确实是先向集群中添加etcd节点，然后安装etcd程序；可以参考官方说明https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md

**Comment by ilanni2460** [comment]
那可能是我理解错了，主要是我再添加etcd是报错，所以才提出这个问题。谢谢
我使用的还是原来的版本realese-0
