### ISSUE TITLE
easzctl add-node 结果 WARN 是啥情况

### ISSUE THREAD

**Issue by waitingsong** [gjmzj/kubeasz#508]
添加节点 `easzctl add-node` ，成功。最后有个 WARN Invalid Contex，请问会是啥情况？

<img width="520" alt="2019-04-12_100431" src="https://user-images.githubusercontent.com/1763067/56007199-82fa2b00-5d0a-11e9-8a6c-0d0291b8281b.png">

**Comment by gjmzj** [comment]
感谢反馈，我去查一下，增加node结果是正确的吧？？

**Comment by waitingsong** [comment]
增加的节点应该是正常工作的。只是不知道那个提示是啥

**Comment by gjmzj** [comment]
这个提示不用管它，只是说明之前你没有使用 easzctl 命令行来创建集群

**Comment by waitingsong** [comment]
嗯。那下次再执行相同命令就不会有这个提示了吧？

**Comment by gjmzj** [comment]
commit 6b952cb3102da224fef57f1ec0b558451ca6960a 已修复该问题
