### ISSUE TITLE
优化kubelet自生成证书逻辑

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#509]
目前我看当前集群ca证书可以自定义配置. CA_EXPIRY，这里挺好的，不过一个问题，就是由kubelet请求, 然后controller-manager生成的证书 kubelet-client.crt 有效期还是一年，也就是说按照目前的配置一年后集群需要重新删除证书文件和kubelet.config，然后重新进行kubectl certificate approve xxx，感觉这样不友好.

我看了下官方一些文档，这里有两个建议:

1 可以修改kube-controller-manager配置，增加 --experimental-cluster-signing-duration=xxxxh参数，可以自定义生成证书有效时间

2 k8s大于1.8版本，可以增加证书自动更新

我觉得这两个配置挺有必要的，我可以提交一下pull request ，你觉得呢？

**Comment by gjmzj** [comment]
感谢你的建议，之前安装的k8s集群确实存在这个问题；
不过现在这个已经不需要了，kubeasz 0.3.1 以后已经完全不依赖controller-manager生成证书了，是用ansible 脚本生成的证书，默认期限10年以上了

**Comment by kobehaha** [comment]
了解

**Comment by AEGQ** [comment]
_“一年后集群需要重新删除证书文件和kubelet.config，然后重新进行kubectl certificate approve xxx”_

目前集群是kubeasz 0.3.1 https://github.com/gjmzj/kubeasz/commit/cdf778b6aba5887077f4c4f62b52430ff303e3bb 之前安装的，请问这个存在的问题，有修复操作可以参考么 @gjmzj ，如果一年到期的话，集群不可用？

**Comment by forbxy** [comment]
如果遇到该问题，重启kubelet
管理节点执行 kubectl get csr，复制NAME项
执行kubectl certificate approve NAME
