### ISSUE TITLE
TLS证书制作，证书请求文件的hosts字段有什么作用

### ISSUE THREAD

**Issue by Rmond** [gjmzj/kubeasz#51]
`    "CN": "kubernetes",
    "hosts": [
      "127.0.0.1",
      "172.16.1.235",
      "172.16.1.237",
      "172.16.1.244",
      "10.254.0.1",
      "kubernetes",
      "kubernetes.default",
      "kubernetes.default.svc",
      "kubernetes.default.svc.cluster",
      "kubernetes.default.svc.cluster.local"
    ],
`
首先说明我etcd和k8s用的同一套证书也是同一台机器，我尝试过去掉里面235，237，244等ip，发现用etcdctl访问的时候，只要用的ca.pem是同一个，证书和私钥根本无所谓呢

**Comment by gjmzj** [comment]
关于证书首先请阅读项目文档`01-创建CA证书和环境配置.md`，额外[参考](https://coreos.com/os/docs/latest/generate-self-signed-certificates.html)
本地etcdctl访问其实是不需要提供客户端证书和私钥，因为根据本项目参数etcd 对 127.0.0.1的地址不需要tls认证，例如`etcdctl --ca-file /etc/kubernetes/ssl/ca.pem ls` 就可以了

**Comment by Rmond** [comment]
我可能没有说清楚，我不是用本地访问的，我使用另外的etcd环境访问的我这个地址具体命令如下：
`etcdctl --endpoints="https://172.16.1.235:2379" --ca-file=ca.pem --cert-file=kubernetes.pem --key-file=kubernetes-key.pem cluster-health`（可以正常访问）
本机ip是3.54，跟之前没有任何关系。客户端证书也是用的3.54自己的，只有ca.pem用的1.235它们的。所以我有些疑惑，之前的hosts里面指定的牵出来的证书有什么用

**Comment by gjmzj** [comment]
etcdctl是使用**客户端证书**，可以忽略hosts字段；真正启动etcd服务时候要用**服务器证书**必须有hosts字段；项目里面为了方便使用的是**对等证书(peer cert)**；还是证书类型问题需要搞清楚 [参考1](https://coreos.com/os/docs/latest/generate-self-signed-certificates.html) [参考2](https://blogs.msdn.microsoft.com/kaushal/2012/02/17/client-certificates-vs-server-certificates/)
