### ISSUE TITLE
istio 安装失败

### ISSUE THREAD

**Issue by waitingsong** [gjmzj/kubeasz#510]
参照文档
- https://github.com/gjmzj/kubeasz/blob/master/docs/guide/helm.md
- https://github.com/gjmzj/kubeasz/blob/master/docs/guide/istio.md

执行命令
```bash
helm install --name istio install/kubernetes/helm/istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort --set gateways.istio-egressgateway.type=NodePort
```

结果：

<img width="1267" alt="2019-04-12_201646" src="https://user-images.githubusercontent.com/1763067/56036637-ef534980-5d5f-11e9-922e-ef116784baa2.png">

搜索结果好像是 CRD 不存在导致的，按照 istio 官网快速安装倒是可以装上 istio 但是容器启动不正常。

**Comment by waitingsong** [comment]
执行 `kubectl api-versions | grep network` ，结果
```
networking.k8s.io/v1
```

**Comment by waitingsong** [comment]
好像是命令格式有问题

**Comment by gjmzj** [comment]
istio更新块，以官方文档为准吧

**Comment by waitingsong** [comment]
晚点我提交个 PR
