### ISSUE TITLE
dns ping 不通 但是curl可以

### ISSUE THREAD

**Issue by djkdeveloper** [gjmzj/kubeasz#512]
![image](https://user-images.githubusercontent.com/16333920/56092620-dd54e080-5ef0-11e9-82a8-28ed61a66a0a.png)
![image](https://user-images.githubusercontent.com/16333920/56092630-0ecdac00-5ef1-11e9-9c37-dd706913b472.png)
发现dns没问题可以正常解析
但是进入容器ping 
![image](https://user-images.githubusercontent.com/16333920/56092662-68ce7180-5ef1-11e9-8477-b40b017a2355.png)

dns也能正常解析 但是ping不通 dns解析也正常

然后在容器curl 是正常的 这是为啥？
![image](https://user-images.githubusercontent.com/16333920/56092681-8a2f5d80-5ef1-11e9-8e65-98dd3391dbef.png)

**Comment by gjmzj** [comment]
k8s svc（服务）的地址本来就ping不通的

**Comment by djkdeveloper** [comment]
哦哦好吧  原来这样。。。

**Comment by djkdeveloper** [comment]
我还有个坏境
是可以ping通svc的是不是我装了什么东西导致的啊？
![image](https://user-images.githubusercontent.com/16333920/56093997-83a8e200-5f01-11e9-9f23-3359f4eee461.png)
![image](https://user-images.githubusercontent.com/16333920/56094001-8c011d00-5f01-11e9-9c79-c62896634763.png)
