### ISSUE TITLE
yc-ssh-key-copy.sh脚本expect交互时password改成模糊匹配

### ISSUE THREAD

**Issue by aeiougo** [gjmzj/kubeasz#522]
升级openssh版本到7.9以后，Password首字母P会变成大写，如下图：
![image](https://user-images.githubusercontent.com/47635948/56492489-84073580-651e-11e9-94b5-4c53ef228fbe.png)

改成模糊匹配`*assword:`可以兼容
![image](https://user-images.githubusercontent.com/47635948/56492653-0b54a900-651f-11e9-8bc1-5bc6c56968ab.png)

**Comment by gjmzj** [comment]
感谢提醒，下次发布修复它
