### ISSUE TITLE
Unable to connect to the server: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by crazy-canux** [gjmzj/kubeasz#535]
安装master失败了，说证书过期了。

TASK [kube-master : 启动 master 服务] *********************************************************************************************************************************************************
changed: [10.103.239.45]
changed: [10.103.239.44]
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (5 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (4 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (3 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (2 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (1 retries left).

TASK [kube-master : 以轮询的方式等待master服务启动完成] *************************************************************************************************************************************************
fatal: [10.103.239.44 -> 10.103.239.40]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/opt/k8s/bin/kubectl", "get", "node"], "delta": "0:00:00.080247", "end": "2019-04-26 09:23:30.494261", "msg": "non-zero return code", "rc": 1, "start": "2019-04-26 09:23:30.414014", "stderr": "Unable to connect to the server: x509: certificate has expired or is not yet valid", "stderr_lines": ["Unable to connect to the server: x509: certificate has expired or is not yet valid"], "stdout": "", "stdout_lines": []}

**Comment by crazy-canux** [comment]
Apr 28 17:48:00 node2 kube-apiserver[19249]: I0428 17:48:00.288488   19249 log.go:172] http: TLS handshake error from 10.103.239.44:58554: remote error: tls: bad certificate

**Comment by crazy-canux** [comment]
Apr 28 18:03:25 node3 etcd[9743]: rejected connection from "10.103.239.44:49256" (error "read tcp 10.103.239.46:2379->10.103.239.44:49256: read: connection reset by peer", ServerName "")
Apr 28 18:03:25 node3 etcd[9743]: rejected connection from "10.103.239.44:49266" (error "EOF", ServerName "")
Apr 28 18:03:25 node3 etcd[9743]: rejected connection from "10.103.239.44:49272" (error "EOF", ServerName "")
Apr 28 18:03:25 node3 etcd[9743]: rejected connection from "10.103.239.44:49290" (error "EOF", ServerName "")

**Comment by crazy-canux** [comment]
文档没说清楚，ansible server必须是 k8s的node才行。

**Comment by piaobeizu** [comment]
请问怎么解决的？

**Comment by piaobeizu** [comment]
> 文档没说清楚，ansible server必须是 k8s的node才行。

请问您是怎么解决的？

**Comment by crazy-canux** [comment]
ansible server必须是 k8s的node才行。
