### ISSUE TITLE
最新master分支，创建只读账号报错

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#537]
最新master分支，创建只读账号报错，报错信息如下：

TASK [设置集群参数] *********************************************************************************************************************************************************************************
fatal: [192.168.0.184]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'CLUSTER_NAME' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/deploy/create-read-kubeconfig.yml': line 26, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # 设置集群参数，指定CA证书和apiserver地址\n  - name: 设置集群参数\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'CLUSTER_NAME' is undefined"}

应该是没有识别到ansible定义的变量，现在手工处理，把其中的变量给替换掉。

**Comment by gjmzj** [comment]
感谢提醒，我去测试看看，并尝试修复下

**Comment by gjmzj** [comment]
已经优化只读kubeconfig的创建方式，详见提交 881a43ab26d600ba337f6f24706181244f782984

**Comment by ilanni2460** [comment]
@gjmzj @lixianyang 辛苦二位了
