### ISSUE TITLE
kubeasz-184-r2.zip + k8s.184.tar.gz集群的pod服务如何自动迁移?

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#54]
我用以下命令创建一个nginx服务：
kubectl run nginx --image=nginx --replicas=1
root@k8-d-1:/etc/ansible# kubectl get pods -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP              NODE
nginx-7c87f569d-rhp2p   1/1       Running   0          2m        172.20.180.79 10.10.10.82 
我看到它分配到node 10.10.10.82 上了，当我将这台机器关机后，nginx的服务却不会自动迁移到别的node节点上去，永远显示这种状态不变, 请问这是什么原因呢？照理来说它应该会自动迁移到另外一台node上去才对?

**Comment by gjmzj** [comment]
机器关机的话，会自动迁移，默认比较慢，可能需要5-10分钟
如果手动迁移的话，你可以在node关机前执行 `kubectl drain`命令和`kubectl cordon`命令，这样pod会迁移到别的node上

**Comment by evenye** [comment]
@gjmzj 抱歉能问一下有参数可以修改这个迁移的时间吗？

**Comment by evenye** [comment]
@gjmzj 谢谢! 确实是可以的. 
衷心祝您春节快乐! 一切顺利! 家里幸福!
