### ISSUE TITLE
efk部署后，kibana不能访问

### ISSUE THREAD

**Issue by jacky-neo** [gjmzj/kubeasz#540]
采用kubeasz 1.0.1版本, s-m安装方式，efk安装成功，但访问kibana报错，如下：

Error: 'dial tcp 172.20.7.20:5601: i/o timeout'
Trying to reach: 'http://172.20.7.20:5601/'

**Comment by jacky-neo** [comment]
问题解决，是集群中有一台机器内核和其他的不同步，不是4.0以上的

**Comment by jacky-neo** [comment]
解决了

**Comment by lizhenwei** [comment]
@jacky-neo  大神，你是怎么解决的啊？我也遇到了同样的问题。能说一说么

**Comment by jacky-neo** [comment]
> @jacky-neo 大神，你是怎么解决的啊？我也遇到了同样的问题。能说一说么

升级内核，重启机器，就OK了。内核升级参考如下：内核升级最好在做k8s前。内核要在4.4以上
https://blog.csdn.net/qq_27281257/article/details/82049634
