### ISSUE TITLE
多cluster 用easzctl增加节点的bug

### ISSUE THREAD

**Issue by smartxff** [gjmzj/kubeasz#543]
- name: 安装kube-proxy.kubeconfig配置文件
  synchronize: src=/etc/kubernetes/kube-proxy.kubeconfig dest=/etc/kubernetes/kube-proxy.kubeconfig
  delegate_to: "{{ groups.deploy[0] }}"

两个不同的集群都从同一个位置复制kube-proxy.kubeconfig，然后就有问题了。

**Comment by weifan01** [comment]
#533 
我dns无法解析的问题难道也是这个原因？
先用deploy节点创建了一个A集群，再用此deploy节点创建了一个B集群，然后往A集群添加节点后A集群dns就无法解析了

**Comment by smartxff** [comment]
@weifan01 哈哈哈，就是这个原因。

**Comment by smartxff** [comment]
@weifan01 你把ansible机器的/etc/kubernetes/kube-proxy.kubeconfig 文件改成A集群的配置文件就好了

**Comment by weifan01** [comment]
@smartxff   刚刚重新验证了下，就是这个问题导致的，哈哈

**Comment by gjmzj** [comment]
用easzctl 做多集群管理，不同集群deploy节点不能相同；详见[easzctl 命令行介绍](https://github.com/gjmzj/kubeasz/blob/master/docs/setup/easzctl_cmd.md)文档中的：
典型 easzctl 创建管理的集群拓扑如下：

```
+----------------+               +-----------------+
|easzctl 1.1.1.1 |               |cluster-aio:     |
+--+---+---+-----+               |deploy 4.4.4.4   |
   |   |   |                     |master 4.4.4.4   |
   |   |   +-------------------->+etcd   4.4.4.4   |
   |   |                         |node   4.4.4.4   |
   |   +--------------+          +-----------------+
   |                  |
   v                  v
+--+------------+ +---+----------------------------+
| cluster-1:    | | cluster-2:                     |
| deploy 2.2.2.1| | deploy 3.3.3.1                 |
| master 2.2.2.1| | master 3.3.3.1/3.3.3.2         |
| etcd   2.2.2.2| | etcd   3.3.3.1/3.3.3.2/3.3.3.3 |
| node   2.2.2.3| | node   3.3.3.4/3.3.3.5/3.3.3.6 |
+---------------+ +--------------------------------+
```
