### ISSUE TITLE
执行easzctl basic-auth -s -u admin -p test1234报错

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#544]
[root@sp tools]# ./easzctl basic-auth -s -u admin -p test1234
[INFO] Action: enable/disable apiserver's basic-auth : basic-auth basic-auth -s -u admin -p test1234
grep: roles/kube-master/defaults/main.yml: 没有那个文件或目录
grep: roles/kube-master/defaults/main.yml: 没有那个文件或目录
grep: roles/kube-master/defaults/main.yml: 没有那个文件或目录

**Comment by gjmzj** [comment]
正在解决中

**Comment by gjmzj** [comment]
已提交修复 6b7d34cd109db41cf1c2fcf61385fbb00fe9dada
