### ISSUE TITLE
efk说明文档连接错误

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#548]
准备

下载官方最新release，其中release连接错误，正确的连接应该是：
https://github.com/kubernetes/kubernetes/releases

现在是：
https://github.com/kubernetes/kubernetes/release

同时也建议把该链接直接替换为efk的实际路径：
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**Comment by gjmzj** [comment]
最下那个是master分支，不一定是最新release，不过应该也可以

**Comment by ilanni2460** [comment]
@gjmzj 是的，是master分支
