### ISSUE TITLE
efk部署kibana yml文件建议增加取消认证的备注

### ISSUE THREAD

**Issue by ilanni2460** [gjmzj/kubeasz#549]
efk部署kibana yml文件建议增加取消认证的备注

现在efk部署完毕后，访问kibana会提示使用认证信息的，建议增加取消kibana认证的功能。

这个功能增加很简单，直接把kibana的yml文件：
            - name: SERVER_BASEPATH
              value: /api/v1/namespaces/kube-system/services/kibana-logging/proxy

把上述选项注释掉即可。

**Comment by gjmzj** [comment]
你是说访问kibana直接用nodePort方式，或者直接用ingress暴露给用户；
如果是的话，确实可以这里修改：
```
- name: SERVER_BASEPATH
   value: /
```
不过对于生产环境，还是建议使用apiserver方式去访问，可以增加认证授权；毕竟应用日志和系统日志不能任何人都可以访问

**Comment by ilanni2460** [comment]
@gjmzj 嗯 说的也是呢，这个可以根据每一个人的需求来进行设定，比如我们现在的开发测试环境谁都可以访问。没有加入认证。
