### ISSUE TITLE
calico启动不了是什么问题？

### ISSUE THREAD

**Issue by biruce** [gjmzj/kubeasz#55]
calico启动不了是什么问题？是calico对docker版本有要求吗？

**Comment by evenye** [comment]
应该不会吧。 我手动安装的docker最新版，组k8s也完全正常啊

**Comment by gjmzj** [comment]
`systemctl status calico-node` 和 `journalctl -u calico-node` 查看日志，寻找有价值的错误信息

**Comment by biruce** [comment]
谢谢帮助
