### ISSUE TITLE
add-node添加节点后出现问题

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#57]
我使用20.addnode-yal 增加主机， 然后安装一切顺利，master也 kubectl get csr也接受了，不过通过kubect get nodes 一直看不到??这可能是什么问题,我发现/etc/kubernetes/ssl 目录下没有kubelet-client.crt 其他目录都是存在的.

kubectl get csr 没有Issued？

```
NAME                                                   AGE       REQUESTOR           CONDITION
node-csr-2Z40hO86gNPPvPLuaqrvw8QwDJLwhSM6TIyI_hTtkEY   21m       kubelet-bootstrap   Approved
node-csr-BOZ2j2gqfBC4l21Cyg0FyTWPNCMSpoNXOXDCHS-wk6U   7d        kubelet-bootstrap   Approved,Issued
node-csr-C27SLCWfVs__e7aPPzvCYY60UbBjwIhJIajQAH3cfTE   7d        kubelet-bootstrap   Approved,Issued
node-csr-dyfA8AOYZ0rqj34KvYEvcGx69R4LjiOJcaYDyZQiQkY   7d        kubelet-bootstrap   Approved,Issued
node-csr-mo-TAhNQ9yu4T9uPRxZtKClkXVmBnrvDKOWn8OBJtow   7d        kubelet-bootstrap   Approved,Issued
```

**Comment by gjmzj** [comment]
问题node节点，看下kubelet日志 `journalctl -u kubelet`

**Comment by kobehaha** [comment]
一直循环报错--> Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
然后我的节点版本是centos7.2？

**Comment by kobehaha** [comment]
非常感谢你的回复，问题我已经修复了

**Comment by evenye** [comment]
@gjmzj 
请问一下,即然有新增节点,那么我想将某一台节点退役,并且完全清除kubeclt的所有信息. 
这个我该怎么做呢?
