### ISSUE TITLE
lb验证脚本有问题

### ISSUE THREAD

**Issue by zhaixuepan** [gjmzj/kubeasz#59]
环境：
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

killall -0 haproxy 报错 -su: killall: command not found

**Comment by gjmzj** [comment]
Ubuntu需要安装下 `apt install psmisc`，Ubuntu 1604 server 默认已经安装了；
反而CentOS7如果最小化安装是没有这个包的，需要 `yum install psmisc`安装

**Comment by zhaixuepan** [comment]
奇怪，我的就是ubuntu server 1604 lts版的，好像没装呢，总不能啥时候卸载了，回来我再看看
