### ISSUE TITLE
kubelet --address 服务地址绑定问题

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#60]
改系统安装存在一个bug，如果--address = {{NODE_IP}}可能存在绑定不上的情况，如果换位0.0.0.0就可以，有可能有些机器存在外网映射，或则类似共享主机就不能绑定

```
kubectl 配置文件/etc/systemd/system/kubelet.service 
--address=0.0.0.0 

```

**Comment by evenye** [comment]
@kobehaha 如果那台node有多块网卡,每块网卡有不同的网段和IP. 那--address=0.0.0.0会不会出问题呢?

**Comment by kobehaha** [comment]
会出问题，这个点还是得想怎么优化好，如果优化不好优化可以添加一点注释呢？

**Comment by gjmzj** [comment]
@kobehaha 如果--address = {{NODE_IP}}可能存在绑定不上的情况，能否提供错误日志

**Comment by kobehaha** [comment]
我这边想到还有个点,可能优化好一些，我们/etc/systemd/system/kubelet.service 存在一个--hostname-override 默认是ip ,我觉得可能我们把它的值改为NODE_ID可能好一些，然后NODE_ID我们用机器主机名来处理，这样我们看nodes的时候看全是ip 就很麻烦，以前我是通过单个机器手工加lables来处理，不过我还是觉得看起来麻烦一些

**Comment by kobehaha** [comment]
错误日志

```

Jan  2 18:18:59 [localhost] kubelet: I0102 18:18:59.797786   20623 cadvisor_linux.go:170] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp xxxxxx:4194: bind: cannot assign requested address
Jan  2 18:18:59 [localhost] kubelet: F0102 18:18:59.826202   20623 server.go:156] listen tcp 118.89.13.197:10255: bind: cannot assign requested address
```

**Comment by kobehaha** [comment]
还存在一个问题，就是如果不能机器不能绑定公网,calico 指定{{NODE_IP}}也会出错了，如果calico配置多台机器都指定0.0.0.0，那么会显示冲突，这台机器共享网络就会有问题

**Comment by kobehaha** [comment]
@gjmzj 有什么思路吗，请问上边calico的问题

**Comment by gjmzj** [comment]
@kobehaha 你的机器有几个网卡，是否有分外网网卡和内网网卡，使用`ip a`查看下，路由`ip route`，已监听的服务`netstat -antlp|grep LIST`；这些命令都打下看看，或者你那边有比较熟悉linux的同事看下，或许你解决你的问题

**Comment by kobehaha** [comment]
现在绑定冲突问题解决了，出现一个很诡异的现象, calico 连接  A--B OK A-C ok  B-C怎么都不Ok，检查了下防火墙配置没什么ip 限制，很怪

**Comment by gjmzj** [comment]
A，B，C每个节点看看 calico node status, 看看错误日志什么的，也可以尝试重新安装calico

**Comment by kobehaha** [comment]
重新装了很多次也不可以，报错就是 /var/log/messages 这个文件提示

```
 node-to-node mesh | start | 05:41:45 | Active Socket: Connection      |
|                 |                   |       |          | refused


```

```
docker: bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
```

**Comment by dowson521** [comment]
@kobehaha 最近我也碰到这个问题了，场景应该和你一致，请问你这个问题是如何处理的呢？
