### ISSUE TITLE
sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf centos7下执行报错

### ISSUE THREAD

**Issue by qwerkinglin** [gjmzj/kubeasz#61]
kubeasz/roles/prepare/tasks/main.yml
- name: 设置系统参数
  copy: src=95-k8s-sysctl.conf dest=/etc/sysctl.d/95-k8s-sysctl.conf
- name: 生效系统参数
  shell: "sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf"

上文步骤在centos7下执行报错,手动执行如下:
[root@xx ~]# sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf
net.ipv4.ip_forward = 1
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-arptables: No such file or directory

**Comment by kobehaha** [comment]
请问是什么版本呢, 执行
```
modprobe br_netfilter 
然后 ls /proc/sys/net/bridge
```

再次加载试一下呢

**Comment by qwerkinglin** [comment]
这个方法试过了 
modprobe: FATAL: Module br_netfilter not found.
报这个错误,可能是内核缺一些模块.
centos7 1511版本的 minimal安装

**Comment by kobehaha** [comment]
可以考虑升级下内核呢，我用的7.4在docker环境下比较稳定

**Comment by gjmzj** [comment]
@qwerkinglin 如果不升级内核，这个错误暂时跳过也没事

**Comment by DiamondYuan** [comment]
@gjmzj  二进制版本的k8s升级是否会有问题。
能否通过docker镜像的方法来部署。
