### ISSUE TITLE
Node节点添加后的问题？安装添加了两个节点，一个节点成功，一个节点报错如下：

### ISSUE THREAD

**Issue by peterpijing** [gjmzj/kubeasz#62]
Jan 03 10:34:17 localhost kubelet[51364]: I0103 10:34:17.313851   51364 server.go:182] Version: v1.9.0
Jan 03 10:34:17 localhost kubelet[51364]: I0103 10:34:17.313901   51364 feature_gate.go:220] feature gates: &{{} map[]}
Jan 03 10:34:17 localhost kubelet[51364]: I0103 10:34:17.314010   51364 plugins.go:101] No cloud provider specified.
Jan 03 10:34:17 localhost kubelet[51364]: I0103 10:34:17.314028   51364 server.go:303] No cloud provider specified: "" from the config file: ""
Jan 03 10:34:17 localhost kubelet[51364]: I0103 10:34:17.314053   51364 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file 
Jan 03 10:34:17 localhost kubelet[51364]: error: failed to run Kubelet: cannot create certificate signing request: Post https://192.168.13.18:8443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 192.168.13.18:8443: getsockopt: connection refused

**Comment by kobehaha** [comment]
我这个配置文件吗？ /etc/kubernetes/kubelet.kubeconfig ,如果没有cp ~/.kube/config /etc/kubernetes/kubelet.kubeconfig过去重启一下？

**Comment by peterpijing** [comment]
@kobehaha  这个配置文件我拷过去之后，虽然kubelet服务起来了,但是还是报错
Jan 03 11:50:15 localhost kubelet[93685]: E0103 11:50:15.938646   93685 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.13.18:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.13.18:8443: getsockopt: connection refused
Jan 03 11:50:15 localhost kubelet[93685]: E0103 11:50:15.940009   93685 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.13.18:8443/api/v1/nodes?fieldSelector=metadata.name%3D192.168.13.183&limit=500&resourceVersion=0: dial tcp 192.168.13.18:8443: getsockopt: connection refused
Jan 03 11:50:15 localhost kubelet[93685]: E0103 11:50:15.940762   93685 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.13.18:8443/api/v1/pods?fieldSelector=spec.nodeName%3D192.168.13.183&limit=500&resourceVersion=0: dial tcp 192.168.13.18:8443: getsockopt: connection refused

**Comment by kobehaha** [comment]
这就是到访问api的问题了-->192.168.13.18:8443 , 1 是内网吗 ，内网可以通过吗 2 防火墙有配置访问拒绝吗 3 api服务确定正确启动了吗

**Comment by gjmzj** [comment]
/etc/kubernetes/目录下看看有没有这个 bootstrap.kubeconfig 文件 @peterpijing

**Comment by peterpijing** [comment]
嗯，有两个问题问下 @gjmzj 
1.在roles/kube-node/tasks/main.yml 中,这个shell只需要在node1上执行吗？
# kubelet 启动时向 kube-apiserver 发送 TLS bootstrapping 请求，需要绑定该角色
# 只需单节点执行一次，重复执行的报错可以忽略
# 增加15s等待kube-apiserver正常工作
- name: kubelet-bootstrap-setting
  shell: "sleep 15 && {{ bin_dir }}/kubectl create clusterrolebinding kubelet-bootstrap \
        --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap"
  when: NODE_ID is defined and NODE_ID == "node1"
  ignore_errors: true
2.example/hosts.m-masters.example文件中，按照这种格式，只要node1节点和master建立连接成功。node2和node3都报connection refused，是格式写错了吗？
#确保node节点有变量NODE_ID=node1
[kube-node]
192.168.1.2 NODE_ID=node1 NODE_IP="192.168.1.2"
192.168.1.3 NODE_ID=node2 NODE_IP="192.168.1.3"
192.168.1.4 NODE_ID=node3 NODE_IP="192.168.1.4"

**Comment by peterpijing** [comment]
@kobehaha 你说的三点我都确认不是真正的原因。 /etc/kubernetes/ bootstrap.kubeconfig这个文件生成了，但是你说的这种方式cp ~/.kube/config /etc/kubernetes/kubelet.kubeconfig 应该是绕过了bootstrap验证吧？ @gjmzj  一起解答下，它说的方式了

**Comment by jmgao1983** [comment]
@peterpijing 1.在roles/kube-node/tasks/main.yml 中,这个shell只需要在node1上执行吗？是的，这个就是普通的rbac设置，在集群上配置一次即可，随便哪个节点都可以，只要节点安装有kubectl客户端
2.格式没错

**Comment by jmgao1983** [comment]
@peterpijing 最简单的方法是 `ansible-playbook 07.kube-node.yml`再运行一下
