### ISSUE TITLE
无法从私人仓库pull image

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#63]
@gjmzj 请教一下大神, 为什么这个版本的docker 不能pull image 呢? 提示以下错误:

root@k8-d-1:/etc/docker# docker pull 172.10.10.28:5000/u14.04-all  
Using default tag: latest
Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"

已经允许私人仓库
root@k8-d-1:/etc/docker# cat daemon.json
{
  "registry-mirrors": ["https://registry.docker-cn.com"], 
  "insecure-registries": ["172.10.10.28:5000"],
  "max-concurrent-downloads": 6
}
root@k8-d-1:/etc/docker#

谢谢!!

**Comment by EamonZhang** [comment]
怎么push上去的

**Comment by evenye** [comment]
@gjmzj  私人仓库, 打个tag后直接运行push 就行了. 
例如:
docker tag pause-amd64:3.0 172.10.10.28:5001/pause-amd64:3.0
docker pull 10.231.248.28:5001/pause-amd64:3.0

**Comment by evenye** [comment]
不知为何,非二进制的docker最新版都可以下载.
但这些二进制的却不能下载.
经过反复检查,初步确定是因为我的私人仓库用的是V1版的. 我重新开了一个V2版的私人仓库是可以用的.
不知道有没有办法让它可以兼容V1版的仓库呢?  毕竟其它版本的docker 并没有这个问题.
