### ISSUE TITLE
traefik是不是应该在每个结点都安装

### ISSUE THREAD

**Issue by rainhard** [gjmzj/kubeasz#64]
首先感谢自动化部署，节省了很多时间。
这里有个疑问想讨论一下：traefik应该在每个节点都装吧
从集群外访问应该是这个路径：
client --> firewall --> ingress --> service --> pod
用manifest安装后只在一个节点上运行，怎么能让请求到这个节点呢？防火墙上做端口映射不能确定后方的地址，集群内的域名也解析不了。
如果所有结点都装，可以在防火墙对后方所有结点做负载均衡，请求就可以被路由了。

**Comment by EamonZhang** [comment]
不需要，kube-proxy iptable会做这方面的工作。

**Comment by gjmzj** [comment]
traefik是个集群服务，负载不大的话只需要1个，当然如果你的集群上有太多服务需要使用traefik来代理，可以考虑扩容，功能上与1个traefik相同，所有kube-node节点都可以利用nodeIP:NodePort来使用。
确实就是kube-proxy起的作用；具体可以 [ingress.md](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/ingress.md) 仔细看下

**Comment by rainhard** [comment]
[ingress.md](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/ingress.md)里有句话：
注意：ingress 本身也需要部署Ingress controller时暴露NodePort让外部访问

这就是我疑问的地方。如果Ingress controller被调度，它的NodeIP变了，外面怎么访问。

“ingress-service的代理” 部分没能解决NodeIP变化的感知

**Comment by rainhard** [comment]
我想应该是集群内通过nodeselector指定几个节点安装ingress controller,这样可以避免单点故障，前方也可以直接映射到这几个节点

**Comment by gjmzj** [comment]
@rainhard `如果Ingress controller被调度，它的NodeIP变了，外面怎么访问` 关于这个疑问，你得详细了解下K8S `kube-proxy`和`service`的基本概念原理；
NodeIP可以是任意一个kube-node的地址，不用管它上面是否有Ingress controller，你有环境试一下不就可以了

**Comment by rainhard** [comment]
之前都是用pod所在node的ip测试，刚才用任意node都可以，这下释然了。
多谢指教，接触时间不长，基本概念理解还有问题。

**Comment by rainhard** [comment]
又想到几个延伸的问题：
1）使用NodePort方式，一个节点上只能跑这个服务的一个Pod
2）如果这种Pod部署了多个，通过任意节点访问服务时，转发的策略是什么。一般优先访问本节点服务，如果本节点没有服务，是轮询转发其他节点，还是按照某种顺序转发
