### ISSUE TITLE
Node启动calico报错

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#66]
```
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory,
```
这应该是容器内的，我看也没有做v映射，请问是有什么地方有问题吗？

**Comment by gjmzj** [comment]
在node节点 docker ps 查看`calico-node` 容器是否运行，如果可以，使用`docker exec -it xxx /bin/sh`查看下，我的部署可以看到如下：
``` bash
# docker exec -it ee56bcadc002 /bin/sh
/ # ls /etc/calico/confd/config/
bird.cfg             bird6.cfg            bird6_aggr.cfg       bird6_ipam.cfg       bird_aggr.cfg        bird_ipam.cfg        custom_filters.cfg   custom_filters6.cfg
```

**Comment by kobehaha** [comment]
现在这个文件解决了，我看bird.cfg它配置文件中是由conf.d自动生成的，然后它记录了到集群中每个节点的连接信息，然后也正确的标识了，不过现在有个异常时它获取连接信息，去连接的时候，会报出
```
an  7 11:33:49 [localhost] docker: bird: Mesh_XXXXX[IP]: Socket error: bind: Address not available,
```
只有两台机器相互存在，集群其他机器连接它都是好的,看起来是相互连接需要绑定暂用的端口被占用了，或则bind的地址不正确，不过我看两台机器到其他机器的连接没问题，比较费解,请问一般这可能有哪些猜想呢

**Comment by gjmzj** [comment]
可能是这两个节点建立bgp邻居是使用的IP地址有问题，你可以在集群每个节点使用`calicoctl node status` 查看下bgp邻居情况，关注bgp邻居建立的地址`peer address`

**Comment by kobehaha** [comment]
它的错误是属于
```
-----------------+-------------------+-------+------------+--------------------------------+
| xxx   | node-to-node mesh | start | 2018-01-07 | Active Socket: Connection      |
|                 |                   |       |            | closed

```
因为他们之间会Socket:error，所有肯定不能正常连接, perr address 我填写是公网地址，所有这个地址也是公网地址，没问题。不过按理来说我直接填写公网也没问题把？按理说公网可以通，那么我们连接就可以通呀？不过有内网依赖类似的

**Comment by gjmzj** [comment]
@kobehaha 如果你仔细看过项目中`安装calico网络组件.md`说明
``` bash
重要本K8S集群运行在同网段kvm虚机上，虚机间没有网络ACL限制，因此可以设置CALICO_IPV4POOL_IPIP=off，如果你的主机位于不同网段，或者运行在公有云上需要打开这个选项 CALICO_IPV4POOL_IPIP=always
```

**Comment by kobehaha** [comment]
CALICO_IPV4POOL_IPIP我是改为always的，很奇怪的是相互不通的两台机器到其他机器是通的，只是他们之前不通，互相不通机器他们是运行腾讯云，而其他的机器是其他的云，其他机器没问题..这就很奇怪了

```
| 118.89.14.76    | node-to-node mesh | start | 09:28:53 | Active Socket: Connection      |
|                 |                   |       |          | closed                         |
| xxxx | node-to-node mesh | wait  | 09:28:53 | Established                    |
| xxxx | node-to-node mesh | wait  | 09:28:53 | Established                    |
| xxxx | node-to-node mesh | wait  | 09:28:54 | Established                    |
| xxxx | node-to-node mesh | wait  | 09:28:56 | Established                    |
+-----------------+-------------------+-------+----------+--------------------------------+
```

**Comment by peterpijing** [comment]
主机如果在相同的网断，但是部署在公有云上，需要打开这个选项 CALICO_IPV4POOL_IPIP=always吗？

**Comment by gjmzj** [comment]
@peterpijing 需要打开，当然每家公有云不太一样，而且你选用的网络类型也不一样，有的选了VPC网络，具体情况可以部署测试测试

**Comment by gjmzj** [comment]
@kobehaha 你够厉害的，k8s集群节点跨的远啊，还跨不同的公有云，厉害！公有云有些网络问题我也没有条件完全测试过

**Comment by kobehaha** [comment]
好吧，那我自己在研究下,辛苦作者了

**Comment by gjmzj** [comment]
@kobehaha 如果不介意重新安装的话，可以用master分支的最新源码，并选择flannel网络，这个在公有云上兼容性好一点

**Comment by kobehaha** [comment]
好的，我先试下，我也准备试下他们自家的k8s，毕竟支持更好，可以用他们的存储，vpc，服务器等等

**Comment by kobehaha** [comment]
我重新换了个集群，然后用flannel 模式，还是不行，pod内网不通，flannel容器内会出现

```
E0113 11:08:30.828280       1 vxlan_network.go:158] failed to add vxlanRoute (172.20.0.0/24 -> 172.20.0.0): invalid argument
```

**Comment by xiongraorao** [comment]
我也遇到了这个问题，楼主解决了吗？
![image](https://user-images.githubusercontent.com/20520593/40763410-72c2a84c-64d7-11e8-8640-f9d86a5673b0.png)
我使用的是flannel

**Comment by lzdtech** [comment]
楼主解决了吗，我和你情况一样，使用flannel 和calico都是一样错误

**Comment by coregiu** [comment]
docker logs看下flannel容器的日志，如果是E0113 09:16:52.215497       1 main.go:235] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-xsjxc': Get "https://10.1.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-xsjxc": x509: certificate is valid for 10.96.0.1, 192.167.192.49, not 10.1.0.1

则kubeadm reset集群，然后kubeadm init中加上--apiserver-cert-extra-sans=10.1.0.1,192.167.192.200重新初始化集群。
