### ISSUE TITLE
新节点无法正常运行dashboard和heapster

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#70]
请问一下,我新增了一个节点,这个节点跟其它的节点不在同一个网段.

但节点之间的访问应该是没有限制的. 

我发现只要docker 上的dashboard和heapster移到新节点就无法打开. 
查日志也没有发现什么错误.

请问有什么办法我可以查到原因吗? 

如果dashboard的image在这个新节运行,打开网页就会提示这样:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

**Comment by evenye** [comment]
@gjmzj 

看起来是dashboard在反复重启
kubectl get pod -n kube-system | grep dashboard
kubernetes-dashboard-58ddfdfd68-nv884      0/1       CrashLoopBackOff   9          19m

**Comment by gjmzj** [comment]
kubectl logs -n kube-system kubernetes-dashboard-58ddfdfd68-nv884 看看日志
