### ISSUE TITLE
flannel模式会出错

### ISSUE THREAD

**Issue by kobehaha** [gjmzj/kubeasz#76]
我重新换了个集群，然后用flannel 模式，还是不行，pod内网不通，flannel容器内会出现 

```
 E0113 11:08:30.828280       1 vxlan_network.go:158] failed to add vxlanRoute (172.20.0.0/24 -
```

**Comment by kobehaha** [comment]
两台机器一台成功，有一台还是会失败

**Comment by gjmzj** [comment]
如果运行在公有云虚机上，请确保虚机的`安全组`对于集群内的机器之间`所有协议`进出双向都放行

**Comment by kobehaha** [comment]
我用的他们黑石物理机，应该是没有安全组限制的，我再排查下其他原因

**Comment by gjmzj** [comment]
云上物理机也是有安全组的，至少`天翼云`是这样的

**Comment by kobehaha** [comment]
好的，我都找下原因

**Comment by kobehaha** [comment]
上次的问题我清楚了，我们的网络环境需要二层互通，然后我用的是不同运营商的机器，导致不是在同一个二层，所有他们不能互通，如果说需要互通需要单独配置路由,
