### ISSUE TITLE
安装第一步失败，是什么意思呀

### ISSUE THREAD

**Issue by xiawanyingtest** [gjmzj/kubeasz#77]
TASK [prepare : 缓存ansilbe setup信息] ********************************************************************************************************
fatal: [192.168.1.110]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.1.110 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_NbXH9c/ansible_module_setup.py\", line 139, in <module>\r\n    main()\r\n  File \"/tmp/ansible_NbXH9c/ansible_module_setup.py\", line 131, in main\r\n    data = get_all_facts(module)\r\n  File \"/tmp/ansible_NbXH9c/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3907, in get_all_facts\r\nTypeError: Bad subset 'min' given to Ansible. gather_subset options allowed: all, hardware, ohai, network, virtual, facter\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/etc/ansible/01.prepare.retry

PLAY RECAP ********************************************************************************************************************************
192.168.1.110              : ok=13   changed=3    unreachable=0    failed=1   

[root@localhost ansible]# ansible all -m ping
192.168.1.110 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
[root@localhost ansible]# 
其中/etc/hosts使用的是默认的
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

#--------------------------------------------------------------------------------------------
下面是/etc/ansible中的hosts的配置文件

# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

# Ex 1: Ungrouped hosts, specify before any group headers.

## 192.168.100.10

# Ex 2: A collection of hosts belonging to the 'webservers' group

## 192.168.1.110

# If you have multiple hosts following a pattern you can specify
# them like this:

## www[001:006].example.com

# Ex 3: A collection of database servers in the 'dbservers' group

[dbservers]
192.168.1.110
## 
## 10.25.1.57

# Here's another example of host ranges, this time there are no
# leading 0s:

## db-[99:101]-node.example.com

# 部署节点：运行ansible 脚本的节点
[deploy]
192.168.1.110

# etcd集群请提供如下NODE_NAME、NODE_IP变量
# 请注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
192.168.1.110 NODE_NAME=etcd1 NODE_IP="192.168.1.110"

[kube-master]
192.168.1.110 NODE_IP="192.168.1.110"

#确保node节点有变量NODE_ID=node1
[kube-node]
192.168.1.110 NODE_ID=node1 NODE_IP="192.168.1.110"

[kube-cluster:children]
kube-node
kube-master

# 如果启用harbor，请配置后面harbor相关参数
[harbor]
#192.168.1.8 NODE_IP="192.168.1.8"

# 预留组，后续添加node节点使用
[new-node]
#192.168.1.xx NODE_ID=node6 NODE_IP="192.168.1.xx"

[all:vars]
# ---------集群主要参数---------------
#集群 MASTER IP
MASTER_IP="192.168.1.110"

#集群 APISERVER
KUBE_APISERVER="https://192.168.1.110:6443"

#pause镜像地址
POD_INFRA_CONTAINER_IMAGE=mirrorgooglecontainers/pause-amd64:3.0

#TLS Bootstrapping 使用的 Token，使用 head -c 16 /dev/urandom | od -An -t x | tr -d ' ' 生成
BOOTSTRAP_TOKEN="d18f94b5fa585c7123f56803d925d2e7"

# 集群网络插件，目前支持calico和flannel
CLUSTER_NETWORK="calico"

# 部分calico相关配置，更全配置可以去roles/calico/templates/calico.yaml.j2自定义
# 设置 CALICO_IPV4POOL_IPIP=“off”,可以提高网络性能，条件限制详见 05.安装calico网络组件.md
CALICO_IPV4POOL_IPIP="always"
# 设置 calico-node使用的host IP，bgp邻居通过该地址建立，可手动指定端口"interface=eth0"或使用如下自动发现
IP_AUTODETECTION_METHOD="can-reach=223.5.5.5"

# 部分flannel配置，详见roles/flannel/templates/kube-flannel.yaml.j2
FLANNEL_BACKEND="vxlan"

# 服务网段 (Service CIDR），部署前路由不可达，部署后集群内使用 IP:Port 可达
SERVICE_CIDR="10.68.0.0/16"

# POD 网段 (Cluster CIDR），部署前路由不可达，**部署后**路由可达
CLUSTER_CIDR="172.20.0.0/16"

# 服务端口范围 (NodePort Range)
NODE_PORT_RANGE="20000-40000"

# kubernetes 服务 IP (预分配，一般是 SERVICE_CIDR 中第一个IP)
CLUSTER_KUBERNETES_SVC_IP="10.68.0.1"

# 集群 DNS 服务 IP (从 SERVICE_CIDR 中预分配)
CLUSTER_DNS_SVC_IP="10.68.0.2"

# 集群 DNS 域名
CLUSTER_DNS_DOMAIN="cluster.local."

# etcd 集群间通信的IP和端口, **根据实际 etcd 集群成员设置**
ETCD_NODES="etcd1=https://192.168.1.110:2380"

# etcd 集群服务地址列表, **根据实际 etcd 集群成员设置**
ETCD_ENDPOINTS="https://192.168.1.110:2379"

# 集群basic auth 使用的用户名和密码
BASIC_AUTH_USER="admin"
BASIC_AUTH_PASS="test1234"

# ---------附加参数--------------------
#默认二进制文件目录
bin_dir="/root/local/bin"

#证书目录
ca_dir="/etc/kubernetes/ssl"

#部署目录，即 ansible 工作目录
base_dir="/etc/ansible"

#私有仓库 harbor服务器 (域名或者IP)
#HARBOR_IP="192.168.1.8"
#HARBOR_DOMAIN="harbor.yourdomain.com"

**Comment by gjmzj** [comment]
`ansible all -m setup`直接运行会报错吗？

**Comment by TimLoveFreedom** [comment]
TASK [prepare : 缓存ansilbe setup信息] *********************************************
fatal: [cdh-node3]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: gather_subset"}
fatal: [cdh-node2]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: gather_subset"}
fatal: [cdh-node1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: gather_subset"}
fatal: [x.x.x.x]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: gather_subset"}
一样报错
