### ISSUE TITLE
执行kube-node.yml时报错

### ISSUE THREAD

**Issue by TimLoveFreedom** [gjmzj/kubeasz#79]
changed: [cdh-node3] => (item=kube-proxy)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/bridge'
failed: [cdh-node3] (item=bridge) => {"changed": false, "item": "bridge", "msg": "Could not find or access '/etc/ansible/bin/bridge'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/host-local'
failed: [cdh-node3] (item=host-local) => {"changed": false, "item": "host-local", "msg": "Could not find or access '/etc/ansible/bin/host-local'"}
changed: [cdh-node3] => (item=loopback)
changed: [cdh-node2] => (item=kube-proxy)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/bridge'
failed: [cdh-node2] (item=bridge) => {"changed": false, "item": "bridge", "msg": "Could not find or access '/etc/ansible/bin/bridge'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/ansible/bin/host-local'
failed: [cdh-node2] (item=host-local) => {"changed": false, "item": "host-local", "msg": "Could not find or access '/etc/ansible/bin/host-local'"}

**Comment by gjmzj** [comment]
提示就是没有`bridge` `host-local`这两个文件，去分享的百度盘下载`k8s.191.tar.gz`，解压出来有这两个文件的，请查看master分支的[快速指南](https://github.com/gjmzj/kubeasz/blob/master/docs/quickStart.md)

**Comment by TimLoveFreedom** [comment]
@gjmzj 好的已解决，用的k8s 1.8.4版本，缺少了文件，tks
