### ISSUE TITLE
安转顺利完成，但是不能获得node列表

### ISSUE THREAD

**Issue by levonchen** [gjmzj/kubeasz#8]
系统：Centos 7.31
安转除了下面这一部分可选项在centos不能过以外，别的都比较顺利：
## 可选 ------安装docker查询镜像 tag的小工具----
- name: apt更新缓存刷新
  apt: update_cache=yes cache_valid_time=72000
  tags: docker-tag

- name: 安装轻量JSON处理程序
  apt: name=jq state=latest
  tags: docker-tag

- name: 下载 docker-tag
  copy: src=docker-tag dest={{ bin_dir }}/docker-tag mode=0755
  tags: docker-tag

因为这一部分使用了apt-get

但是安装好以后，获取不到node list

[root@vb-centos1 ~]# kubectl cluster-info
Kubernetes master is running at https://192.169.1.130:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@vb-centos1 ~]# kubectl get node
No resources found.
[root@vb-centos1 ~]# kubectl get pod --all-namespaces
No resources found.
[root@vb-centos1 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 192.169.1.132 | node-to-node mesh | up    | 13:01:31 | Established |
| 192.169.1.131 | node-to-node mesh | up    | 13:02:17 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

我是使用了三个虚拟机，一个master 两个nodes的配置

**Comment by gjmzj** [comment]
centos7 的安装我没有验证过，据说还是有几个坑的，node没起来主要是看 kubelet的错误日志，`journalctl -u kubelet `

**Comment by gjmzj** [comment]
有时间我自己测一把

**Comment by junthink** [comment]
我也遇到这个问题，node一个都没起来
journalctl -u kubelet里有一个error: failed to run Kubelet: unknown cloud provider "''"
请问这个cloud在哪里设置？

**Comment by evenye** [comment]
请问一下,https://192.169.1.130:6443的用户名和密码是什么? 我用root帐号好像不能登陆? 谢谢了!!

**Comment by gjmzj** [comment]
@junthink `/etc/systemd/system/kubelet.service` 里面可以把 `--cloud-provider='' `这一行删掉，然后 `systemctl daemon-reload && systemctl restart kubelet` 试试，按理说这个问题不会有啥大影响

**Comment by levonchen** [comment]
@evenye ,这个是我的master server，集群里面的主机。你肯定没法访问的啊

**Comment by levonchen** [comment]
@gjmzj  发现了下面的错误：
error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
在/etc/kubernetes下面只有下面两个文件： bootstrap.kubeconfig  kube-proxy.kubeconfig  和一个文件夹ssl

**Comment by evenye** [comment]
对不起,我是想说,我的集群建好后,我直接打开LB的VIP地址, https://10.10.2.17:8443/,它弹出对话框让我输用户名和密码.
我用本机,帐号试均不成功. 还请指点一下? 谢谢您了!!



Best Regards
Even

**Comment by vsxen** [comment]
admin
test1234
/etc/kubernetes/ssl/basic-auth.csv

**Comment by evenye** [comment]
@vsxen ,谢谢您了!!!

**Comment by evenye** [comment]
@vsxen,我可以登陆了,但是好像打开提示有错误,请问您知道是什么原因吗? 

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"admin\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

**Comment by vsxen** [comment]
用kubectl proxy 打开

**Comment by evenye** [comment]
@vsxen 真是不好意思哈.我是新手. 您说的用kubectl proxy 可以打开dashboard ,是用如下命令吗?
kubectl proxy --address='10.10.2.17' --port=8443 --accept-hosts='^*$' 
我这里有错误发生:
F1207 16:17:45.772424   13954 proxy.go:153] listen tcp 10.10.2.17:8443: bind: cannot assign requested address

**Comment by vsxen** [comment]
'10.10.2.17' 这个是的网卡IP 看错误冇事端口占用 换一个吧

**Comment by evenye** [comment]
@vsxen 
10.10.2.17 这个是Kubernetes master 的虚拟IP: 
root@k8-d-2:~# kubectl cluster-info
Kubernetes master is running at https://10.10.2.17:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

这个端口对外是开放的,我telnet也能看出来,但只是打开网页提示如下错误:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"admin\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

不知道是怎么回事呢?

**Comment by junthink** [comment]
@gjmzj 多谢大神，你做的这个东西太方便了

**Comment by vsxen** [comment]
kubectl proxy --address='10.10.2.17' --port=8001 --accept-hosts='^*$'

打开10.10.2.17:8001/ui

**Comment by evenye** [comment]
@vsxen 奇怪无论用什么端口都不行:
root@k8-d-1:/home# kubectl proxy --address='10.10.2.17' --port=5001 --accept-hosts='^*$' 
F1207 17:16:43.431353   14787 proxy.go:153] listen tcp 10.10.2.17:5001: bind: cannot assign requested address
root@k8-d-1:/home# netstat -antlp|grep 7001
root@k8-d-1:/home# netstat -antlp|grep 5001
root@k8-d-1:/home# netstat -antlp|grep 8443
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      4640/haproxy  


新手,学得很坚难,一步一步地不断尝试,幸好有您的帮助,谢谢!!!

**Comment by evenye** [comment]
@vsxen @gjmzj  我的问题解决了,谢谢您们!

运行kubectl get svc 会看到类似
kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)       AGE
kubernetes   ClusterIP   10.68.0.1    <none>        443/TCP       1h
nginx        NodePort    10.68.97.9   <none>        80:4098/TCP   2m

浏览器访问 $NodeIP:4098即可
http://10.233.2.82:4098/

**Comment by levonchen** [comment]
刚才从新部署了一下，发现kubelet起不来，是因为下面的原因：
Dec 08 18:47:20 centos-node1 kubelet[5430]: I1208 18:47:20.025041    5430 bootstrap.go:57] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Dec 08 18:47:20 centos-node1 kubelet[5430]: error: failed to run Kubelet: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "kubelet-bootstrap" cannot create cer

**Comment by gjmzj** [comment]
@levonchen 我脚本中是有这个步骤的，可能因为一些原因没执行成功，anyway，你自己能解决了

**Comment by gjmzj** [comment]
@evenye @vsxen 关于dashboard的访问可以参考我更新的dashboard.md文档

**Comment by evenye** [comment]
@gjmzj 太了不起来,我昨天还在用别的教程启dashboard但一直没有成功,提示境像下载失败. 
今天看到您的更新后,换成您的方法几分钟就成功了!!!  赞!!!  大赞!

**Comment by peterpijing** [comment]
@levonchen 下面的这个报错，我已经执行了kubectl create --insecure-skip-tls-verify clusterrolebinding kubelet-bootstrap 
--clusterrole=system:node-bootstrapper \ --user=kubelet-bootstrap
但是依然node节点的kubelet启动报这个错误，知道什么原因吗？
5.如果启动kubelet时报错failed to run Kubelet: cannot create certificate signing
request: certificatesigningrequests.certificates.k8s.io is forbidden: User "kubelet-bootstrap" cannot create certificatesigningrequests，是由于在master上忘记创建
clusterrolebinding ，执行
kubectl create --insecure-skip-tls-verify clusterrolebinding kubelet-bootstrap 
--clusterrole=system:node-bootstrapper \ --user=kubelet-bootstrap就可以解决了。
