### ISSUE TITLE
kubectl get componentstatus

### ISSUE THREAD

**Issue by TimLoveFreedom** [gjmzj/kubeasz#80]
执行kubectl get componentstatus时，etcd-0               Unhealthy   Get https://cdh-node1:2379/health: x509: certificate is valid for etcd, not cdh-node1好像证书有问题，没找到具体问题

**Comment by gjmzj** [comment]
请提供更多信息帮助排查：
1. k8s版本
2. 网络插件 flannel？calico?
3. 部署模式 AllinOne? 多master？
4. 使用项目的分支：master，v1.9，v1.8？
5. 其他相关日志，比如 `journalctl -u etcd`
