### ISSUE TITLE
hosts.allinone.example文件配置

### ISSUE THREAD

**Issue by TimLoveFreedom** [gjmzj/kubeasz#81]
你好，请问一下，如果集群中node本身就有内网地址和外网地址，hosts文件https都配置成外网？（或者哪些配置成内网ip,哪些配置成外网ip?）

**Comment by gjmzj** [comment]
你说的外网地址是指该网卡可以ping通公网，还是说该网卡直接绑定了公网地址？
hosts.allinone.example模板中建议都配成内网地址

**Comment by TimLoveFreedom** [comment]
@gjmzj 绑定了公网地址，都配置成内网地址的话，6443绑定的也是内网地址吧，外网就没法直接ip+port访问ui页面了吧

**Comment by gjmzj** [comment]
allinone的话，其实你可以在模板中都替换成公网地址；
当然如果之前你已经配了内网地址，集群运行起来了，你也可以手动修改:
`/etc/systemd/system/kube-apiserver.service`文件，把里面的相关行改成`--bind-address=0.0.0.0`保存退出，然后执行：
`systemctl daemon-reload`
`systemctl restart kube-apiserver`
