### ISSUE TITLE
请教，启动DNS失败报错信息如下

### ISSUE THREAD

**Issue by zhangwj-HS** [gjmzj/kubeasz#83]
I0117 06:05:37.525634       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:38.025553       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:38.525639       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:39.025626       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:39.525629       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:40.025978       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:40.525951       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:41.025520       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0117 06:05:41.027104       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.68.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.68.0.1:443: i/o timeout
E0117 06:05:41.027177       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.68.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.68.0.1:443: i/o timeout
I0117 06:05:41.525568       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:42.026548       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0117 06:05:42.525650       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

**Comment by gjmzj** [comment]
请提供些相关信息：
网络插件 flannel？calico?
部署模式 AllinOne? 多master？
使用项目的分支：master，v1.9，v1.8？
可以尝试分步安装，每一步的验证是否都能成功

**Comment by luokeychen** [comment]
我也同样遇到问题
请提供些相关信息：
网络插件 calico
部署模式  s master
使用项目的分支：v1.9
每一步执行都通过了

**Comment by gjmzj** [comment]
@luokeychen 是不是在等待从网上下载dns的相关镜像

**Comment by luokeychen** [comment]
@gjmzj 
docker images 确认过了已经下载完成
用 kubectl logs 看了一下报错
类似于下面的报错（VM环境删掉了）
`I0712 09:37:12.453626       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0712 09:37:12.454204       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0712 09:37:12.454254       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0712 09:37:12.953657       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I`
VM删除后重新从头试了很多次，总是不行。
有什么建议吗？

**Comment by gjmzj** [comment]
@luokeychen 
第一次安装最好分步安装，每步成功后都有相关验证，通过之后才继续下一步，确认etcd/master/node/网络都成功后再去安装dns插件，单机部署会有问题吗？建议单机部署先测试下，总之多尝试下，这个项目虽然提供类似一键安装，但是最好的地方是可以分步安装和了解每一步组件安装细节。

**Comment by luokeychen** [comment]
@gjmzj 
非常感谢你的分享，对我个人学习很有帮助
顺利过了Mirantis KCM 100 谢谢。

对于这个问题，最后我发现好像是VM内存分的太小了，API访问没有来的来的急处理。就timeover了。
我把主节点的内存分到6G后类似问题解决了。

1.9.1版本s.master集群calico和flannel我也试了，启动后container起来了又掉了（循环几次就死了）。
后来我发现你的hosts配置里有这个参数
# 设置 calico-node使用的host IP，bgp邻居通过该地址建立，可手动指定端口"interface=eth0"或使用如下自动发现
IP_AUTODETECTION_METHOD="can-reach=223.5.5.5"
我想请问一下这个参数的具体作用
当我把can-reach=223.5.5.5改成interface=eth1 时，container可以保持running状态。

容器的网络我总是觉得很难搞懂。

**Comment by gjmzj** [comment]
@luokeychen 恭喜通过KCM 100
关于calico网络参数的说明，项目[calico文档](https://github.com/gjmzj/kubeasz/blob/master/docs/07-%E5%AE%89%E8%A3%85calico%E7%BD%91%E7%BB%9C%E7%BB%84%E4%BB%B6.md) 都有给出官网参数说明链接

**Comment by luokeychen** [comment]
@gjmzj 
我在仔细看看官方文档。
有具体的问题我在发别的issue。感谢你的回复。
※对于这个issue，我的问题已经解决。希望对提问者有帮助
