### ISSUE TITLE
启动成功后 grafana 界面的css、js文件加载不出来

### ISSUE THREAD

**Issue by yijingping** [gjmzj/kubeasz#84]
![image](https://user-images.githubusercontent.com/2122123/35029565-832487c8-fb96-11e7-9ff1-9a9f7763905e.png)

**Comment by gjmzj** [comment]
这个问题不是css、js加载的问题，请按照项目[heapster文档](https://github.com/gjmzj/kubeasz/blob/master/docs/guide/heapster.md)安装，你用的官方heapster yaml文件有问题
