### ISSUE TITLE
master节点 calico 网络节点状态Calico process is not running

### ISSUE THREAD

**Issue by franplk** [gjmzj/kubeasz#88]
所有calico节点状态
calicoctl node status
Calico process is not running.

master节点查看镜像
docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
quay.io/calico/node   latest              80a64d11695d        3 weeks ago         270MB

node节点镜像
docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
calico/node                          v2.6.5              f4ab0d399175        3 weeks ago         279MB
calico/kube-controllers              v1.0.2              326eab7066ae        4 weeks ago         52.3MB
calico/cni                           v1.11.2             6f0a76fc7dd2        4 weeks ago         70.8MB

这里master是quay.io/calico/node镜像；node节点是calico/node

Ansible里面是对整个集群进行calico安装的，为啥只有node里面安装了，而master上没有安装

**Comment by gjmzj** [comment]
镜像拉取需要一定时间，某些节点启动会慢点的
