### ISSUE TITLE
master VIP并没有出现

### ISSUE THREAD

**Issue by evenye** [gjmzj/kubeasz#9]
首先谢谢您提供这么好的一套安装指导教程. 
请问我在执行的时候,并没有提示有什么错误,但是我ip a的时候并没有找到VIP的IP地址,在二台LB服务器上可以得到:
netstat -antlp|grep 8443   
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      899/haproxy    

但我ip a时,并没有找到我的VIP地址,
root@k8-d-1:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:a9:d0:df brd ff:ff:ff:ff:ff:ff
    inet 10.10.2.70/23 brd 10.233.3.255 scope global dynamic ens33
       valid_lft 86084sec preferred_lft 86084sec
    inet6 fe80::f68:8c63:a546:8f1e/64 scope link 
       valid_lft forever preferred_lft forever

请问这是什么原因呢? 还请给予一些指点,谢谢了!!!!!
我配置默认VIP地址是: 
MASTER_IP="10.10.2.17"         # api-server 虚地址
MASTER_PORT="8443"              # api-server 服务端口

**Comment by evenye** [comment]
我重新安装再配置后恢复正常了,谢谢.

**Comment by peterpijing** [comment]
@evenye 我在这个安装完成后，两台keepalived机器上同时执行ip a命令,两台都出现了VIP地址，你知道是什么原因吗？？
