### ISSUE TITLE
kube-dns错误

### ISSUE THREAD

**Issue by duanzonglong** [gjmzj/kubeasz#96]
master版本
191版本 单master多node 启动DNS后 路由无法查找
日志1
[root@localhost kubernetes]# kubectl logs kube-dns-5496dcff79-tscq7 -n kube-system -c kubedns
I0126 15:37:20.238783       1 dns.go:48] version: 1.14.4-2-g5584e04
I0126 15:37:20.239820       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0126 15:37:20.239869       1 server.go:113] FLAG: --alsologtostderr="false"
I0126 15:37:20.239881       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0126 15:37:20.239887       1 server.go:113] FLAG: --config-map=""
I0126 15:37:20.239891       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0126 15:37:20.239895       1 server.go:113] FLAG: --config-period="10s"
I0126 15:37:20.239901       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0126 15:37:20.239904       1 server.go:113] FLAG: --dns-port="10053"
I0126 15:37:20.239910       1 server.go:113] FLAG: --domain="cluster.local."
I0126 15:37:20.239915       1 server.go:113] FLAG: --federations=""
I0126 15:37:20.239920       1 server.go:113] FLAG: --healthz-port="8081"
I0126 15:37:20.239924       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0126 15:37:20.239928       1 server.go:113] FLAG: --kube-master-url=""
I0126 15:37:20.239932       1 server.go:113] FLAG: --kubecfg-file=""
I0126 15:37:20.239936       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0126 15:37:20.239942       1 server.go:113] FLAG: --log-dir=""
I0126 15:37:20.239946       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0126 15:37:20.239950       1 server.go:113] FLAG: --logtostderr="true"
I0126 15:37:20.239953       1 server.go:113] FLAG: --nameservers=""
I0126 15:37:20.239957       1 server.go:113] FLAG: --stderrthreshold="2"
I0126 15:37:20.239960       1 server.go:113] FLAG: --v="2"
I0126 15:37:20.239964       1 server.go:113] FLAG: --version="false"
I0126 15:37:20.239972       1 server.go:113] FLAG: --vmodule=""
I0126 15:37:20.240080       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0126 15:37:20.241416       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I0126 15:37:20.241446       1 dns.go:147] Starting endpointsController
I0126 15:37:20.241451       1 dns.go:150] Starting serviceController
I0126 15:37:20.241792       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0126 15:37:20.241815       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0126 15:37:20.741605       1 dns.go:171] Initialized services and endpoints from apiserver
I0126 15:37:20.741623       1 server.go:129] Setting up Healthz Handler (/readiness)
I0126 15:37:20.741631       1 server.go:134] Setting up cache handler (/cache)
I0126 15:37:20.741639       1 server.go:120] Status HTTP port 8081

日志2
[root@localhost kubernetes]# kubectl logs kube-dns-5496dcff79-tscq7 -n kube-system -c dnsmasq
I0126 15:37:20.485415       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local./127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0126 15:37:20.485575       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local./127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0126 15:37:20.514373       1 nanny.go:111] 
W0126 15:37:20.514408       1 nanny.go:112] Got EOF from stdout
I0126 15:37:20.514498       1 nanny.go:108] dnsmasq[11]: started, version 2.78-security-prerelease cachesize 1000
I0126 15:37:20.514517       1 nanny.go:108] dnsmasq[11]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0126 15:37:20.514522       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0126 15:37:20.514526       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0126 15:37:20.514530       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0126 15:37:20.514534       1 nanny.go:108] dnsmasq[11]: reading /etc/resolv.conf
I0126 15:37:20.514538       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0126 15:37:20.514542       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0126 15:37:20.514546       1 nanny.go:108] dnsmasq[11]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0126 15:37:20.514550       1 nanny.go:108] dnsmasq[11]: using nameserver 10.211.55.1#53
I0126 15:37:20.514554       1 nanny.go:108] dnsmasq[11]: read /etc/hosts - 7 addresses

日志3
[root@localhost kubernetes]# kubectl logs kube-dns-5496dcff79-tscq7 -n kube-system -c sidecar
ERROR: logging before flag.Parse: I0126 15:37:20.871125       1 main.go:48] Version v1.14.4-2-g5584e04
ERROR: logging before flag.Parse: I0126 15:37:20.871209       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
ERROR: logging before flag.Parse: I0126 15:37:20.871242       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
ERROR: logging before flag.Parse: I0126 15:37:20.871322       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}

**Comment by duanzonglong** [comment]
我试了1.8和1.9
服务都日志也都正常
nslookup nginx 这一步都验证不通过 后面heaspter也因为这里服务无法访问到报错
是少了哪一步吗

**Comment by gjmzj** [comment]
问题很清晰，dns组件中的sidecar有错误日志，但是整个dns组件的解析功能似乎是正常的

**Comment by duanzonglong** [comment]
重试了几次 dns都不是很稳定 偶尔才可以解析成功几次 试着删除再次创建 都不行 可有什么检查办法？

**Comment by gjmzj** [comment]
dns日志最后那个sidecar的错误日志其实是没关系的，目前猜测你dns插件是正常的，而是集群某些节点访问dns服务可能网络不通，参考[issue58822](https://github.com/kubernetes/kubernetes/issues/58822)
你是云虚拟主机创建的吗？
你分步安装网络插件的时候有没有验证过网络插件功能？
提供下网络插件的信息
