### ISSUE TITLE
二进制文件缺失

### ISSUE THREAD

**Issue by mds1455975151** [gjmzj/kubeasz#97]
![image](https://user-images.githubusercontent.com/12950929/35481088-97011cf6-0457-11e8-82b3-ecfb196f3ae4.png)
![image](https://user-images.githubusercontent.com/12950929/35481110-f9622d68-0457-11e8-99fd-af38dbb21a39.png)

请确认打包文件是否完整

**Comment by gjmzj** [comment]
百度云盘中，只有最新的`k8s.191.tar.gz` 有这几个二进制，因为之前项目不支持flannel，只有master分支最新的才支持

**Comment by mds1455975151** [comment]
好的
