### ISSUE TITLE
MASTER_IP没有添加

### ISSUE THREAD

**Issue by henghasaint** [gjmzj/kubeasz#99]
执行 ansible-playbook 01.prepare.yml，在lb和上没有发现MASTER_IP（192.168.0.204）。
在执行ansible-playbook 06.kube-node.yml后，报错如下：
TASK [kube-node : kubelet-bootstrap-setting] ***********************************************************************************
skipping: [192.168.0.222]
skipping: [192.168.0.223]
fatal: [192.168.0.221]: FAILED! => {"changed": true, "cmd": "sleep 15 && /root/local/bin/kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap", "delta": "0:00:21.255984", "end": "2018-01-30 15:50:56.065169", "msg": "non-zero return code", "rc": 1, "start": "2018-01-30 15:50:34.809185", "stderr": "Unable to connect to the server: dial tcp 192.168.0.204:8443: getsockopt: no route to host", "stderr_lines": ["Unable to connect to the server: dial tcp 192.168.0.204:8443: getsockopt: no route to host"], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by henghasaint** [comment]
找到原因： 
默认的virtual_router_id 的值与内网中的keepalived相同

**Comment by doterme** [comment]
@henghasaint 我也遇到这个问题了，要怎么解决呢

**Comment by henghasaint** [comment]
@doterme 
修改/etc/ansible/roles/lb/templates/下的keepalived-backup.conf.j2和keepalived-master.conf.j2中virtual_router_id的默认值51改为其他值如135 限定在1-255之间，否则VIP无法添加成功。
